- instat/dlgOutputforCPT.designer.vb
- instat/dlgOutputforCPT.vb
Modification to Output for CPT, with all parameters.
> Output for CPT - Climatic Methods Menus

- instat/ucrSelector.vb
This is done to avoid multiplication of variables inside the ucrSelectorAddRemove
> Fix a bug in ucrSelector  

- instat/clsGridLink.vb
- instat/dlgEndofRains.vb
- instat/dlgExtremeEvents.vb
- instat/dlgFileNew.vb
- instat/dlgOneSample.vb
- instat/dlgStartofRains.vb
- instat/dlgWaterBalance.vb
- instat/frmEditor.Designer.vb
- instat/frmEditor.vb
- instat/frmMain.Designer.vb
- instat/frmMain.vb
- instat/frmMetaData.designer.vb
- instat/frmMetaData.vb
- instat/frmVariables.designer.vb
- instat/frmVariables.vb
- instat/instat.vbproj
- instat/rLink.vb
- instat/static/InstatObject/R/data_object.R
- instat/static/InstatObject/R/instat_object.R
Implemented new syncing method between grids and Instat object and updated some functions on the file menu (some not working and some incomplete)
> Grid syncing, Instat object & File Menu

- instat/dlgPermuteRows.Designer.vb
- instat/dlgPermuteRows.vb
- instat/dlgYearRaincount.designer.vb
- instat/dlgYearRaincount.vb
> dlgPolynomials: adding r code to the dialog

- instat/clsRLink.vb
- instat/dlgRegularSequence.designer.vb
- instat/dlgRegularSequence.vb
Dates option disabled since still needs further work. Discussions on dialog design and preview window needed and desired functionality e.g. from = 1, to = 10, by = 1 produces `rep(x = seq(from = 1, to = 10) , length.out = 36)` instead of `seq(from = 1, to = 10, length.out = 36)`. Should both be possible?
> Fixed regular sequence for numeric sequences

- instat/dlgFromLibrary.vb
This fixes #1220 for Plotrix package. Some data sets from datasets package still do not load for other reasons.
> Fixed bug in import from library dialog - some data sets did not load

- instat/dlgPermuteColumn.vb
- instat/dlgPolynomials.vb
- instat/dlgRandomSample.designer.vb
- instat/dlgRandomSample.vb
- instat/dlgRegularSequence.vb
- instat/dlgRowStats.vb
Polynomials:
TestOKEnabled is now False for if there is no column name
Row Statistics:
TestOKEnabled is now False for if there is no column name
Regular Sequence
TestOKEnabled is now False for if there is no column name
TestOKEnabled is now False for if notthing is selected for the nud: from, to, instepsof and repeatvalues
Generate Random Sample
Set Validation Type as R Variable for the Prefix
Permute Column Dialogs
TestOKEnabled is now False for if there is no column name
> Amended a few small bugs for the following dialogs:

- instat/dlgColumnStats.vb
- instat/dlgCombine.Designer.vb
- instat/dlgCombine.vb
- instat/dlgName.Designer.vb
- instat/dlgRenameDescriptive.Designer.vb
- instat/dlgSplitText.Designer.vb
- instat/dlgSplitText.vb
- instat/dlgTransformText.Designer.vb
- instat/dlgUnstack.Designer.vb
- instat/dlgUnstack.vb
- Transform Text (Corrected a spelling error)
- Factor: Combine (The dialog was in the top left hand corner)
- Split (Dialog was in top LHC)
- Rename Descriptive (Dialog was in top LHC)
- Name (Dialog was in top LHC)
- Unstacked (Dialog was in top LHC, and amended a TestOKEnabled code)
> Amended Dialog Designs for:

- instat/dlgMakeDate.vb
- instat/frmMain.vb
I have changed the format of origin from "30-12-1899" to "1899-12-30" for both excel and Gregorian... after noticing an anomaly in the output given.
i.e
as.Date(42034,origin="30-12-1899 (Excel)")
[1] "0146-01-18"
> as.Date(42034,origin="1899-12-30(Excel)")
[1] "2015-01-30"
And too put a constrain on the Single column (when specify origin is checked) to only accept numeric variables to avoid error message in case a different datatype is provided for conversion.
> Changes on the specify origin option

- instat/dlgMakeDate.Designer.vb
- instat/dlgMakeDate.vb
Trying to add this enhancement on the make date...
""I think we need to change the idea of 2-digit years.
There should be a checkbox somewhere, default unchecked with
"2-digit years". If checked, then open an up-down control from 0 to 100 with the label "Cutoff for 2000 years".
The idea is that if it is less than the number given, then the year is in the 2000's. If more or equal, then it is in the 1900s. For example 20 means that 15 is made into 2015, while 25 is 1925. If give 0 then all years are in the 1900s. If you give 100 then all are in the 2000's"
@dannyparsons ,... in the method you wrote, I think you will add a parameter to use this additional feature suggested by Roger on the 2-digit years.
> 2-digit Enhancement on Make Date

- instat/dlgImportDataset.vb
- instat/dlgOpenSST.vb
- instat/ucrInput.vb
- instat/ucrInputComboBox.vb
- instat/ucrInputTextBox.vb
auto change is now done without a message - only used in Import and SST dialog so far
> removed validation message to auto change an invalid R variable

- instat/dlgMakeDate.vb
Disabled them because they are still awaiting to be implementation. This is to make sure that the dialogue looks good - most of them were invisible thus leaving large empty spaces on the dialog. 
*To be returned to how it was after beta release (Implemented as required).
> Disabling Make date check boxes,..

- instat/dlgRownamesOrNumbers.vb
Disenabling the OK button whenever the ucrRreceiver is empty and vice versa when non-empty.
This is when rhe radio button Set Row Names from Columns radio button is clicked.
> Dlg RowNamesOrNumbers 

- instat/UcrGeomListWithAes.designer.vb
- instat/UcrGeomListWithAes.vb
- instat/dlgGeneralForGraphics.vb
- instat/sdgLayerOptions.vb
List of changes:
- global aes fill when difference between global and local dataframes
- adding IgnoreGlobalAes when difference between global and local dataframes
- correct the add "stat = identity" method
> Sdglayeroptions + ucrGeomListWithAes: solving LayerOptions bugs

- instat/dlgCombineText.Designer.vb
- instat/dlgCombineText.vb
Name prefix in Defaults
Tab Order
Fixed Bug - upon reopening the dialog, the order of the variables to combine would flip (i.e., it would combine as ABC first time, CBA second time, ABC third, CBA, ... etc)
Bug issue - if you input variables as A B C, then it combines them as C B A always. I'm not sure how to fix this, although have been trying.
So, it was going
FIRST TIME:
Combine5 <- stringr::str_c(**X2**=InstatDataObject$get_columns_from_data(use_current_filter=FALSE, col_names="**no**", data_name="border_dataframe"), **X1**=InstatDataObject$get_columns_from_data(use_current_filter=FALSE, col_names="**dai**", data_name="border_dataframe"))
SECOND TIME:
Combine6 <- stringr::str_c(**X1**=InstatDataObject$get_columns_from_data(data_name="border_dataframe", col_names="**dai**", …
> Combine Text

- instat/frmSetupLoading.Designer.vb
Got the form to start at the center of the screen. it looks more appropriate there.
> fixing frmSetuploading properties

- instat/dlgOneWayFrequencies.Designer.vb
- instat/dlgOneWayFrequencies.vb
- instat/frmMain.Designer.vb
- instat/frmMain.vb
- instat/instat.vbproj
In Progress...
Issue: In R studio, the output of `sjt.frq`  by default is given in the output window  but this can be redirected to HTML  by changing  `use.viewer`  parameter from default as `TRUE`  to `FALSE`.
`sjt.frq(efc$e42dep,use.viewer=FALSE)` -HTML
`sjt.frq(efc$e42dep,use.viewer=TRUE)`- Rstudio output window
@dannyparsons @stevekogo 
Now coming to R-instat I am having a challenge redirecting the output to the R-Instat output window for the case of tables.  The tables (output) are redirected to  HTML which I guess is not what is required. I have tried using iCallType 2 and adding the parameter  `use.viewer` to control this, but apparently this does not help. 
For the graphs - its displaying well on the output window. 
@rdstern , Is the Weights check box supposed to pass `weight.by` …
> DlgOneWayFrequencies

- instat/clsGridLink.vb
- instat/clsRLink.vb
- instat/frmEditor.vb
- instat/frmMain.Designer.vb
- instat/frmMain.vb
- instat/instat.vbproj
- instat/ucrButtons.vb
- instat/ucrColumnMetadata.Designer.vb
- instat/ucrColumnMetadata.resx
- instat/ucrColumnMetadata.vb
- instat/ucrDataFrameMetadata.Designer.vb
- instat/ucrDataFrameMetadata.resx
- instat/ucrDataFrameMetadata.vb
- instat/ucrDataView.Designer.vb
- instat/ucrDataView.resx
- instat/ucrDataView.vb
- instat/ucrLog.Designer.vb
- instat/ucrLog.resx
- instat/ucrLog.vb
- instat/ucrOutputWindow.Designer.vb
- instat/ucrOutputWindow.resx
- instat/ucrOutputWindow.vb
- instat/ucrScript.Designer.vb
- instat/ucrScript.resx
- instat/ucrScript.vb
@africanmathsinitiative/instat Here is a suggested change to the frmMain layout - partly prompted by the difficultly we saw students had with the mdi child form system. This uses split containers to keep sections of the form separate while still allowing flexibility in resizing.
Please make a copy of this branch and play around and test. Let me know what you think, whether it is an improvement and any suggestions.
> added user controls for all mdi child forms and implemented new window system in frmMain using split containers

- instat/dlgDuplicateColumns.Designer.vb
- instat/dlgDuplicateColumns.vb
Changes made:
- Bug fix. It was reading in the name of the column not the contents
- Updated some of the code in the SetDefaults sub
- Bug fix. ucrInputColumnName only has a name once something has been inputted in the receiver, so there was a developer error upon opening the dialog when nothing was in the receiver.
> dlgDuplicateColumns

- instat/dlgRandomSubsets.vb
@dannyparsons I have allowed all data types now. fixes #3089
> Allowing all data types in the selector of Random Subset dialog

- instat/dlgJitter.vb
The parameter `n` could be updated wgen you changed from one data frame to the other.
> Dlg Jitter Bug Fix on change of data frames

- instat/clsRLink.vb
- instat/dlgLabels.Designer.vb
- instat/dlgLabels.vb
- instat/dlgRecodeFactor.vb
- instat/dlgReferenceLevel.vb
- instat/dlgRemoveUnusedLevels.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrFactor.vb
- instat/ucrFilter.vb
The main change here is to include "levels" as well as "labels" for factors. Our new language uses 
"label" - a text value corresponding to each category of a factor
"level" - a number value corresponding to each category of a factor
So in levels/labels dialog you can now set a level and a label for each category or "level" (double meaning of level)
You can also just use labels if you don't care about levels
This has affected the following dialogs which use factor grids:
dlgLabels
dlgRecodeFactor
dlgReferenceLevel
dlgRemoveUnusedLevels
ucrFilter
Note that only labels dialog has visibly changed, as the others don't need to include the levels, but the code changes affect all of them so they need testing.
@Lunalo this builds on the changes from your branch. Can you review this? I suggest …
> Implementing use of labels and levels in dialogs with factor grids

- instat/dlgBarAndPieChart.vb
- instat/dlgBoxPlot.vb
- instat/dlgCumulativeDistribution.vb
- instat/dlgDotPlot.vb
- instat/dlgGeneralForGraphics.vb
- instat/dlgHistogram.vb
- instat/dlgImportDataset.vb
- instat/dlgLinePlot.vb
- instat/dlgRugPlot.vb
- instat/dlgScatterPlot.vb
- instat/dlgSummaryBarOrPieChart.vb
- instat/dlgUseGraph.vb
- instat/sdgPlots.vb
- instat/ucrSelector.vb
@maxwellfundi here I have linked the selector on the main dialog to the facet selector on the sub dialog so that the facet variables can be included if we do a temporary stack.
I noticed that none of the main dialog are linked to the layer options dialogs, the setup lines are commented out. Why is this not done?
> various bug fixes

- instat/dlgConvertColumns.Designer.vb
- instat/dlgConvertColumns.vb
- instat/dlgTransformText.vb
@dannyparsons this is ready to review
I've addressed the issue of the developer error when reopening when a ucrInput has a different value inputted from specified in Initialise()
> Transform split bug fix

- instat/dlgExportGraphAsImage.Designer.vb
- instat/dlgExportRObjects.Designer.vb
- instat/dlgExportRWorkspace.Designer.vb
- instat/dlgFromLibrary.Designer.vb
- instat/dlgImportDataset.Designer.vb
- instat/dlgOpenSST.Designer.vb
Here I have changed Select File to Browse
Or removed the ellipsis from Browse. According to the Windows documentation we shouldn't use an ellipsis on Browse as the word "Browse" already implies a new window.
@dannyparsons this is ready to review
Fixes #2974
> Changing Select File to Browse

- instat/dlgStartofRains.vb
- instat/dlgTransformText.Designer.vb
- instat/dlgTransformText.vb
@africanmathsinitiative/developers small fix for #3772 - this is ready to be reviewed. Here the default column name is now
`ColumnInReceiver_transformed`
As opposed to before where it was
`DataFrame_transformed`
> Transform text fix

- instat/dlgClimaticSummary.Designer.vb
- instat/dlgClimaticSummary.vb
> Climatic Summary

- instat/dlgCalculator.designer.vb
- instat/dlgCalculator.vb
- instat/dlgContrasts.vb
- instat/dlgDisplayDailyData.Designer.vb
- instat/dlgOpenNetCDF.vb
- instat/dlgStringHandling.vb
- instat/dlgThreeVariableFrequencies.Designer.vb
- instat/dlgThreeVariableFrequencies.vb
- instat/dlgTransformText.vb
- instat/dlgTwoWayFrequencies.Designer.vb
- instat/dlgTwoWayFrequencies.vb
- instat/ucrCalculator.Designer.vb
- instat/ucrCalculator.vb
- instat/ucrDialogDisabled.Designer.vb
@africanmathsinitiative/developers another interesting issue here related to displays on different screens. I noticed when testing on my machine some dialogs were very small and cut off most of the controls. I realised this was only on dialogs where the size changes depending on options e.g. calculator expands for different keyboards.
The reason these dialogs don't display correctly on some screens is that the size is set directly in the dialog code which is interpreted differently on different machines. So the solution is to not have fixed sizes set in the dialog but to make it proportionally bigger or smaller. It's easiest to see with an example. The next time someone has to do this, these are roughly the steps:
1. In the designer work out all the different sizes you want the dialog to …
> Dialog sizes and alignment fixes

- instat/clsRLink.vb
@Muthenya can you try this branch to see how this works on your machine? 
Change the setting back to Output Window and then rerun. It should display a different message about the issue and the display the graph in the R viewer. I haven't fixed the saving issue yet but at least this should mean graphs can still display.
> temporary fix to png error when display graphs in output

- instat/clsRLink.vb
- instat/frmMain.vb
@africanmathsinitiative/developers this is a change to the core RLink code. I've tested this quite a bit so should be fine, but please report any issues with this quickly if you find anything, as it would be a major bug if there are errors here.
> added a check on load for correct R version installed

- instat/instat.vbproj
@dannyparsons  Removed the System.Net.Http reference.
Was not used anywhere. A simple google shows that its no longer in .Net framework by default.
> Runtime Warnings

- instat/clsRLink.vb
- instat/dlgBackupManager.Designer.vb
- instat/dlgBackupManager.resx
- instat/dlgBackupManager.vb
Changes to the `clsRLink`, Subroutine `LoadInstatDataObjectFromFile` . 
@dannyparsons you can review the subroutine `LoadInstatDataObjectFromFile` .  I have commented out the original code statements so that you can compare the changes.
@africanmathsinitiative/developers we can have an interesting discussion on  `clsImportRDS.ToScript(strScript)` subroutine with @volloholic .
This is continuation of #4240
> Dialog Backup Manager

- instat/clsRLink.vb
- instat/sdgCalculationsSummmary.vb
- instat/static/InstatObject/R/Backend_Components/link.R
- instat/static/InstatObject/R/Backend_Components/summary_functions.R
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrReceiver.vb
- instat/ucrReceiverMultiple.vb
- instat/ucrReceiverSingle.vb
- instat/ucrSelector.vb
- instat/ucrSelectorByDataFrame.vb
@africanmathsinitiative/developers there are changes to some main user controls here but the functionality of dialogs should not be affected. The new functionality is used when `bAttachedToPrimaryDataFrame = False` for a receiver, the default is `True`. Currently only `sdgCalculationsSummmary.vb` has such a receiver.
This will be common on climatic dialogs soon e.g. to select the start day from a linked data frame.
> Added functionality to select columns from different data frames on the same dialog

- instat/ucrScript.Designer.vb
- instat/ucrScript.vb
As of now, this copies/cuts the entire text in the script window. I wonder if we could include an option of copying/cutting  selected text. 
Fixes #4389
> Adding Cut/Copy/Paste for the script window 

- instat/static/InstatObject/R/Backend_Components/DisplayDaily.R
@shadrackkibet This is now ready to be implemented in the Display Daily dialog. The parameters are slightly different but similar. Note that the margin summaries (`monstats`) can now be a list of summaries.
There are no defaults for the codes because they are optional. But I suggest the dialog defaults are:
```
Misscode = "-"
Tracecode = "tr"
Zerocode = "--"
```
> changed defaults for codes in display daily

- instat/clsRSyntax.vb
- instat/dlgCompareColumns.Designer.vb
- instat/dlgCompareColumns.resx
- instat/dlgCompareColumns.vb
- instat/static/InstatObject/R/stand_alone_functions.R
- instat/ucrReceiver.vb
- instat/ucrReceiverSingle.vb
- instat/ucrSave.vb
- instat/ucrSelector.vb
@africanmathsinitiative/developers this is ready for review. This is a new dialog for Prepare > Check Data (and the new Options by Context menu), useful for comparing the values in two columns before doing a merge to check the values match, so likely the two columns will be from different data frames. An example is comparing the values in the station columns of the three data frames in the Western Kenya data.
@shadrackkibet I have added to our functionality for getting columns from different data frames. It shouldn't affect how this works in existing climatic dialogs but please check.
> Added R code and dialog for Compare Columns

- instat/dlgClimaticCheckDataRain.vb
> Qc Rainfall

- instat/sdgPlots.Designer.vb
- instat/sdgPlots.resx
- instat/sdgPlots.vb
> Adding labeller parameter on facet function

- instat/dlgSort.Designer.vb
- instat/dlgSort.vb
This fixes issue #5048. @africanmathsinitiative/developers this is ready for review.
> Clearing the previously selected columns on reopen in the sort dialog.

- instat/ucrVariablesAsFactor.vb
This removes one potential cause of an error when using multiple variables in a plot. 
With this change, all columns are now carried when stacking so we do not need to keep track of all columns used in the dialog. Errors such as "column not found in data" should now be eliminated.
> removed id.vars from stacking data for multiple variables

- instat/DlgDefineClimaticData.Designer.vb
- instat/DlgDefineClimaticData.resx
- instat/DlgDefineClimaticData.vb
- instat/dlgClimaticBoxPlot.vb
- instat/dlgPICSARainfall.vb
- instat/sdgDoyRange.vb
- instat/sdgPICSARainfallGraph.vb
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrReceiver.vb
- instat/ucrVariablesAsFactor.vb
- doy range sub dialog now only shows numeric columns
- improved messages on define climatic
- facets correctly enabled after using climatic boxplot options
- PICSA rainfall only allows numeric and excludes Date column on y-axis to avoid confusion
- Corrected setting selector heading for the variables as factor control
- PICSA graphs: fixed display of mean label for dates
- PICSA graphs: changed label position for lower tercile to below
- corrected PICSA crops calculation for incomplete years
- corrected PICSA crops proportions calculations with missing years
> Various climatic bug fixes

- instat/dlgPICSARainfall.vb
- instat/ucrReceiver.vb
- instat/ucrReceiverSingle.vb
Implements the suggestion in #5428. Climatic dialogs should autofill the same as before but will now also display full list of variables, not just the climatic defined ones. In particular, climatic dialogs are usable without defining.
It might be sensible for someone to take over this branch and make the necessary changes on the climatic dialogs to fully test this. 
See the required changes to climatic dialogs here: https://github.com/africanmathsinitiative/R-Instat/issues/5428#issuecomment-516462624
Some thought is needed to get the correct restrictions on the receivers now.
Still to do is implement autofilling of multiple items in a multiple receiver. I suggest this is for a separate pull request.
> changed use of defined climatic variables

- instat/sdgPlots.vb
- instat/ucrAxes.vb
> Plot Options Subdialog.  X-Axis and Y-Axis unshown options

- instat/ucrCalculator.vb
Fixes #5520
For logical and Symbol keyboard, the tooltips have been added for most of the keys.
@africanmathsinitiative/developers Someone can review this
> Added tooltips for Logical and Symbols keyboard

- instat/dlgUseModel.Designer.vb
- instat/dlgUseModel.vb
> Segmented keyboard#5584

- instat/dlgTreemap.Designer.vb
- instat/dlgTreemap.resx
- instat/dlgTreemap.vb
Implements the `treemap` graph from the `treemapify` package, see details here https://cran.r-project.org/web/packages/treemapify/vignettes/introduction-to-treemapify.html
An interesting test is to use the WorldBank97 data from the Procurement library and use `country` as the identifier. You could also weight by the contract value. This will test the "Primary data" option. Use the "country" sheet to test the "Summary data" option.
- Install the `treemapify` package to test as it's not yet included in R-Instat
- I have excluded the dialog from the project so that there are no vbproj changes. To test, include in the project and add the dialog somewhere in frmMain. Eventually this will be a graph under the describe menu, and on the …
> New treemap dialog

- instat/dlgDescribeTwoVariable.Designer.vb
- instat/dlgDescribeTwoVariable.resx
- instat/dlgDescribeTwoVariable.vb
- instat/dlgOneVariableSummarise.Designer.vb
- instat/dlgOneVariableSummarise.resx
- instat/dlgOneVariableSummarise.vb
- instat/sdgDescribeDisplay.vb
- instat/static/InstatObject/R/Backend_Components/summary_functions.R
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrReceiverMultiple.vb
- dialog design modified, checkbox for customise replaced with radio buttons
- improved display of names of summaries in output
- removed scientific notation of summaries
- corrected summaries for Dates
- corrected error for invalid summaries on some data type
- ordered summaries in output by size and groupings
**Edit**
Added improvements to two variable summarise dialog here since the improved summary methods were needed
- added a box on the dialog showing the summary that will be done based on the variables selected
- allowed for broad categorical/numeric types (implemented in multiple receiver) to be chosen in the first receiver (e.g. factor and character are allowed together, or numeric and date)
- created a correlation function that ensures columns are converted to numeric first …
> One & two variable summarise improvements

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
- fixed bug reported here https://github.com/africanmathsinitiative/R-Instat/pull/5574#issuecomment-554724349 when logical column is both a first and second variable (considered as different types) on two variable summarise. 
@rdstern Since the logical column appears twice in the summary data frame, it is actually not a problem for it to be of different types - logical considered as factor, and numeric. Here is an example output with Death (factor) and Death.1 (numeric):
> Bug fix for logical columns on 2 variable summarise

- instat/clsGridLink.vb
- instat/clsRLink.vb
Created new function `clsRLink.GetDataFrameCount()` which returns the number of data frames in `data_book`.
Added an extra check in `clsGridLink.UpdateGrids()` so that the grid is only updated if there is at least one data frame.
> Solves #5613 problem deleting only data frame.

- instat/clsRLink.vb
Fixes #5577. This was caused by the following:
- `RLink.RunScript(...)`, line 570
- Calls `Evaluate(...)` with the R script (e.g. `.temp_val <- capture.output(2+x)`)
- `Evaluate(...)` returns `True` if script executed successfully, else `False`
- Line 570 ignores the return value
- `RLink.RunScript(...)`, lines 571-577
- Extracts and displays the value of `.temp_val`
- If the script was not successful then `.temp_val` still contains its previous value (or is potentially undefined)
Issue fixed by:
- line 570: Check the return value of `Evaluate(...)`
- If `True` then
- Extract and display the value of `.temp_val`
- Remove `.temp_val` (as recommended by @dannyparsons it's good to keep the R environment tidy and remove variables after using them)
- Else do nothing
> fixes #5577 Errors in R-Instat repeat the previous command

- instat/dlgView.vb
Fixes #5262 by ensuring that that the R script is updated whenever the contents of the `Variable(s) To View` window is updated.
> Fixes #5262 Data receiver in View dialogue does not clear

- instat/dlgNewDataFrame.vb
I was still looking at what was causing the change to the text for button examples
> Fixed the button examples problems on the new dataframe dialog

- instat/dlgExportGraphAsImage.Designer.vb
Changing the  image  fieldname  textbox  for dlgExportGraphAsImage as read only #5589
> Having the ExportFile,fieldName textbox, in dlgExportGraphAs Image as read only

- instat/dlgRownamesOrNumbers.vb
disabling the use of filters in the row names dialogue #5608
> Removing filters from row names dialogue

- instat/clsRLink.vb
- instat/ucrScript.vb
Fixes #5742 Issue multiline commands in script window.
Note that this issue also has an optional enhancement to allow multi-line functions (enclosed with '{' and '}') to be executed in the script window. This PR does **not** implement this optional enhancement.
**Issue**
In the R-Instat script window, if the user splits commands over multiple lines then R-Instat displays an error. 
@rdstern and @dannyparsons requested that if a script line ends with '+', ',', or '%>%', then the command may continue onto the next line.
**Analysis and solution**
The R  script window commands are processed by 'ucrScript'. It would be possible to add the multi-line functionality to this class.
However, R scripts can also be manually executed from the log window. Therefore I decided to add the multi-line …
> Fixes #5742 Issue multiline commands in script window

- instat/clsRLink.vb
- instat/ucrScript.vb
PR #5796 had merge conflicts. I could not fix them in a good way so I made this new PR from the master branch and reimplemented the changes.
@Patowhiz You have already peer reviewed these changes. The only new part is the check for open double quotations (") on lines 372 and 376. Please could you quickly review these lines? Thanks
@rdstern The test case below should now pass. Please could you test? Thanks
P.S. It's strange that the '=' works on the last line, but not the first!
```
Input <- ("
Individual  Hand     Length
A           Left     17.5
B           Left     18.4
C           Left     16.2
D           Left     14.5
E           Left     13.5
F           Left     18.9
G           Left     19.5
H           Left     21.1
I           Left     17.8
J           Left     16.8
K …
```
> Replaces PR #5796 Issue multiline commands in script window

- instat/clsPopup.vb
- instat/instat.vbproj
@lloyddewit @maxwellfundi this is an empty `class` meant to hold the code that will be creating the popup used in several dialogs. 
Since I last created such a popup for the comment section, github issues have been created demanding more use of it (currently there is another dialog that needs this feature outlined by @rdstern in issue #5596 and possibly more will arise). Because of this we had discussed with @dannyparsons to have this as a reusable component that can be used in any dialog without much of re-implementation( and copy paste). Check out more about this `component` in issue #5876 . 
So I have added an empty class so that this can be merged quickly and avoid conflicts incase another item is added to the R-Instat `solution`. After this is merged I'll push the code needed to …
> Empty clsPopup

- instat/dlgHypothesisTestsCalculator.Designer.vb
- instat/dlgHypothesisTestsCalculator.resx
- instat/dlgHypothesisTestsCalculator.vb
> Added Trend keyboard and general changes to layout for the Hypothesis Tests dialog

- instat/dlgCompareSummary.Designer.vb
- instat/dlgCompareSummary.vb
- instat/sdgVerificationSummaries.Designer.vb
- instat/sdgVerificationSummaries.vb
- instat/static/InstatObject/R/Backend_Components/summary_functions.R
- instat/ucrContinuousVerification.Designer.vb
- instat/ucrContinuousVerification.resx
- instat/ucrContinuousVerification.vb
Fixes #5843. This is still work in progress. Continuous options working now. Coming soon!
> Verification of forecasts and satellite data - Summaries dialog

- instat/dlgStack.Designer.vb
- instat/dlgStack.resx
- instat/dlgStack.vb
Relates to #5831 but a new aspect has been noted in #5831 after this pull request is merged. 
Changes:
* Design changes to "tidy up" the stack dialog
Unable to fix the ucrSave problem - this seems to be an issue on similar dialogs (aside from when the "Position" button is visible?). Is there a way to do this that I am missing, and if not has this been recorded as an issue?
Before:
After:
> Dlgstackdesign

- instat/dlgExportDataset.resx
- instat/dlgExportGraphAsImage.resx
- instat/dlgExportRObjects.resx
- instat/dlgExportRWorkspace.resx
Fixes #5879 
Minor design changes to the "File > Export" dialogs:
* Tab order
* Receiver/Browse button aligned with ucrBase
* "Export File" label moved.
To see "before" screenshots, see #5879
> File Export Dialogs - design 

- instat/dlgHomogenization.Designer.vb
- instat/dlgHomogenization.resx
- instat/dlgHomogenization.vb
Fixes #5461. @rdstern this contains an initial implementation of homogenization. This implements the three core functions from `changepoint` package i.e `cpt.mean(), cpt.var` and `cpt.meanvar()`. I did initial testing using the datasets from the `changepoint` package although some of these datasets are not well labelled. I also used Dodoma data at some point to check how these methods work in our area of application (Climate). But first I aggregate the data into Annual using climatic summaries for the reasons I outline below. So for this case, I obtained annual rainfall totals for testing.
My understanding is that homogenization of daily and sub-daily data is still an active area of research therefore applying homogenization methods is still not recommended. This is because daily data is …
> Initial Implementation of homogenization 

- instat/dlgInfillMissingValues.Designer.vb
- instat/dlgInfillMissingValues.resx
- instat/dlgInfillMissingValues.vb
- instat/static/InstatObject/R/stand_alone_functions.R
@rdstern I am putting up this for testing. I think I have been able to implement these methods for multiple stations and also the Average option can now use a multiple receiver, which means you can use multiple levels at a time. Please also check the start and end options under constant option if it works as discussed. I also added the `sample` as a function to be selected under average option dropdown (I think we need to rename this option to accommodate sample function but I am not sure what to call it now).
**NOTE** This is not ready for code checking.
> Using multiple stations and multiple levels for aggregate option when infilling missing values

- instat/ucrCheck.vb
Partly Fixes , issue #5838. (More controls to await such enhancements)
Currently to set the text of the checkbox, developers have to call `ucrCheck.SetText()`. This sometimes increases substantially the number of lines needed to write and during peer reviewing the team has to go through these lines which are basically more or less "labels" of the checkboxes. To take advantage of visual studio and have it write such trivial code for us, this subroutine has to be rewritten or complemented with a VB.NET property. The VB.NET property Text will now appear in the design properties panel of visual studio. 
Another critical advantage of this enhancement is, when designing the dialog the developers can now see the size that the text will …
> Check box text property

- instat/ucrFactor.vb
@rdstern I didn't find an issue for this but I remember this is something you mentioned at some point during our discussions. This change removes the selection of the first level of a factor when filtering for convenience purpose. Please test.
**Note:** This affects other places where this control is used, my assumption is that we do not need to always select the first level.
> Removed automatic selection of the first level of a factor when filtering and elsewhere

- instat/dlgDeleteObjects.Designer.vb
- instat/dlgDeleteObjects.resx
- instat/dlgDeleteObjects.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
Fixes #5792. @rdstern this is now working please test. I am concerned that we are enabling the user to delete a current filter and also "no_filter" this will cause bugs. One option is to hide them from the selector so that the user does not delete it or stop the user from deleting and give notification that it is not allowed.
> Adding options to delete filters and calculations - delete objects dialog

- instat/ucrFilter.vb
- instat/ucrInputComboBox.vb
- instat/ucrReceiverExpression.vb
@rdstern this PR fixes a small issue you reported in PR #5914. Please check, I might have misunderstood your statement below.
> Sounds good. Will check. One other (smaller) item in the filter sub-dialogue is that the control with the function ==, > etc doesn't get remembered between successive uses of the dialogue.
> Retaining an operator(==,> etc) on filter input

- instat/dlgRestrict.resx
- instat/dlgRestrict.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrFilter.Designer.vb
- instat/ucrFilter.resx
- instat/ucrFilter.vb
Fixes #5791. @rdstern this is ready for you to test. This is the implementation of the use of **&** and **|** operators in the filter.
> Enabling use of & and | operators in the filter 

- instat/ucrCore.vb
I made the integration of the comments from the ucrCoreNote document in ucrCore.vb class and comment also some remaining functions in ucrCore.vb. Your remark and suggestion will be welcome.
> Integrate comment from ucrCoreNote Doc to ucrCore.vb cls

- instat/dlgClimaticCheckDataTemperature.vb
> Autofilling the minimum and maximum temperature Receivers in the Climatic Check Data Temperature dialog

- instat/clsPopup.vb
- instat/dlgEnter.Designer.vb
- instat/dlgEnter.resx
- instat/dlgEnter.vb
- instat/instat.vbproj
Fixes #5596 . Fixes #5876.
This issue implements the popup component and also demonstrates through dlgEnter how other dialogs can use it. It's a continuation of PR #5877(which should be merged first) which has an empty class that represents the popup component. 
Once merged, the other dialogs that currently have code that is implemented in this component, can be amended to use it. 
@rdstern as discussed in issue #5596 the only thing waiting in the dialog are the samples and their tooltips. I will add them as soon as I get your feedback.
> Popup Component and dlgEnter Implementation

- instat/dlgCombine.resx
- instat/dlgFindNonnumericValues.Designer.vb
- instat/dlgFindNonnumericValues.resx
- instat/dlgPermuteColumn.resx
- instat/dlgPolynomials.resx
Fixes #5942 
Just a quick clear up of four dialog designs. "Before" screenshots are given in #5942 
1. Prepare > Check Data > Non-numeric cases
a) First letter of each word in the title of the dialog is now capitalised, with a hyphen added between "non" and "numeric"
b) The checkbox is made larger so the words can all be read
c) The data frame selector is at the usual (10,10)
d) Both words capitalised in new column name
e) Space between controls neatened up
Should the first letter for the words in the checkboxes here be capitalised? They are in most other dialogs (however, not in all. For example, the Import dialog).
2. Prepare > Column: Factor > Combine Factors
a) The ucrReceiver is moved down slightly
b) The "Separator" label …
> Prepare clear up

- instat/static/InstatObject/R/data_object_R6.R
Fixes #6000 
This fixes a bug in the R-code used in the dlgInventory dialog
1. Go to `File > Import from Library ...` and import the `ghana_two_stations.RDS` data set. This data set has a date column and not a year column. The bug was present in a data set without a year column (or without a year column defined in the climatic define dialog).
2. Go to `Climatic > Check Data > Inventory ...`
3. Enter the `Date` and `Elements`, and select `DOY-Year Plot` on the radio buttons
4. There used to be an error at this point. This PR fixes this error so that the code now runs.
> Minor bug fix in the R-code for `$make_inventory_plot`

- instat/dlgTimeSeriesPlot.vb
One minor change: `names_ptypes` added to `pivot_longer` to ensure that the reference and estimates columns always appear in the correct order in the labels of the graph.
This is the same as was done on the seasonality plot dialog as mentioned here https://github.com/africanmathsinitiative/R-Instat/pull/6006#issuecomment-705429670
> Time series plot dialog: added names_ptypes parameter to ensure labels are in correct order

- instat/dlgTidyDailyData.Designer.vb
- instat/dlgTidyDailyData.resx
- instat/dlgTidyDailyData.vb
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrReceiverMultiple.vb
fixes #5383 
@africanmathsinitiative/developers this is ready for review. Please test all 3 cases as the R code has changed substantially.
- allow 62 columns to be given for day option for flags
- added tooltips on radio buttons and receiver label to explain cases
- added label to show number of columns in multiple receiver
- set selector to remove columns added in a receiver to make selection clearer
- allowed month and year columns to be non-numeric
- added an "unstack elements" option for multiple elements
- stop and give output if unstacking and values are not unique
Also included here is a bug fix in `ucrReceiverMultiple`. The additional line added ensures that the selector refreshes when using the "Clear" option in the receiver. This is only important if the columns are removed from …
> Tidy climatic data dialog improvements

- instat/clsRCodeStructure.vb
- instat/clsRSyntax.vb
- instat/dlgCalculator.vb
- instat/static/InstatObject/R/Backend_Components/calculations.R
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
1. Fixed functionality so that when replacing an existing column, it stays in same position by default and also added parameter to the R methods to allow it to be moved when replaced (a control for this can be added to the positioning sub dialog in a separate PR)
2. Fixed bug in calculator where the `before` parameter, and therefore positioning a new column, was changed when reopening the dialog
3. Added `strAdjacentColumn` as a parameter to assign to methods as this is now part of the saving options
@africanmathsinitiative/developers This is ready for the review. 1. needs to be reviewed across dialogs that use the save control, please test carefully as this edits core parts of saving columns, and 2. only needs to be checked for the calculator dialog
> Saving and position columns bug fixes and changes

- instat/frmMain.resx
- instat/frmMain.vb
As requested in #6047 this PR adds the define survival object dialog to the main form.
> Adding survival dialog to frmmain

- instat/static/InstatObject/R/data_object_R6.R
This PR updates the `split_date` function to use `make_factor` function instead of the `factor` function where the levels are automatically set (i.e., where there is no levels parameter currently read in), this is as outlined in #6095
> Updating split_date function with make_factor

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
- instat/static/InstatObject/R/instat_object_R6.R
- `weights` parameter passed as `NULL` and correctly checked in summary functions so that Summary Tables dialog doesn't give error
- invalid dates data frame in tidy climatic data now a `data.frame` (not `tibble`) in all cases so that all rows are printed in output
> Fixed summary tables bug and display of invalid dates in tidy climatic data

- instat/static/InstatObject/R/instat_object_R6.R
Fixes #5893 @africanmathsinitiative/developers this is ready for review. This PR fixes the problem with the colouring of rows (red) when obtaining a subset from filtered data in the filter dialog.
Note
- Removed current filter when copying a data object and the filter is not missing.
> Obtaining a subset from filtered data - Fixed problem with colouring of rows

- instat/dlgRestrict.vb
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrDataView.vb
Fixes #5901, Fixes #6180 and Fixes #6181. @africanmathsinitiative/developers this is ready for review. 
Notes
- Removed resetting of state for apply options on load.
- Added a method for getting the filter name.
- Setting up the display of an active filter below the current sheet.
- Clearing the filter receiver.
> Display of a filter in operation and retaining of state of apply option on load - Filter dialog

- instat/dlgClimaticCheckDataRain.resx
- instat/dlgClimaticCheckDataRain.vb
- instat/sdgSelectMonth.vb
- instat/ucrNud.vb
Fixes part of #6115 and #5017. @rdstern this fixes the problem with the calculation of dry months on rainfall quality control.
Notes
- Added method that checks if nudUpDown is empty.
- Code refactor: sorted out parameter positions, test Ok fix and change to how `calculated_from` parameter is added into calculations.
- Bugfix: Ensuring that a monthly filter is not added when there are no months to omit.
- Changing the threshold label for dry months option.
> Bug fix: calculation of dry months on rainfall quality control

- instat/ucrColumnMetadata.vb
- instat/ucrDataView.vb
Fixes #4079. @africanmathsinitiative/developers this is ready for review.
Notes
- Disabled remove the current filter on column, row and cell right clicks when there is no filter and enabled otherwise
> Disabled remove current filter on right clicks

- instat/ucrColumnMetadata.Designer.vb
- instat/ucrColumnMetadata.resx
- instat/ucrColumnMetadata.vb
- instat/ucrDataFrameMetadata.Designer.vb
- instat/ucrDataFrameMetadata.resx
- instat/ucrDataFrameMetadata.vb
- instat/ucrDataView.vb
Fixes #5250 and Fixes #2967 @africanmathsinitiative/developers this is ready for review.
Notes
- Deleted extra separator, disabled freeze and unfreeze menu items
- Added and implemented facilities for tab context menu strip
- Enabled hide sheet when sheets > 1
- Removed some commented out code
> Added right-click functionality to the column metadata (bottom tab right-click) and the data frame metadata (row right-click)

- instat/dlgFromLibrary.vb
@africanmathsinitiative/developers this is ready for review. It is a minor designer fix. I have removed the space between the input control and the label in the save control.
Since there is no open issue that this PR fixes see below screenshots.
**Previous**
**Current**
> Removing space between label and input in the save control

- instat/dlgImportDataset.Designer.vb
- instat/dlgImportDataset.resx
- instat/dlgImportDataset.vb
fixes #6229 
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks
> Small bug fixes on Import Dataset dialog

- instat/dlgAddLink.vb
Fixes #6168
The bug was that the dialog would call an error if you opened the dialog without a data frame loaded into R-Instat.
This PR fixes this bug.
> Fixed bug in dlgAddLink triggered when dialog opened without a data frame loaded into R-Instat

- instat/dlgClimaticCheckDataTemperature.vb
Setting enable/disable difference checkbox when one element is missing. This solves issue #5013 
@shadrackkibet this is ready to review. Thanks
> Small bug fixes in Climatic Check Data Temperature dialog

- instat/dlgDuplicates.Designer.vb
- instat/dlgDuplicates.resx
- instat/dlgDuplicates.vb
Fixes #6239
Changes made:
* Added checkbox to run a summary of the new column (similar to as seen in Prepare > Check Data > Non-numeric Columns).
* Naming convention - changed "clsdupCountIndex" to "clsDupCountIndex"
> Added Summary checkbox to the Duplicates dialog

- instat/dlgMerge.Designer.vb
- instat/dlgMerge.resx
- instat/dlgMerge.vb
- instat/dlgMergeAdditionalData.resx
- instat/dlgMergeAdditionalData.vb
- instat/sdgMerge.Designer.vb
- instat/sdgMerge.resx
- instat/sdgMerge.vb
- instat/sdgMergeColumnsToInclude.Designer.vb
- instat/sdgMergeColumnsToInclude.resx
- instat/sdgMergeColumnsToInclude.vb
Replaces #6277
Fixes #6265
This PR separates the two tabs in the original sub-dialog into two separate sub dialogs (as described in #6265).
@dannyparsons this is ready for review. From what I can tell, the dialogs still automatically add in columns you merge by, even if you try to remove those columns in the "Columns to Include" tab. Is this okay?
> Separating the sub-dialog for Merge into two sub-dialogs

- instat/dlgMerge.vb
- instat/sdgMerge.Designer.vb
- instat/sdgMerge.resx
- instat/sdgMerge.vb
Fixes some of #6265
The joining options tab of the sub dialog now always shows users the choose pairs controls. By default this is filled with all columns with the same names. 
@rdstern this change could be tested but PR is not finished yet.
@lilyclements Could you take over this PR? The remaining task is to separate the two tabs into two separate sub dialogs as described in #6265. I suggest the current sub dialog stays as the Joining Options subdialog and the new sub dialog is for Columns to Include.
> Simplify Joining Columns options on Merge dialog

- instat/ucrColumnMetadata.Designer.vb
- instat/ucrDataFrameMetadata.Designer.vb
- instat/ucrDataView.Designer.vb
- instat/ucrDataView.vb
- instat/ucrLog.Designer.vb
- instat/ucrOutputWindow.Designer.vb
- instat/ucrScript.Designer.vb
This PR partially fixes issue #3721 . 
The translation mechanism requires that each translated item in a form has a unique name. `frmMain` has 6 output windows:
- Column Meta Data
- Data Frame Meta Data
- Data View
- Log
- Output
- Script
These 6 windows had the same name (`lblHeader`) for their header text. This PR renames each of the 6 names to a unique name.
This PR does not affect the functionality in any way.
@shadrackkibet , @rdstern Please could you approve/merge? thanks
> Ensure that each of the 6 output windows has a unique header item name (needed for translations)

- instat/dlgSetupForDataEntry.Designer.vb
- instat/dlgSetupForDataEntry.resx
- instat/dlgSetupForDataEntry.vb
- instat/instat.vbproj
@lloyddewit @dannyparsons this is an empty dialog requested in issue #6401 that needs to be merged. Thanks
> New Dialog to Setup Data Entry dialogue

- instat/dlgConvertColumns.Designer.vb
- instat/dlgConvertColumns.resx
Fixes #6489 
@rdstern I widened the controls so that the texts could be well visible. Please, have a look. Thanks.
> Improved presentation of French & Portuguese text in Convert Columns dialog

- instat/dlgBarAndPieChart.Designer.vb
- instat/dlgBarAndPieChart.resx
- instat/dlgBarAndPieChart.vb
Partially fixes #6135
This PR fixes the bug in the two comboxes to remember the states in reopen, and the presentation of the labels.
> Bug fixes: ensure comboxes to remember states in reopen of bar chart dialogue

- instat/sdgClimaticDataEntry.vb
Fixes pasting into the data entry bug.
@rdstern I noticed there is a bug when pasting into the climatic data entry sub dialog. The pasting doesn't start from the top. This PR adds 1 line of code that fixes the bug.
> climatic data entry pasting bug fix

- instat/dlgCopySpecial.Designer.vb
- instat/dlgCopySpecial.vb
- instat/instat.vbproj
@lloyddewit this adds a new empty dialog needed for Copy Special functionality. 
See issue #6579 for more information.
> Added empty placeholder for Copy Special dialog

- instat/dlgCopyDataFrame.vb
@rdstern this fixes the bug reported [here](https://github.com/africanmathsinitiative/R-Instat/pull/6567#issuecomment-891066484). Please test.
> Bug fix: Passing the data name when copying data frames

- instat/sdgOneVarCompareModels.vb
fixes issue #6697 
@africanmathsinitiative/developers , this is ready for review
@Patowhiz , this is ready for review
The constructor was wrongly written. I have fixed it by changing it from `sdgOneVarCompareModels` to `sdgOneVarCompareModels_Load`
The sdgOneVarCompareModels Design now loads with no issue.
> Ensure that One variable Compare Models subdialog opens correctly

- instat/frmMain.Designer.vb
- instat/frmMain.resx
- instat/frmMain.vb
I have renamed the Specific menu items as suggested and moved the Mosaic up. @rdstern you can have a look at it. Though, I have not added the tooltips, as they are not yet specified.
> Renamed specific options in the Describe menu

- instat/sdgOneVarFitModDisplay.vb
Fixes Issue #6591 
@africanmathsinitiative/developers , This is ready for review
@lloyddewit , This is ready for review. 
I have added  handle.load base on sdgOneVarFitModDisplay. This will ensure that the subdialog design loads in vb with no issue
> Ensure that the Display Options Sub Dialog in One Variable fit Model Dialog opens correctly

- instat/ucrGeom.vb
This allows the label aesthetic in geom_treemap_text function to allow any type of variable instead of factors only as suggested by @rdstern in point(g) of PR #6764
> Allowed variables of any type as labels into the Plot subdialog geom_treemap_text

- instat/dlgOneWayFrequencies.Designer.vb
- instat/dlgOneWayFrequencies.resx
- instat/dlgOneWayFrequencies.vb
- instat/sdgOneWayFrequencies.Designer.vb
- instat/sdgOneWayFrequencies.resx
- instat/sdgOneWayFrequencies.vb
Partly fixes Issue #6670 
@africanmathsinitiative/developers , this is ready for review
@rdstern , @Patowhiz This is ready for review
- I have added the `min.frq` parameter in the `frq` function for the One Way Frequency Dialog. Additionally, I have added the `show.na` parameter in the same function. 
- A function `as.data.frame` has been added converting the result into a data frame
- A save control has been added, to save the resulting data frame for the table and Both options in the dialog.
> Improved One Way Frequencies dialog, added table save and extra parameters for 'frq' function

- instat/sdgOneWayFrequencies.vb
Changes as of PR #6730 requested after merging 
@shadrackkibet , I have corrected the typo error `Variabless` to `Variables`.  It is ready for review now. 
@lloyddewit , Kindly review it too.
> Correcting typo in One Way Frequency Table Dialog

- instat/static/InstatObject/R/Backend_Components/calculations.R
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
fixes #6891
This bug wasn't due to the recent changes to the grid but to the recent additions to the filter objects. It's a very good bug to find and a good reminder of the importance of backwards compatibility so we can support users with older `data_book` files.
@shadrackkibet This was caused by recent additions to the parameters for filters i.e. `"inner_not"` and `"outer_not"`. Because these parameters don't exist in filter objects in `data_book`s saved a long time ago, it gives an error when trying to access these parameters. I hadn't thought too much about this before. I should have put these structures in place at the beginner so it would be clear what to do when making changes.
It's easy to resolve. I have created …
> Fixed bug loading older files with filters applied

- instat/ucrColumnMetadata.Designer.vb
- instat/ucrColumnMetadata.vb
- instat/ucrDataFrameMetadata.vb
fixes #6895
ColumnMetaData was causing issues as if there isn't a worksheet then the reoGrid cannot be visible. Also updated order of remove to create to make sure current worksheet is updated.
> updated columnMetaData to display even if no databook open

- instat/dlgClimaticNCMPCountRecords.Designer.vb
- instat/dlgClimaticNCMPIndices.Designer.vb
- instat/dlgClimaticNCMPSummaryFile.Designer.vb
- instat/dlgClimaticNCMPVariogram.Designer.vb
- instat/dlgHomogenization.vb
- instat/dlgInfillMissingValues.vb
- instat/dlgRestrict.resx
- instat/static/InstatObject/R/stand_alone_functions.R
- Making the save control wider on various dialogs where the text box was cut off
- Improved spacing in Homogenization dialog code
- Added required blank lines in writing lines for `export_wwr()`
- Changed default save column name in infill missing values to follow naming convention
@africanmathsinitiative/developers This is ready for review. These are very small, can someone check these code changes are sensible?
> various small bugs, design issues & naming conventions

- instat/ucrDataView.vb
This works as when the original dataframes are added the main form selects the first worksheet therefore this can be added without affecting the initial load
> Updated grid so any new dataframes added become current tab

- instat/frmMain.vb
This will fix the issue simply however there may be an issue in the future as it swaps labels on buttons and if we were using tool tips this could get lost.
@dannyparsons do I need to set up translations on these buttons if I'm swapping labels?
> fixes #6787 - simple fix that swaps grids and labels on buttons

- instat/dlgRecodeFactor.resx
- instat/dlgRecodeFactor.vb
fixes #6898
I've resolved this by changing the Recode Factor dialog back to using `plyr::recode()`. This function works in a different way allowing the duplicate values.
@N-thony @rdstern Can you confirm this resolves the issue?
I also updated some text on the dialog. We should use `NA` in capitals for the missing value code. We should also not use `_` for text on dialogs, it should always be readable normal text e.g. `Add NA` instead of `add_na`.
> Fixed bug recoding factor levels

- instat/dlgLabelsLevels.vb
Partially fixes #6900 
This essentially concerns the first part of issue #6900 on the way the application was throwing due to the fact that the deleted dataset from the Data View after showing the Levels/Labels dialogue was still present when trying to show the Levels/Labels of another data set.
@rdstern @africanmathsinitiative/developers this is ready for review. Thanks.
> Fixed bug when trying to show Levels/Labels Dialogue

- instat/Model/DataFrame/clsColumnMetaData.vb
- instat/ucrColumnMetadata.vb
- instat/ucrDataView.vb
Set up that anytime a worksheet is updated it is selected. When adding worksheets this will override any selection with the first worksheet added
> Updated tab selection when updating databook

- instat/clsRLink.vb
- instat/dlgExtremeEvents.vb
- instat/dlgFromLibrary.vb
- instat/frmCommand.vb
- instat/frmConvertToNumeric.vb
- instat/frmEditor.vb
- instat/frmLog.vb
- instat/frmMetaData.vb
- instat/frmOutputWindow.vb
- instat/frmScript.vb
- instat/frmVariables.vb
- instat/ucrButtons.vb
Updated all form.Hide to form.Close
@shadrackkibet can you check this doesn't break any functionality. I have checked areas that I've changed and the forms close and reload correctly however I'm not confident on all functionality
> Replace form.Hide with from.Close in order to work on Linux

- installer/inno_install_script_32bit.iss
- installer/inno_install_script_64bit.iss
- instat/frmConvertToNumeric.vb
- instat/ucrDataView.vb
@ChrisMarsh82 I noticed an issue with the new closing on `frmConvertToNumeric`. This is because the `DialogResult` property seems to be lost when the form is closed. I've changed it so that the form is closed by `ucrDataView` instead. This seems to work ok. Can you check you're happy with this?
(I also included updates to the installation scripts here, but that's unrelated to this change)
> fixed convert to numeric form closing issue and updated install scripts

- instat/Translations.vb
- instat/instat.vbproj
- instat/translations/translateIgnore.txt
Fixes #6581 
Fixes #6532 
Partially fixes #3721 
Added mechanism to ignore specified WinForm controls when the application or dialog is translated into a different language.
This will prevent the text from being translated. For example, if a control's text represents the name of an R parameter, then this text should not be translated.
@rdstern , @N-thony ,  Please could you review 'translateIgnore.txt' to make sure that the proposed approach is OK, and adequately explained. Updating the database from this file currently requires manual steps, but I'll automate this (maybe in a separate PR).
@rdstern Please could you also test that this fixes issue #6581 , thanks
@rachelkg You are also welcome to review if you're interested (optional)
@dannyparsons We discussed this before and you …
> Added mechanism to ignore specified UI controls when translating to a different language (e.g. to French)

- instat/dlgRemoveUnusedLevels.Designer.vb
@africanmathsinitiative/developers @shadrackkibet 
this partially fixes issue #7023 
>  Made the Message text box non-editable on the Remove Unused Levels dialog

- instat/ucrTry.Designer.vb
@africanmathsinitiative/developers @shadrackkibet 
This partly fixes #7023 
Can you look at this change.
> Made the Try text box non-editable on the Calculator dialog

- instat/translations/translateIgnore.txt
Fixes issues described in PR #7035.
Changes to database:
@rdstern @shadrackkibet There is nothing you can really test or review here. Please can you approve so that we can merge quickly and avoid potential merge conflicts with the database? Thanks
> In the 'Evapotranspiration' dialog, set the 'Penman-Monteith' and 'Hargreaves-Samani' buttons to DoNotTranslate

- instat/dlgImportDataset.vb
- instat/frmMain.vb
- instat/instat.vbproj
- instat/ucrScript.vb
Fixes #6984 
This PR adds the Niger script file to the Climatic > Niger folder and also the facility to open an R script to the Script Window from Open From Library.
> In Open From Library dialog, open R script file and write to the Script Window, also added Niger script file

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
On PR #7107 @rdstern commented
"This is that the order of the variables in the table is not the same as the order in the receiver. I think it is alphabetical in the table. I can live with this temporarily if it is difficult to fix?"
This should fix that problem in the R code
> Variables in summary tables to be in order they are put in the receiver

- instat/dlgClimaticBoxPlot.vb
> Resolved 'argument "x" is missing, with no default' error in Climatic>Boxplot dialog 

- instat/UserControl/ucrOutputPage.vb
- instat/UserControl/ucrOutputPages.vb
Fixes #7000
@dannyparsons I have here implemented the Ctrl+C as you suggested in the corresponding issue with the Output Window.
@ChrisMarsh82 I have additionally fixed the bug when copying text from `Output Window` to `Script Window` by Clicking on `Copy Tab` as I have explained in the issue. The change is made in `CopySelectedElementsToClipboard()`
> Implemented the Ctrl+C on the new Output Window

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
Fixes issue found in #7107 
@rdstern found an issue with the margins in the `summary_calculations` function when the summary itself contained more than one `_` (for example, `summary_count_non_missing`, but not `summary_sum`).
> And then it gets more "interesting" when I add the margins! This might be a @lilyclements question? ![image](https://user-images.githubusercontent.com/11226469/150835729-04add97c-b030-4785-b62d-dbf3d85b3046.png)
This problem was occurring because we have the columns saved as `summary-type _ variable-name` (e.g. `sum_field`, `count_non_missing_field`). This PR fixes the issue found.
@rdstern @africanmathsinitiative/developers this is ready to review
> Fixing a bug with the margins in the summary table function 

- instat/UserControl/ucrOutputPage.vb
- instat/frmMain.vb
> Ensure output window always scrolls to bottom when new output is added

- instat/dlgSelect.vb
- instat/dlgSelectColumns.Designer.vb
- instat/dlgSelectColumns.vb
- instat/sdgDataOptions.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/labels_and_defaults.R
- instat/static/InstatObject/R/stand_alone_functions.R
fixes #7190
@rdstern  this PR add more options to select columns. I have enabled the following options under select.
The remaining bit is an option to select by the number of factor levels.
I used the following dataset to test it.
[dfid2_ug_210803.zip](https://github.com/africanmathsinitiative/R-Instat/files/8051556/dfid2_ug_210803.zip)
> Added options to select columns by variable type, labelled variables, empty variables and NA variables

- instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
- instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
- instat/ucrDataView.vb
fixes issue #7246 
Delete cells seems to not work on the Linux grid 
i have enabled the delete function for the Linux grid 
@N-thony can you test this
> Ensured that Delete Cells works correctly for Linux grids

- instat/dlgDeleteObjects.Designer.vb
- instat/dlgDeleteObjects.vb
- instat/dlgRenameObjects.Designer.vb
- instat/dlgRenameObjects.vb
- instat/static/InstatObject/R/data_object_R6.R
fixes #can't trace the issue at the moment but it should be somewhere. Apologies, I will try to find it. @rdstern please help.
This PR adds options for renaming and deleting column selections into **Rename Objects** and **Delete Objects** dialogs. To test it;
- Create column selections using **Prepare> Data frame> Column selection**
- Rename column selection using **Prepare> R Objects> Rename Objects**
- Delete column selection using  **Prepare> R Objects>Delete Objects**
**Note**: You have to select **Type** - "Column selections" while using these dialogs.
> Added options for renaming and deleting column selections

- instat/dlgFromLibrary.Designer.vb
- instat/dlgFromLibrary.vb
- instat/dlgViewLabelsAndLevels.Designer.vb
- instat/frmMain.Designer.vb
Fixes (partially) #7073 
@lloyddewit @shadrackkibet this just update the database by renaming the menu and dialogue text to `View/Delete Labels` for View Label dialogue.
> Renamed Dialogue controls texts in the database

- instat/dlgCalculateTreatmentDifferences.Designer.vb
- instat/dlgClimaticDataEntry.Designer.vb
- instat/dlgCompareTreatmentLines.Designer.vb
- instat/dlgSetupForDataEntry.Designer.vb
- instat/ucrInputFactorLevels.Designer.vb
Fixes #7269 
@rdstern  I had a quick discussion on this with @ChrisMarsh82 and then found that the problem was more general mainly under the following dialogues and ucrInputFacotrLevels itself:
- dlgCalculateTreatementDifferences
- dlgClimaticDataEntry
- dlgCalculateTreatementLines
- dlgSetupForDataEntry
- ucrInputFacotrLevels 
To fix this, we just set the `AutoSize property to False` and also adjusted the `Size` of ucrInputFacotrLevels and it corresponds to the above dialogues.
Please take a look. Thanks.
> Fixed bug on the factor levels control being hidden in some dialogs

- instat/dlgSelect.Designer.vb
- instat/dlgSelect.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
fixes #
This PR adds an option to copy column selection as a separate data frame.
> Added option in Column Selection dialog to copy column selection into a separate data frame

- instat/Interface/IColumnMetaDataGrid.vb
- instat/Interface/IDataframeMetaDataGrid.vb
- instat/UserControls/DataGrid/Linux/ucrColumnMetadataLinuxGrid.vb
- instat/UserControls/DataGrid/Linux/ucrDataframeMetadataLinuxGrid.vb
- instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
- instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
- instat/dlgLabelsLevels.vb
- instat/dlgSelect.vb
- instat/dlgSelectColumns.vb
- instat/dlgViewLabelsAndLevels.Designer.vb
- instat/dlgViewLabelsAndLevels.vb
- instat/sdgDataOptions.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/ucrColumnMetadata.vb
- instat/ucrSelectorByDataFrameAddRemove.vb
Fixes (partially) #7073 
This is still a work in progress.
@dannyparsons I need your help here. Could we have a call? Thanks
> Added delete of value labels to the Prepare > Column: Factor > View Levels/Labels dialogue using delete key in column metadata

- instat/dlgFactorDataFrame.Designer.vb
- instat/dlgFactorDataFrame.vb
- instat/static/InstatObject/R/instat_object_R6.R
This fixes #7229
Hello @rdstern and @shadrackkibet, The dialog now works. The replace checkbox is checked by default as well as the frequencies checkbox. 
When the Contrasts checkbox is unchecked, we have the levels and frequencies only, when checked we have the contrasts included. The same thing happens to the Frequencies checkbox, when its unchecked we don't have the frequencies in the output displayed.
> Added an option to include frequencies into the Prepare>Column: Factor> Factor Data Frame Dialogue

- instat/dlgClimaticCheckDataTemperature.Designer.vb
- instat/dlgClimaticCheckDataTemperature.vb
Fixes #7025 
@rdstern @dannyparsons @shadrackkibet ,  this PR makes the following changes ;
- Changing the nud to textboxes in Acceptable Range
- produced column names to have standard name such as _e1 and _e2 (for element 1 and element 2)
- Removing QC column which was being created at the end
- Removing  "oC" label from Acceptable Range and Jump and Changing "Same" label to "Days:"
@N-thony  made the following changes in database #7243 
changing "to" to [box] To: [box] in Acceptable Range
Adding : to "Coef:" in Outlier.
> Naming and adding textboxes into Qc temperature dialog

- instat/Model/DataFrame/clsDataFrameFilter.vb
- instat/ucrDataView.vb
Fixes #7277 
I have added the info concerning the column selection when it is applied to DataView, I also adjusted the size of the info when the application is minimized or maximized.
> Updated the data view info when selection is applied

- instat/dlgThreeVariablePivotTable.Designer.vb
- instat/dlgThreeVariablePivotTable.vb
Replaces PR#7315 and fixes issues raised in PR #6634 
@rdstern currently the Pivot Table improvements are under the Describe>Three Variable menu. Moving it under the Describe>Two Variable menu bring an error since the file has been manipulated in another PR.
I suggest have this reviewed and possibly merged then I will remove the dialogue under the Describe >Three Variable menu and Move it to the Describe >Two Variable menu
> Improved the Three Variable Pivot Table dialog

- instat/dlgPICSARainfall.vb
Fixes #7332
@rdstern the result produced when changing the facet option by row or column was still the same due to the missing of `dplyr::group_by(station)` in the R code. I have added that now, please test and confirm if everything is fine. Thanks.
> Fixed the bug on the result produced by PICSA when the Facets is by row or column

- instat/dlgConversions.vb
- instat/dlgRownamesOrNumbers.Designer.vb
- instat/dlgRownamesOrNumbers.vb
This fixes #7323 
@rdstern and @shadrackkibet, I have added a checkbox to Add Keys to the New column created by the first option (Copy row names into Column). The checkbox is checked by default. I have been using the mtcars dataset to test the dialogue.
I have also fixed some other bug issues on the dialog. You can have a look at it.
> Added an option to Add Key for the new column in Prepare>Data Frame>Row Numbers/Names dialog

- instat/dlgDuplicates.Designer.vb
- instat/dlgDuplicates.vb
- instat/frmMain.Designer.vb
- instat/frmMain.vb
Fixes #7259 
@rdstern @shadrackkibet, in this PR which affects Two/Three variables sub-menu;
Renames Frequencies to Two-way Frequencies and also adds Three-way Frequencies. 
Renames pivot table to Pivot-Table (Frequencies) and also adds Pivot-Table (Summaries)
Also, here is updated database screenshot.
> Renaming items and adding Three-Way Frequencies and Pivot-table(summaries) dialogs in Two/Three Variables sub-menu.

- instat/dlgMergeAdditionalData.vb
Fixes #7382
@rdstern I have fixed the bug as described in the corresponding issue, this problem is fixed by swapping the `x` and `y` parameters values in the `left_join function`. Please take a look. Thanks.
> Bug fixed on Add (Merge) Columns when merging with different datasets length

- instat/Model/DataFrame/clsDataBook.vb
- instat/Model/DataFrame/clsDataFrame.vb
- instat/Model/DataFrame/clsDataFramePage.vb
- instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
- instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
- instat/ucrDataView.vb
Fixes #7374
This PR is meant to prevent R-Instat from breaking if there is a problem with retrieving data frame form R. This prevention was already there in the old version of R-Instat.
Changes include;
1. Refactoring code
2. Adding a warning that was there in the old version. 
To test it, you can  use the data file in the issue.
> If error thrown when retrieving data frames from R, then handle error and display user message

- instat/dlgContrasts.vb
- instat/dlgRegularSequence.designer.vb
- instat/dlgRegularSequence.vb
This fixes #7388 
@rdstern, I have added a checkbox that when checked, we have the preview. I created a data frame of 200,000 rows and it worked well. Using 2,000,000 rows, it is well until you check the checkbox. So, I feel for a data frame with about 2,000,000 rows, it's safe having the regular sequence without checking for the preview at the moment. 
But since some people may find the preview useful, maybe we could show the preview for the first 1000 rows. What do you think?
> Improves the use of long datasets with the Regular sequence dialog. 

- instat/ucrDistributionsWithParameters.vb
Fixes #7406 
@rdstern this PR makes ucrInputParameter1 to be editable for some distributions.
> Ensure that parameters can be edited in Random Samples dialog

- instat/dlgContrasts.vb
This fixes (partially) #7392 
@rdstern, I limited the precision to 3 decimal places. I still used the survey data and set the contrast to polynomials, then the user-defined grid gives the available contrasts with a maximum of 3 decimal places.
> Minor improvements to the Contrasts dialog.

- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
Fixes (partially) #7351 
@rdstern @lilyclements I have updated the metadata to be able to drop the key columns when there is no keys.
These changes concern items a) b) and c), please take a look.
> Made the change to the metadata to update the Data Frame Metadata grid

- instat/dlgMerge.vb
> Minor bug fixed in the Merge Dialogue

- instat/Model/DataFrame/clsDataFramePage.vb
- instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
- instat/dlgColourbyProperty.Designer.vb
- instat/dlgColourbyProperty.vb
- instat/dlgMergeAdditionalData.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrDataView.vb
Fixes #7232
@rdstern I have fixed the bug on not setting the colour to the dataset in the `Data View`, in addition while testing I fixed one small bug I found in the `Merge Additional Dialogue`. I also realised in version `0.7.2` that with dataset you shared in Skype, the merge dialogue seems to not apply the colour though the second or first dataframe has colour applied but with this version, it seems to keep the colour if applied from one of the dataset in the merged dataset. Please could test on your side and see if I'm right? Thanks.
> Fixed bug when colour is applied in the dataset from Data View window

- instat/dlgMergeAdditionalData.vb
Fixes #7473
@rdstern I have fixed the bug that occurs when the key columns have two different name when trying to merge. For the Joining columns option sub dialogue as you suggested that the selectors should reflect the selectors in the main dialogue, this can be done in a sepearate PR.
> In Prepare > Add (Merge) Columns dialog, ensure that data frames with different key column names can still be merged

- instat/dlgClimaticStationMaps.Designer.vb
- instat/dlgClimaticStationMaps.resx
- instat/dlgClimaticStationMaps.vb
Fixes #7472
@rdstern @lilyclements could you test this?
> Combined the three plot options buttons in Climatic Maps

- instat/static/InstatObject/R/Backend_Components/calculations.R
Fixes #7488 
@lilyclements thanks for your support, @rdstern I had a quick look of it then requested help from Lily, this seems to be fixed now, please take a look.
@derekagorhom @VimbayiChimonyo could you also test?
@dannyparsons could you review this? Thanks.
> Fixed bug in the Start of Rains Dialog

- instat/dlgClimaticStationMaps.Designer.vb
- instat/dlgClimaticStationMaps.vb
Fixes #7494 
@rdstern @africanmathsinitiative/developers This is ready for review.
> Added missing Geoms to the plot options in the Climatic>Mapping>Map sub dialog

- instat/dlgName.vb
fixes #7422 , minor bug in Prepare>DataFrame>Rename Column Dialogue 
Enabling the `ok button` for the multiple option 
@africanmathsinitiative/developers  this PR is ready for review
> Fixed minor bug in Prepare>Data Frame>Rename Columns dialog

- instat/frmMain.vb
- instat/ucrDataView.vb
Fixes #7477 
@rdstern I have made the improvement to the column meta data to change to the current data frame when the current data frame has changed from data view. Please have a look. Thanks
@derekagorhom please have a look.
> Ensured that Column Metadata window opens with the default selected dataset in the Data View

- instat/mdlCoreControl.vb
- instat/ucrDataFrame.vb
Fixes #7489.
@africanmathsinitiative/developers @Wycklife this is ready for review.
@lloyddewit,
I'm not sure if we should generally allow committing changes like the one I've made `ucrDataFrame`. I did it here for @Wycklife to test, I can remove it if need be.
I think developers should be calling the `IsInDesignMode`  to make design changes then just remove or comment it out after that. 
I also understand there is no any significant performance difference in leaving such code. So I'm happy with any suggestion.
Thanks.
> Adds a data book null check, in the data frame selector, to prevent design view error

- instat/dlgCorrelation.vb
- instat/frmMain.vb
Fixes #7452 
It replaces PR #7457  due to conflicting files
@rdstern @N-thony @lloyddewit this PR makes default to be Multiple variables in Multivariate sub-menu and Two Variables in 2/3 variables sub-menu
I have also updated the database for the labels changed
> Changed the defaults of Correlation dialog to be '2/3 Variables' or 'Multivariate' depending on menu option used to open dialog

- instat/Interface/IGrid.vb
- instat/Model/DataFrame/clsDataBook.vb
- instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
- instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
- instat/dlgReorderDataFrame.Designer.vb
- instat/dlgReorderDataFrame.vb
- instat/frmMain.vb
- instat/static/InstatObject/R/instat_object_R6.R
- instat/ucrColumnMetadata.Designer.vb
- instat/ucrColumnMetadata.vb
- instat/ucrDataView.Designer.vb
- instat/ucrDataView.vb
- instat/ucrReorder.vb
Fixes (partially) #4557 
@shadrackkibet @lilyclements I checked the R code, then I found that on line 128, we were trying to check the obj class type as `data_object` i.e ` if(!is.list(new_data_objects) || (length(new_data_objects) > 0 && !all("data_object" %in% sapply(new_data_objects, class))))` to `if(!is.list(new_data_objects) || (length(new_data_objects) > 0 && !all("DataSheet" %in% sapply(new_data_objects, class))))`, please have a look, if everything is okay, I will then check the reodering in the front end.
> Improved reordering of data frame tabs in Data View

- instat/dlgPICSARainfall.Designer.vb
- instat/dlgPICSARainfall.vb
Fixes (partially) #7534
This PR fixes the bugs recently found on the PICSA rainfall graph dialogue. 
@N-thony @Vitalis95 can you test. 
There seems to be an issue with the dialogue. 
1. In the Single variable; when using either Line or Point Options the user has to automatically select the variable it wants to use as the Y variable. (I tried correcting that but it created more problems that solutions). 
to show proof: 
When using the dialogue without Line/Point options:
ghana <- data_book$get_data_frame(data_name="ghana")
last_graph <- ggplot2::ggplot(data=ghana,` mapping=ggplot2::aes(y=as.numeric(x=rainfall), x=month_abbr)) `+....
When using the Dialogue with Line/Point options:
ghana <- data_book$get_data_frame(data_name="ghana")
last_graph <- ggplot2::ggplot(data=ghana, …
> Fixed bugs in PICSA Rainfall Dialogue 

- instat/static/InstatObject/R/Backend_Components/calculations.R
As @rdstern pointed out in #7465:
> I then tried with data-time variables. I used the mydata file from openair in the library. When you ask for sum there, (default with customised) it gives: ![image](https://user-images.githubusercontent.com/11226469/177487588-3229fd68-f41a-4d0b-8193-44d7cbacb617.png)
This PR fixes this problem.
@rdstern @africanmathsinitiative/developers this is ready to review
> Ensured that date-type variables return `NA` if `sum` is performed in a calculation

- instat/clsRLink.vb
Fixes #7609 
In the script window, R statements can be split across multiple lines for readability. When R-Instat parses the script, it parses line by line, and only executes the text when it judges that the R statement is complete.
It uses a set of heuristics to judge if the statement is complete (e.g. unclosed quotes, line ends in ',' etc.). This PR adds a check to ensure there that all open brackets have been closed. See issue #7609 for an example.
Note: The set of heuristics is quite simple but should cover most real-world examples. The RScript library parsing is much more sophisticated. However, it doesn't currently have a public function to check if the R script represents an incomplete R statement.
I suggest to stay with the simpler heuristics for now. If we find that we continue …
> Ensured that R script with unclosed brackets treated as incomplete R statement

- instat/dlgPICSARainfall.vb
- instat/sdgPICSARainfallGraph.vb
Fixes #7607 
@rdstern @N-thony @lloyddewit  this PR fixes the issue when you set Y-axis  at any point  then it doesn't unset itself when dialogue is used repeatedly
> Ensured that Y-axis settings are persistent when closing/re-opening PICSA Rainfall dialog

- instat/static/InstatObject/R/install_packages.R
fixes #7626
- Removed signmedian.test R package because it has been [removed ](https://cran.r-project.org/web/packages/signmedian.test/index.html)from CRAN and we do not use it anywhere.
> Removed signmedian.test R package

- instat/dlgGeneralForGraphics.vb
Fixes #5349 
@rdstern, the issue here was in the general graphics dialog and not the Plot options sub dialog. So, I traced the error and fixed it. Kindly test.
The condition is that when the receivers are empty, the X/Y axes are discrete, but when the receivers are filled, it changes to Continuous and maintains their state.
> Fixed the graphics axes issue in the General Graphics dialog.

- instat/dlgHistogram.vb
Fixes #7672 
@rdstern @N-thony @lloyddewit , this PR sets  `counts` as default value  in the `Statistiques` input control
> Set 'counts' as default 'Stats' value in Histogram Plot dialog

- instat/sdgPICSARainfallGraph.vb
Fixes (partially) #7668 
@N-thony @rdstern @lloyddewit this PR makes PICSA graphs sub-dialog titles be consistent with the PICSA graphs dialogs
@lloyddewit, please could change the id_text in the database for `sdgPICSARainfallGraph` to `ReplaceWithDynamicTranslation` before they test it . It's causing merge conflicts from my end if I do it.
> Made PICSA Graphs sub-dialogs' titles consistent with PICSA Graphs dialogs

- instat/frmOutputWindow.vb
- instat/ucrSelectorByDataFrameAddRemove.Designer.vb
R-Instat displayed the following build warnings:
```
Rebuild started...
1>------ Rebuild All started: Project: instat, Configuration: Debug Any CPU ------
1>C:\Users\steph\source\repos\lloyddewit\R-Instat\instat\ucrSelectorByDataFrameAddRemove.Designer.vb(135,23): warning BC40004: WithEvents variable 'ToolStripSeparator1' conflicts with WithEvents variable 'ToolStripSeparator1' in the base class 'ucrSelector' and should be declared 'Shadows'.
1>C:\Users\steph\source\repos\lloyddewit\R-Instat\instat\frmOutputWindow.vb(83,13): warning BC42024: Unused local variable: 'prphTemp'.
1>C:\Users\steph\source\repos\lloyddewit\R-Instat\instat\frmOutputWindow.vb(84,13): warning BC42024: Unused local variable: 'conImage'.
1>  instat -> C:\Users\steph\source\repos\lloyddewit\R-Instat\instat\bin\Debug\in …
```
> Removed build warnings

- instat/clsRegressionDefaults.vb
- instat/dlgFitModel.vb
- instat/ucrDistributions.vb
Fixes #6345  
@rdstern @lilyclements @N-thony , we have added (@Tula1 and I) `glm.nb`, `polr`  distributions from `MASS` package and `multinom` from `nnet` package.
For the factor response variables, the dialog runs `car::Anova`  to the saved model (type-II analysis-of-variance tables for model objects)
> Added more distributions to General Fit Model dialog

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
@africanmathsinitiative/developers @rdstern this is ready to review.
This PR adds a parameter to include counts with percentages in summary function called `include_counts_with_percentage` as discussed in #7621.
This is default `FALSE`, but when `TRUE`, includes the counts when percentages are chosen.
E.g.
```
survey <- data_book$get_data_frame(data_name="survey")
multiple_receiver_cols <- c("village", "variety")
list_of_tables  <- survey %>% purrr::map(.x=multiple_receiver_cols,
.f= ~ dplyr::select(.data=data_book$summary_table(data_name="survey", percentage_type="factors", perc_total_factors="fertgrp",
include_counts_with_percentage = TRUE,
summaries=c("summary_count"), include_margins = TRUE, factors=c("fertgrp", .x)), c(1, by_var=2, 3, 4))) %>% purrr::map(.x=., .f= ~ …
```
> Added counts with percentages option to summary function in Describe > Specific Tables/Graphs > Summary Tables dialog

- instat/ucrScript.Designer.vb
- instat/ucrScript.resx
- instat/ucrScript.vb
**Brackets**
If the user types an open bracket (e.g. `[`), then R-Instat automaticaly inserts a closing bracket.
Also, if the user moves the cursor, and the caret is then next to a bracket, then it highlights the paired open/close bracket. 
If it cannot find a paired bracket, then it displays the bracket next to the caret in red (to indicate an error).
For indented brackets, it shows a vertical line at different indentation levels:
**Quotes**
If the user types a quote character (e.g. `"`), then R-Instat automaticaly inserts a closing quote character.
It avoids inserting closing quotes in situations such as `don't`. 
It also ensures that the caret does not remain in the center upon multiple quote insertions. For example ("|" is cursor position; '=&gt;' is output):
- insert ' => '|' 
- …
> In the Script window, improved the usability of brackets and quotes

- instat/translations/en/r_instat_not_menus.json
- instat/ucrTry.vb
Fixes #7774.
Specifically, this fixes the part 'e' of issue #7774 (see screenshot below). The rest of this issue is covered by issue #3721, therefore it's OK for this PR to auttomatically close #7774 when this PR is merged.
This PR should also fix this issue for all other dialogs that use the `ucrTry` control.
@N-thony Please could you peer review? The database changes are shown below.
@rdstern Please could you test?
Thanks!
> Ensured that the 'Try' message in the Calculator, and some other diogs, is correctly translated (e.g. to/from French)

- instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
- instat/ucrColumnMetadata.vb
Fixes (partially) #7643 
@lloyddewit this PR replaces PR #7918
@rdstern please have a look. 
This set the color to red of the selected columns in the Column Metadata grid
> In Column Metadata grid, display columns selected in DataView in red

- instat/Model/DataFrame/clsDataBook.vb
- instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/ucrDataFrameMetadata.vb
Fixes (partially) #7339
@rdstern this fixes item 4) in the corresponding issue, please have a look. Thanks.
it changes the colors of `Columns` and `Rows` of the datasets where the filter is applied
Perhaps we can move `Rows` after/before `Columns`?
> In Data Frame Metadata grid, displays filtered columns and row in red

- instat/ucrScript.vb
Fixes #7931 
If I tried to paste an image (e.g. jpeg) into the script window, it would try to bring up the error message that this cannot be performed.
However, instead of bringing up the error message, it would crash.
This fixes that bug
> Fixed error message in Script window

- instat/dlgOptions.Designer.vb
Fixes Partly #7749 
@lloyddewit , @N-thony , this PR adds Scale/Distance dialog and Random split dialog to the database
> Added Scale/Distance & Random Split dialogs to the database

- instat/dlgThreeVariableFrequencies.vb
Fixes #7741
@rdstern please check if the result is now correct? Thanks
Probably you could play around with the dialogue and see if everything expected is correct?
> Ensured correct result from 3-way frequencies dialog

- instat/dlgImportDataset.vb
This Fixes #7714 
@rdstern, This is in progress.
So far the code can import a JSON file with equal lengths of lists. Am working towards being able to import JSON files with unequal lengths of lists.
I tried importing a simple txt file and the current options managed to import it to R-Instat, though I haven't tried with a bigger txt file!
>  In Import dialog, read a JSON file with equal lengths of lists

- instat/static/InstatObject/R/stand_alone_functions.R
- instat/ucrColumnMetadata.vb
Fixes (partially) #7812 
@rdstern have a look of what we have now, when I use your example by creating a big number with `2^x1-1` in the corresponding issue I get this in the grid, with `Scientific = FALSE`
So, here when we set `Scientific = TRUE` we get the `e-notation` where the character are more than 9, you can see from row 30
> Ensured big numbers can be displayed in Data View grid

- instat/dlgCluster.Designer.vb
@N-thony , @lloyddewit - I have added missing strings mentioned in  issue #7749   to the database.
> Added missing strings in Scale/Distances dialog to the database

- instat/dlgClimaticSummary.vb
Fixes #7670 
@N-thony , this PR is ready for preview
> Fixed bug in Climatic Summary dialog

- instat/dlgNewDataFrame.Designer.vb
- instat/dlgNewDataFrame.vb
Fixes #7957 
@berylwaswa can you test this? Thanks.
> Enhanced New Dataframe dialog

- instat/ucrCalculator.Designer.vb
- instat/ucrCalculator.vb
fixes #7953
@rdstern , @N-thony this PR is ready for review
> Added random sampling to Probability keyboard in Calculator dialog

- .github/workflows/CreateInstaller.yml
- instat/Interface/IGrid.vb
- instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
- instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
- instat/dlgReorderDataFrame.vb
- instat/frmMain.vb
- instat/ucrColumnMetadata.vb
- instat/ucrDataView.vb
Fixes #7550
@rdstern as discussed I have improved the code and also fixed the small bug in the `Data View` to maintain the selected sheet even though reordering is applied. Please, take a look. Thanks.
> Ensured that the selected sheet in the Data View is maintained after reordering

- instat/dlgRatingScales.vb
fixes partly #8104
@Patowhiz , @lloyddewit , @N-thony 
> Ensured Rating Data dialog output correct

- instat/dlgOneWayFrequencies.Designer.vb
- instat/dlgOneWayFrequencies.vb
Fixes partially #8104 
@rdstern, @Patowhiz and @lloyddewit 
I have implemented the new output system in this dialog.
1. I have disabled the` Both option` since the new output system does not support producing two objects simultaneously. From the discussion with @Patowhiz, it's so easy for a user to go back and produce the other object when needed.
2. The dialog uses only one save control now.
3. The panel that initially controlled save as text(viewer) or HTML (browser) now controls save as a table and save as a data frame, for the `Table option`.
> Implemented new output system in Describe >One variable >Frequencies dialog

- instat/dlgTwoWayFrequencies.vb
fixes partly #8104 
@lloyddewit , @Patowhiz this PR is ready for review
I added the save control for the `table option` of this dialogue and implemented the `new output system` for both the `graph and table options` of this dialogue.
> Ensured output for Two Way Frequencies dialog is correct

- instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
- instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
- instat/ucrDataView.vb
Updated ReplaceValueInCell to only update the changed cell.
At the moment we still bring back the entire dataframe from R so there is still a delay. This would be a much bigger change and could run into errors. This change should at least half the time taken to refresh
> Changed grid to only update one cell if replace value is done

- instat/UserControls/Webview/Windows/ucrWebViewer.vb
- instat/UserControls/frmMaximiseOutput.vb
- instat/clsFileUrlUtilities.vb
- instat/dlgFromLibrary.vb
- instat/dlgHelpVignettes.vb
- instat/dlgHypothesisTestsCalculator.Designer.vb
- instat/dlgHypothesisTestsCalculator.vb
- instat/dlgModelling.Designer.vb
- instat/dlgModelling.vb
- instat/dlgUseModel.Designer.vb
- instat/dlgUseModel.vb
- instat/instat.vbproj
- instat/static/InstatObject/R/stand_alone_functions.R
- instat/ucrCalculator.vb
@rdstern this is ready for you to test. I made the changes in the FromLibrary, HelpVignettes, HypothesisTestsCalculator, Modelling, UseModel, and Calculator Dialogues. Some dialogue `Help button` is still `Help` the changes will be make in another PR.
@lloyddewit could you have a look of the code?
Thanks
> Display R package help in output window rather than in browser

- instat/dlgNewDataFrame.vb
Fixes #8167 
This fixes the recent bug found when the dialogue fails to create a dataframe with less than 3 columns. 
@ChrisMarsh82 , @rdstern, this PR is ready for review.
> Fixed regression bugs on the New Data Frame dialog

- instat/dlgOneWayFrequencies.Designer.vb
- instat/dlgOneWayFrequencies.vb
- instat/dlgThreeVariableFrequencies.vb
- instat/dlgTwoWayFrequencies.vb
Fixes part(a) of #8163 
I have changed the saved objects from table to summary.
This is ready.
> Save summary, rather than save table in One, Two and Three-way frequency dialogs

- instat/ucrButtons.vb
fixes #8153 fixes #7932
This fixes the issues with If a user clicks the To Script button on the dialogue and the toolbar icon doesn't get its tick - though the View > Script Window is ticked.
@lloyddewit , @N-thony  this PR is ready for review.
> Ensured buttons/options to display Script window show a tick when Script window is open

- .gitignore
I have a Git branch to explore writing control states to Json files (PR #8193). This requires the Newtonsoft JSON NuGet package to be installed. If I don't tell the main branch to ignore this lib, then each time I switch branches I need to uninstall the NuGet package.
> Tell Git to ignore Newtonsoft Json NuGet package

- instat/dlgPICSARainfall.vb
Fixes partially #8213 
Fixes part a) of the issue
@rdstern , @lloyddewit , Made year variable be completed automatically and  wrap as default facet
> Ensured that year fills automatically in PICSA dialogs

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
@anastasia-mbithe @rdstern this should fix the issue you highlighted in #8027 about reordering the summaries if `treat_column_as_factor = FALSE`.
This is ready to review, thank you again for being patient!
> Fixed factor level order for `summary-variable` type in Table Summaries

- instat/dlgClimdexIndices.Designer.vb
fixes #8225 
I changed the text that was displaced - so that the number of indices selected would be in the middle of the message.
This PR is ready for review 
@rdstern , @N-thony  can you test/approve
> Ensured that number of indices selected is in the middle of the message in Climdex Indices dialog

- instat/dlgImportDataset.vb
Fixes partly #8025  
I have increased the preview line option to go from 100 to 1000. 
This works well for `xls` files but it takes a little time for `csv` files but not enough to cause an inconvenience 
@Patowhiz , @N-thony this PR is ready for review. 
Thanks
> Increased the number of preview lines in Import dialog

- instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
@rdstern following our chat on Skype few minutes ago, I made the changes as you have noticed during the workshop when paging sometimes it is giving you blank page. This will always set the scroll bar at the top. You can test it also try with the filter for the rows.
I'm checking about the column if easy will just do it here.
> Reset the Data View scroll bar to the top

- instat/dlgEnter.Designer.vb
- instat/dlgEnter.resx
- instat/dlgEnter.vb
- instat/dlgHypothesisTestsCalculator.Designer.vb
- instat/dlgHypothesisTestsCalculator.resx
- instat/dlgHypothesisTestsCalculator.vb
- instat/dlgModelling.Designer.vb
- instat/dlgModelling.resx
- instat/dlgModelling.vb
- instat/dlgUseModel.Designer.vb
- instat/dlgUseModel.resx
- instat/dlgUseModel.vb
fixes #8160 
replaces #8165 
I have updated this branch with the changes done on PR  #8159  added the `Rhelp dropdown` to the Use `Model keyboard`, `Hypothesis Tests`, `Fit Mode`l and `Prepare > Column: Numeric > Enter dialogue.`
@N-thony , @rdstern this PR is ready for review.
> Improved Rhelp for Model Menu Dialogs

- instat/dlgOneVariableSummarise.vb
Fixes #8136 
@rdstern This is ready for testing
> Improved the R code produced by One Variable > Summarise dialog

- instat/frmMain.Designer.vb
fixes #8246  
Replaces #8250 
I moved the `Graph` icon and down arrow to after the `output window` icon and also increased the width on the drop downs for both the `Graph` icon and `View/Edit last Dialogues` icon
@lloyddewit , @rdstern this PR is ready for review
> Improved layout of Main Menu Toolbar

- instat/dlgClimaticBoxPlot.vb
Fixes partially #8213 
Fixes part h) of the issue
@rdstern , @lloyddewit , Made `tmin `variable be completed automatically and if `tmin` is missing, then `rain `be filled automatically
> Ensured that 'tmin' & 'rain' fill automatically in Climatic Boxplot dialog

- instat/dlgColumnStructures.vb
fixes partially #7232 
I made the checkbox for the colour the default. So it starts with the checkbox ticked and also fixed the problem of the dialogue remembering the variables in each control when the dialogue is re-opened. 
@rdstern  this PR is ready for review. 
Thanks
> Ensured that 'Colour Columns by Structure' check box works correctly in Column Structure dialog

- instat/dlgNewDataFrame.Designer.vb
fixes partly #8151 
I changed the radio button for Empty to New, Then made Lists the second, Then Random, Construct, Commands - in that order and together. 
@rdstern , @lloyddewit this PR is ready for review.
> Renamed first radio button in New Data Frame dialog

- instat/dlgBarAndPieChart.Designer.vb
- instat/dlgBarAndPieChart.vb
Fixes partly #8288 
This Fixes the Item c on the list. 
Item b is being fixed in PR #8293 by @lloyddewit 
Item a will be fixed after PR #8293 is merged
This  PR is ready for review 
@COLIEWO can you test this. 
Thanks
> Design changes in Bar chart

- instat/translations/translateIgnore.txt
Fixes #8275
Fixes #8298
@rdstern 
I was only able to recreate the #8275 error intermittently. I think it's fixed but please test thoroughly.
This PR fixes the above issues by setting all input fields (including combo boxes), in all dialogs, to 'do not translate'. My rationale is that these controls contain values to be used literally in the R code. Does this make sense? Please could you do a sanity check on a few other dialogs with input fields to see if the translations are still as expected.
Thanks for your help
> Ensured that Climatic > Check Data > Display Daily Data dialog works in non-English languages

- instat/ucrGeom.vb
Fixes #8283 
@rdstern This is ready for testing.
> Added a layer parameter for density ridges

- instat/dlgSummaryTables.Designer.vb
- instat/dlgSummaryTables.resx
- instat/dlgSummaryTables.vb
This fixes some of #8248 
@lilyclements and @rdstern This is ready for testing.
> Changed mmtable2() to gt() in Describe < Tables dialog

- instat/frmMain.Designer.vb
@lloyddewit this will add the version number back in. 
Looks like it was removed in this PR https://github.com/africanmathsinitiative/R-Instat/pull/8232
> Add version number back in

- instat/dlgImportDataset.vb
@rdstern When you tested R-Instat 0.7.12 you reported that if the user tries to open the Import Dataset dialog in French, then the dialog does not open and R-Instat hangs. This PR fixes this. Please could you test?
thanks
Notes:
- This PR fixes some regression inadvertently introduced by PR #8319
- This PR does not fix the issue with the apostrophe in the Import Dataset comment field. This will be fixed in a separate PR.
> Ensured that Import Dataset dialog does not hang when opened in French

- instat/dlgBarAndPieChart.Designer.vb
- instat/dlgBarAndPieChart.vb
- instat/sdgPlots.vb
Fixes partly #8288 
@rdstern i was able to fix items d, e, and g.
Item f will be fixed along with the new ones @COLIEWO found recently
> Ensured that Bar Chart dialog opens with the correct settings, and improved formatting

- instat/frmMain.Designer.vb
- instat/frmMain.vb
Fixes partly #4108
This Fixes items A to D except adding the `Show R commands` to the `log/Script` window drop-down. 
I keep getting an error when adding that option to the log/script drop-down so i will fix that one separately. 
@rdstern , @N-thony can you test/review. 
Thanks
> Improved usability of Toolbar

- instat/dlgOneWayFrequencies.vb
fixes issue #8411
@rdstern , this PR is ready for review
> Ensured that stem and leaf fields set correctly when opening One Way Frequencies dialog for first time

- instat/static/InstatObject/R/data_object_R6.R
replaces #8416 
@lloyddewit @rdstern this is ready to review
> Ensured that columns in the Data Grid can be deleted even when there are no key columns

- instat/Model/Output/clsOutputLogger.vb
- instat/UserControl/ucrOutputPage.vb
- instat/UserControl/ucrOutputPages.vb
Fixes partly #8408
This is a temporary solution. It restore previously regressed features in a way that it was previously implemented.
Html outputs will still not be saved.
> Restores 'add to' and 'save' output window features

- instat/static/InstatObject/R/Backend_Components/summary_functions.R
A bug identified by the CIMH group during their workshop is that using `na_type=c("'prop'")` in R-Instat calls a bug. This is because the parameter associated with `na_type` was not being called in with `na_type`. This PR fixes this issue for percentiles.
I am not sure if this issue would occur with other summaries. I have tried for other summaries like `summary_mean` and there is no issue there. 
This issue does not occur for me for the other variables that are altered by the na_type. I have tested and these values are read in.
Script that I was testing the bug fix with
```
setwd(dir="C:/Users/lclem/source/repos/RInstat/instat/static/InstatObject/R")
source(file="Rsetup.R")
data_book <- DataBook$new()
options(dplyr.summarise.inform=FALSE)
options(digits=4) …
```
> Fixed calculating column summaries with a missing-proportion option

- instat/dlgThreeVariablePivotTable.vb
@rdstern, @lloyddewit  base on this comment
>  @MeSophie and @lloyddewit of course I checked something slightly different this time, and found another problem with the new pivot table. I hope it might be easy to fix?
> 
> To see the problem:
> 
> a) open (say) Domoma from the library, or any of the climatic sets you have been using to check yourself.
> b) Then open a second data frame - I used the usual survey.
> c) Then go into your climatic pivot table with the wrong data frame.
> d) Then try to change to the correct data frame. I found it was impossible. It insists on the original data frame. Even going to the correct data frame and pressing Reset does no good. It insists on sticking with the wrong data frame.
in PR #8431
I corrected the bug when trying to change data frame in Pivot …
> Ensured that the Change of the Data Frame Works correctly in the Pivot Table dialog in Climatic Menu 

- instat/translations/translateDynamic.txt
- instat/translations/translateIgnore.txt
Fixes #8440 
@rdstern This is the proposed commit for the R-Instat 0.7.16 release.
Please could you test. If you're happy to approve, then I will merge and build the release (probably Friday morning).
Thanks
> Merged CrowdIn changes from PR #8387 into translations table in database

- instat/ucrScript.Designer.vb
Fixes part a of #8451.
In the script window, I also changed the `Add` button to `New`.
@rdstern Please can you test?
Note:
The problem was caused by incorrect translations for these 2 labels for several languages in the translations database.
The JSON files and CrowdIn translations are all correct so the problem must have been introduced when I imported the JSON files into the database. I added a regression test so that if this happens again, then I should detect it before merging the new database into master.
> Ensured that factor labels in Plot Options subdialog are correct

- instat/dlgCalculator.vb
- instat/sdgSaveColumnPosition.vb
- instat/ucrInputComboBox.vb
- instat/ucrInputTextBox.vb
- instat/ucrSave.vb
- instat/ucrVariablename.vb
Fixes #8434
@rdstern have a look. Thanks.
> Ensured position works correctly in Calculator dialog

- instat/sdgPlots.vb
Fixes #8451 
@rdstern , issue a) is no longer there for the updated master branch , b) the default  None  in the legends is  now restored and part c) of the issue is sorted in PR #8005
> Restored "none"  legend option in plots sub-dialog

- instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/static/InstatObject/R/instat_object_R6.R
- instat/static/InstatObject/R/stand_alone_functions.R
Fixes partially #8443 
Fixes #8475
@rdstern this fixes the bug when wrapping/unwrapping a column to not lose the `meta data` and also correct the display of `2:1` to `2, 1`
> Bug fix when wrapping or unwrapping a list column

- instat/sdgPlots.Designer.vb
- instat/sdgPlots.vb
Fixes #8477 
@rdstern , @N-thony , @lloyddewit , this is ready for review.
> Improved Titles options in Plots subdialog

- instat/ucrReceiverMultiple.vb
Fixes #8409 
This Fix clears previously selected variables in the multiple receiver when the dialog is re-opened. 
@rdstern , @N-thony can you review this 
Thanks
> Reset the Multiple Receiver when re-opening the dialog

- instat/dlgOneVariableSummarise.vb
Fixes #8534 
@rdstern @N-thony , have a look at it
> Ensured that Maximum Factor Levels Shown is not reset when Describe > One Variable Summarise dialog is reopened

- instat/dlgRownamesOrNumbers.vb
fixes #8510
The changes are; 
a) Delete the second set of lines. 
b) To permit the key variable checkbox to be unchecked while still being checked by default.
c) added the function  `all(sapply(rownames(data), is.numeric))`
@N-thony , @rdstern this PR is ready for review
Thanks
> Ensured the Identify Key checkbox works correctly in Row Names or Numbers dialog

- instat/frmMain.vb
- instat/ucrColumnMetadata.vb
- instat/ucrDataFrameMetadata.vb
- instat/ucrScript.vb
When you start R-Instat, there is a layout oddity as shown in the image below. 
This PR fixes the oddity and also comment https://github.com/africanmathsinitiative/R-Instat/pull/8465#pullrequestreview-1588370215 
Layout oddity screenshot
> Ensured logical layout and correct toggling of Script, Metadata, Data and Output windows

- instat/clsRLink.vb
Fixes double imports of data as outlined in issue #8509.
This PR also fixes optimises running of commands through the script window.
@rdstern I'll keep this updated with the master branch. 
If possible, kindly do all possible tests on this branch in your daily operations. I'm particularly keen on which dialog scripts would fail when run through the script window.
@lloyddewit as mentioned to me by @rdstern you may be working on this as well.
> Fixed double imports of data when using script window

- instat/dlgGeneralForGraphics.Designer.vb
- instat/dlgGeneralForGraphics.vb
Fixes #8428 
@rdstern , @N-thony  I added `Use as Numeric` and `Display as Factor` checkbox on Graphics dialog. Please check it.
> Added Use as Numeric and Display as Factor checkboxes to Graphics dialog

- instat/instat.vbproj
- instat/packages.config
@rdstern 
For details of these changes, please see:
- lloyddewit/rscript#16
- lloyddewit/rscript#32
I think this PR also fixes #8533. I think that the only remaining parts of this issue are covered by lloyddewit/rscript#19. Please check.
Apart from keywords and curly brackets, do you have any other R code that is not correctly parsed by the RScript library?
Thanks
> In Script window, implemented ?? operator and ensured tildas correctly parsed

- instat/dlgDescribeTwoVariable.Designer.vb
- instat/ucrSelector.vb
Fixes #8256
@rdstern I have tested this with some dialogues in the Describe menu, have a look
> Returning the focus to the original receiver

- instat/ucrSplitButton.vb
@rdstern this replaces PR #8673 in case we decide to use the same control i.e `contexmenustrip` in the split button. I made it scrollable, have a look.
> Made the Context Menu Control in the Split Button Scrollable

- instat/dlgSelectColumns.vb
- instat/static/InstatObject/R/stand_alone_functions.R
Fixes #8705 
@rdstern check this if it is okay now.
> Fixed bug in Column Selection > Partially labelled option

- instat/ucrReceiverMultiple.vb
Fixes #8866
@rdstern I have used this as a good example to show the team in our today meeting on how to debug the code and fix when there is an issue. The problem was more general and coming from `GetVariableNamesList` function from `ucrReceiverMultiple` control. Have a look.
> Correcting the browsing in the Export Dataset Dialogue

- instat/dlgCalculator.vb
- instat/ucrCalculator.Designer.vb
- instat/ucrCalculator.resx
- instat/ucrCalculator.vb
Fixes issue #8925 
@rdstern , this PR is ready for review
N/b; this fixes the issue and the change in Wakefield requested in PR #8926
> Adjusting keyboards order and changing labels in the calculator

- instat/frmMain.Designer.vb
- instat/frmMain.vb
Fixes issue #8949 and issue #8815 partially.
@rdstern  this is ready for review where the first issue is fixed and the second partially; whereby @Patowhiz had instructed the paste new data frame item to be reverted to just paste new.
> Changes to Hide/show column item and changing paste new data frame back to paste new in edit menu

- instat/static/InstatObject/R/data_object_R6.R
Fixes #9086
@rdstern @Patowhiz I don't remember the reason that code has been changed but this seems now to be fixed. It will be good to test this PR seriously and see if there is no regression. I did some test and all seems to work fine. Over to you.
> Bug fixes in adding columns

- instat/frmMain.Designer.vb
- instat/frmMain.resx
- instat/frmMain.vb
- instat/ucrScript.Designer.vb
- instat/ucrScript.vb
fixes partly https://github.com/IDEMSInternational/R-Instat/issues/8847
@rdstern @derekagorhom have a look of the formatting of the script.
> Formatting Script

- instat/UserControl/ucrOutputPage.vb
Fixes #9327
@rdstern, I hope this solve the issue as mentioned. Have a look
> Displaying multi-line comments better, from scripts

- instat/ucrReceiverMultiple.vb
Fixes #9306 I hope!
@derekagorhom have a look of this PR, it attempts to fix b) from the issue by adding of variable in the multipe reveiver, I think the issue was in the code with `FindItemWithText` which might only check for the beginning of the text (prefix matching) instead of the full string, or it could be performing partial matches therefore we were not able to add another variable.
You can work on item a)
> Fixes bug in adding variable in multiple receiver

- inno_install_script_64bit.iss
@ChrisMarsh82, the changes I made, do the following
- AppName=R-Instat {#SetupSetting("AppVersion")}: This ensures the name and version number are displayed in Programs and Features as R-Instat 0.7.6 (or whatever version you're using).
- AppVerName=R-Instat {#SetupSetting("AppVersion")}: This ensures the version number is displayed during the installation process (and used for output filenames) as R-Instat 0.7.6.
> Ensures the name and version number are displayed in Programs and Features

- instat/dlgName.vb
- instat/dlgSelect.vb
- instat/frmMain.vb
- instat/static/InstatObject/R/data_object_R6.R
- instat/ucrDataView.vb
Fixes partially #9265
@rdstern this PR tempts to fix the issue when renaming selected columns. It completes issue #9265. Have a look
> Improve Column Renaming for Selected Columns

- instat/Model/DataFrame/clsDataFrame.vb
- instat/Model/DataFrame/clsDataFramePage.vb
- instat/frmMain.vb
- instat/ucrDataView.vb
Fixes #9236
@rdstern I hope this fixes what you have suggested in issue #9236, and replaces PR #9283 Have a look.
I have maintained the timer and in addition, the auto save will be triggered only if the data have been previously changed.
> Auto-Saving Data: Triggering Saves Only on Data Changes

- instat/ucrReceiver.vb
Fixes #9352
@rdstern @derekagorhom The issue was in `ucrReceiver.vb` at line 499. When setting or updating the R code, the `SetControlValue` sub is called, which attempts to auto-fill the control.
In the case of a multiple receiver, values are added as a group, typically using a `dataframe` name from the `selector's tag` or the current selector's dataframe name. However, in this dialogue, the selector only contains a list of data names, leading to the anticipated group name being set as `data_names` for values added to the multiple receiver. Have a look.
> Fixed bug in Append Dialogue

- instat/DlgDefineClimaticData.vb
- instat/dlgDescribeTwoVariable.vb
- instat/dlgImportClimMob.Designer.vb
- instat/dlgImportClimMob.vb
- instat/dlgTraitCorrelations.vb
- instat/dlgTraits.vb
- instat/instat.vbproj
- instat/sdgImportFromClimMob.vb
@lilyclements Added Help Page Links and Fixed Display in Summary Dialog
- Linked help pages to the following dialogs and sub-dialog:
dlgTraits (701)
dlgClimBoxCorrelations (703)
dlgImportClimOb (650)
sdgImport (716)
changed the define 328  to 672
- Corrected display logic in the 2/3-Way Summary dialog (`dlgDescribeTwoVariable`) under the Describe menu:
• Ensured correct alignment of row and column variables in summary tables
• Fixed mapping of receiver variable (`.x`) to match expected R output
Note: This change includes cleanup after help ID mix-up from earlier commit #9551.
> changes in the help page links and 2/3 summarize table

- instat/frmMain.Designer.vb
- instat/frmMain.resx
- instat/frmMain.vb
@rdstern I have implemented what we discussed, please check
Help menu -  deleted "and dialogues", so it just says Menus. Keep the Menus and Dialogues as they are, within the sub-menu.
Optional help menu should have the same order of the items as the view menu.
Tricot > Describe and added 2 extra elements.
Added a second new menu called Tidy. This has 4 entries as follows:
Finally deleted the menu item Genotype Data...
> Refined Help Menu 2. Added 2 extra elements in Tricot 3. Added new menu Tidy 4. Deleted "Genotype Data"

- instat/sdgDisplayModelOptions.vb
- instat/sdgTricotModelOptions.Designer.vb
@lilyclements, @rdstern, @MeSophie, @anastasia-mbithe, @derekagorhom, @Fran2or    I renamed the two estimates checkboxes to coefficients and fitted values respectively. I also changed the name of the model options sub-dialog used by the modelling (one covariate) and modelling (general) dialogs.
> Renamed estimates checkboxes and model options sub dialog

- instat/dlgTricotModelOneVarCov.vb
Fixes #9519
@rdstern and @lilyclements 
This completes the Tricot One Covariate dialog, as the main dialog and the two subdialogs are done and  linked.
Here, I have linked the Display Options subdilog to the main dialog and it is ready for testing.
> Linking Display Options Subdialog to the One Covariate Dialog

- instat/dlgModellingTree.vb
Fixes #9560 
@lilyclements @rdstern I have added the model options sub-dialog (created by @MeSophie) to the trees dialog. Kindly check it out. Thank you.
> Added the model options sub-dialog to the modelling (trees) dialog

- instat/dlgEdit.vb
this fixes #9641 
I put a dropdown  for replacing Ordered Factors as done in Factors 
Edit Cell > New Cell
@rdstern I have implemented what we discussed before . Please review
> Dropdown for replacing Ordered Factors as done in Factors

- instat/dlgModellingTree.vb
- instat/dlgPlacketLuceModel.vb
- instat/dlgTricotModelOneVarCov.Designer.vb
- instat/dlgTricotModelOneVarCov.vb
- instat/dlgTricotModellingGeneral.vb
- instat/sdgDisplayModelOptions.Designer.vb
- instat/sdgDisplayModelOptions.vb
Fixed #9688 
I have added the save checkbox that is visible when the coefficients checkbox is checked. This is only available for the modelling (no covariate) dialog as specified in the issue. I added some snippets to the other modelling dialog to ensure that the save option is not available there. Kindly check and let me know if there are any more required changes. Thank you.
Also, I realized the one covariate dialog had the maximize and minimize buttons on the dialog, so I change it to disable those options (as we have for the other dialogs).
> Added the save checkbox to the display options sub-dialog for the modelling dialog (no covariates)

- instat/sdgSummaries.vb
Fixes #9440 
First in the proportion and count, at the prepare data dialogue we were limited to numeric only and not neither factors or ordered factors and that check needed to be removed.
Its now working for  both ordered factors and factor labels for proportion and count and not limited like before
you just need to update the databook.
@rdstern  I have implemented what we discussed
@lilyclements kindly review
> Allowed Proportion and count input to accept factor labels.

- instat/dlgDescribeTwoVariable.vb
Fixes #9712 
Added` instatExtras::generate_summary_tables` which was missing in the two variable option of the Two variable summarise dialog.
@lilyclements , @rdstern can review this 
Thanks
> Fixed Bug in Describe two variable summarise

- instat/dlgModellingTree.vb
- instat/dlgPlacketLuceModel.vb
- instat/dlgTricotModelOneVarCov.vb
- instat/dlgTricotModellingGeneral.vb
- instat/sdgDisplayModelOptions.vb
Fixes #9732 
This is ready for testing.
@lilyclements , just for clarification, the Save checkbox is visible in No covariates modelling dialog only right?
> Added the Define Output as Tricot in the Display Options Subdialog

- instat/dlgRecodeFactor.Designer.vb
- instat/ucrInput.vb
- instat/ucrInputTextBox.Designer.vb
Fixes #2334
Fixes #3828
This PR adds the ability to add in more options into our numeric input. For example, you can now do `1:10` to get a list of numbers from 1 to 10.
**Testing**
For example, under "Prepare > Column: Factor > Recode Numeric", you can now put in a list by separating by ":". E.g., `1:10`.
@Ag-Derek can you review this? (Or assign someone to)
@rdstern can you review this as well.
> Adding more functionality to numeric input (e.g., 2:10)

- instat/dlgModellingTree.vb
- instat/dlgPlacketLuceModel.vb
- instat/dlgTraitCorrelations.vb
- instat/dlgTraits.vb
- instat/dlgTricotModelOneVarCov.vb
- instat/dlgTricotModellingGeneral.vb
Fixes partially #7306 for Tricot cases
@rdstern and @lilyclements following the discussion in the issue above, the multiple receivers in the modelling dialogs and correlation dialog are now able to autofill.
This took time because I started with implemeting the Traits dialog with a single receiver and after spending time on it, I realized the ucrReceiver only autofills when there is only one valid item. So in our case with multiple traits, it doesn't autofill.
I am thinking, what if, when we have multiple items, it could take the first one in the list, but that would be a @Patowhiz problem in the ucrReceiver.
In the meantime, I have set the receiver in Traits dialog to include numerics in the selector, to make it easier for the users.
> Autofilling in the Traits Multiple Receivers

- instat/dlgRowSummary.vb
Fixes #4141
We will return to the remaining issues later, but the "return later" tab has been given
> Disabling option for filter in Row Summaries

- instat/dlgDescribeTwoVariable.Designer.vb
- instat/dlgDescribeTwoVariable.vb
Fixes #6012 
The checkbox and the sdg were already implement but it looks like they were hidden, also they were only implemented for the two variable option on the Summarise dialog when you have a categorical and numberic which gives a `summary table`. 
@lilyclements when the user has a summary table summary they should be able to see it now.
This is ready for review
Thanks
> Implementing Omit Missing Value Options In Describe>Two Variable> Summarise

- instat/instat.vbproj
@rdstern This is a very small PR. It just removes an unused folder and file. These were related to the `Tricot XP` menu. I don't think there's anything you can test. These files were not used in the code and I checked that there was no regression after I removed then.
This PR changes the `instat.vbproj` file so it would be great if it could be merged quickly to reduce the risk of future merge conflicts.
Thanks
> Removed unused dialog definition folder

- instat/sdgDisplayModelOptions.Designer.vb
- instat/sdgDisplayModelOptions.resx
- instat/sdgDisplayModelOptions.vb
Fixes #9744
@lilyclements @rachelkg @rdstern 
I have added the tooltips as given in the issue. 
@lilyclements I think you may have forgotten one (the general plot radio button).
I realized that for the custom controls (the ones starting with ucr), adding the tooltips directly wasn't working so I had to create a helper function for that.
Thank you.
> Added tooltips to the tricot model display sub-dialog

- instat/dlgModellingTree.vb
Fixes #9867 
This excludes charater variables from the Explanatory Model receiver in Tricot > Model > Modelling Trees
> Excluded Characters from the Explanatory model receiver

- instat/dlgClimaticStationMaps.vb
As outlined in #7661
We want to call in the `geometry` parameter into the correct place when the receiver is filled, and to otherwise call in the `data_book$get_geometry(...)` option.
> Calling geometry correctly in Climatic Maps Dialog

- instat/dlgDescribeTwoVariable.vb
Replaces #9895
Partly Fixes #9880
I ensured the missing option button will not be able to appear on the Skim option but on both the Two and Three Variable options
@lilyclements , @berylwaswa , @Rockjunior can you review this 
Thanks
> Fixed Bug Where Missing Option Button was Appearing on the Skim Option

- instat/frmMain.vb
Making sure when using File>close data book, it automatically sends user back to starting screen view
fixes partly #9897
This PR fixes the issue below
@derekagorhom one addition to the changes is when I use File > Close Data Book and I have switched the Window to the Column (or maybe other) types of metadata, then I don't get the usual starting screen. I can use the curly arrow to get it back. Could that please be done automatically.
@lilyclements , @rdstern this is ready for review 
Thanks
> Return to Start Screen After Closing Data Book

- instat/dlgExportClimaticDefinitions.Designer.vb
- instat/dlgExportClimaticDefinitions.vb
- instat/sdgDefineAnnualRainfall.Designer.vb
- instat/sdgDefineAnnualRainfall.vb
As outlined in #9926
1. Removing the "Year" and "Month" receivers from the main dialog
2. Removing the "Rain" receiver from the main dialog
3. Setting up tab order correctly
4. Amending the layout to be more intuitive for the user
5. Removing the option for extremes as this is part of the annual summaries
6. Changing "Country" inputs to drop downs
7. Setting up correctly the parameter values for "Monthly Temperature Summaries" in the sdg for export_r_instat_to_buckets function
> Amendments to Export to Buckets design

- instat/dlgCalculator.vb
Fixes #9428
This fixes the issue with a dataset and a column in the dataset having the same name i.e `sza`
This is ready for testing.
> Temporarily renaming Dataframe in the Calculator

- instat/sdgDataOptions.vb
Fixes #9957 
@rdstern @lilyclements @Ag-Derek ,This PR ensures that the Data Options sub-dialog always opens with the correct data frame from the parent dialog
> Made Data Options control can open in the correct data frame

- instat/dlgImportFromEPicsa.Designer.vb
- instat/dlgImportFromEPicsa.vb
Fixes partly #9960
@lilyclements @rdstern @berylwaswa 
@lilyclements I have worked on all the things you mentioned with the exception of the `Data` tab and also the issue with the `Find Files` button on the `Definitions` tab. 
I thought I should push it so that you can check and give any feedback. Then I'll be able to work on all the needed bits once you send me your response.
For easy reference, I'll mention that problem here again.
> Please, can you help me resolve the error below?
> 
> It happens in the `list_definition_versions` function that runs internally when I click on the `Find Files` button.
> 
> <img alt="Image" width="350" height="300" src="https://private-user-images.githubusercontent.com/110286432/492758784-498cfa73-606a-43d6-a4de-d4c40c25cd29.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGc …
> Added the Import from E-PICSA dialog.
