IDEMSInternational/R-Instat

instat/dlgVisualizeData.Designer.vb
instat/dlgVisualizeData.resx
instat/dlgVisualizeData.vb
instat/instat.vbproj

@dannyparsons kindly merge this new dialog.

New visualize data dialog

---

instat/dlgInsertColumn.vb

Improving the Insert columns/rows dialog

---

instat/ucrGeom.vb

Added fatten parameter to geom_boxplot

---

instat/dlgColumnStats.resx

Fixes https://github.com/africanmathsinitiative/R-Instat-Translations/issues/2 (Column Summaries dialog query); R-Instat Translations repository.
@maxwellfundi this is ready.

Changing Text on the Proportion and percentages button in column summaries dialog

---

instat/dlgBarAndPieChart.resx
instat/dlgCombine.resx
instat/dlgEnter.resx
instat/dlgFindNonnumericValues.resx
instat/dlgFreqTables.Designer.vb
instat/dlgHistogram.designer.vb
instat/dlgHistogram.resx
instat/dlgMerge.resx
instat/dlgRandomSample.resx
instat/dlgRecodeNumeric.resx
instat/dlgSaveAs.resx
instat/dlgStack.resx
instat/dlgStringHandling.resx
instat/dlgSummaryBarOrPieChart.Designer.vb
instat/dlgSummaryBarOrPieChart.resx
instat/dlgSummaryTables.resx
instat/dlgTwoWayFrequencies.resx
instat/dlgUnstack.resx
instat/dlgViewGraph.resx
instat/sdgOneVarGraph.resx
instat/sdgPlots.resx
instat/sdgThemes.resx
instat/ucrAxes.resx
instat/ucrGridUnit.resx

This has the Enter and Themes subdialog changes for the translations.
@africanmathsinitiative/developers I'm still going through the dialogs for the translations.

New french translations

---

instat/dlgModelling.Designer.vb
instat/dlgModelling.resx
instat/dlgModelling.vb

Added keys to the MASS and stat key boards

---

instat/dlgOpenNetCDF.vb
instat/sdgOpenNetCDF.Designer.vb
instat/sdgOpenNetCDF.resx
instat/sdgOpenNetCDF.vb

- Warning message added if sub dialog incomplete when returning to main dialog
- OK disabled on main dialog when sub dialog incomplete
- Dimension labelling corrected on sub dialog based on file and lon lat added when X and Y

NETcdf dialog/sub dialog small improvements

---

instat/clsRCodeStructure.vb
instat/dlgImportDataset.Designer.vb
instat/dlgImportDataset.resx
instat/dlgImportDataset.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/ucrSave.vb

@africanmathsinitiative/developers this is ready for review. As well as the new feature I'm particularly concerned that it has not had effected the current import features.

Import multiple Excel sheets

---

instat/ucrGeom.vb

Added string names to the shape aesthetic

---

instat/sdgCreateFilter.vb

Added message when leaving filter subdialog with the condition not added

---

instat/sdgSummaries.Designer.vb
instat/sdgSummaries.resx
instat/sdgSummaries.vb
instat/static/InstatObject/R/Backend_Components/summary_functions.R

Fixes #5006
@Ogik99 kindly check if the changes are what are required. Thanks.

Added non missing option to the summary subdialog

---

instat/dlgRenameDataFrame.vb

Rename data frame

---

instat/clsGridLink.vb
instat/static/InstatObject/R/instat_object_R6.R

changes to enable renaming a data frame while only changing the cases

---

instat/static/InstatObject/R/data_object_R6.R

Replacing is.tibble() with is_tibble() on the data_object_R6.R

---

instat/static/InstatObject/R/instat_object_R6.R

fixes #5378 
@africanmathsinitiative/developers  this can reviewed

typoo changes to tidy Climatic

---

instat/dlgDefineCRI.Designer.vb
instat/dlgDefineCRI.resx
instat/dlgDefineCRI.vb
instat/dlgDefineCorruption.Designer.vb
instat/dlgDefineCorruption.resx
instat/dlgDefineCorruption.vb
instat/dlgDefineCorruptionOutputs.Designer.vb
instat/dlgDefineCorruptionOutputs.resx
instat/dlgDefineCorruptionOutputs.vb
instat/dlgFitCorruptionModel.Designer.vb
instat/dlgFitCorruptionModel.resx
instat/dlgFitCorruptionModel.vb
instat/frmMain.vb

Fixes #2841
@africanmathsinitiative/developers In progress

Correcting names for corruption dialogs

---

instat/dlgHistogram.designer.vb
instat/dlgHistogram.resx
instat/dlgHistogram.vb
instat/frmMain.vb

Fixes #5343 
@maxwellfundi This has now been addrressed!

Adding counts to histogram

---

instat/ucrGeom.vb

fixes #5409 
@africanmathsinitiative/developers this  is ready for review

Bar chart bug

---

instat/ucrGeom.vb

Added outside parameter to geom rug

---

instat/dlgHistogram.vb

still fixing #5343 
This is a small change on the merged and closed pull request. (Adding counts to histogram)
@africanmathsinitiative/developers Someone can review this.

Removing empty sub on Histogram dialog

---

instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Adding atan2 key to maths calc and and also expanding the expression on the calculator

---

instat/dlgClimaticSummary.vb
instat/dlgColumnStats.vb
instat/dlgDescribeTwoVariable.vb
instat/dlgOneVariableSummarise.vb
instat/dlgSummaryTables.vb
instat/sdgSummaries.Designer.vb
instat/sdgSummaries.resx
instat/sdgSummaries.vb
instat/static/InstatObject/R/Backend_Components/summary_functions.R

@africanmathsinitiative/developers this is ready for review. Fixes #5300 and #5310. This is the extension of missing values options to enable calculation of climate normals. I am available to provide guidance on testing if needed.

Amending missing values options - Climate normals implementation.

---

instat/dlgLinePlot.designer.vb
instat/dlgLinePlot.resx
instat/ucrVariablesAsFactor.vb

Removing the unused lblGroup on issue #5431

Line plot changes

---

instat/dlgBoxPlot.vb
instat/sdgPlots.vb
instat/ucrAdditionalLayers.vb

fixes #5321 
@africanmathsinitiative/developers this is ready for review and will need much testing
@Ivanluv I have built on your attempt in #5426 to remove the message. Looking at the code of the control, it needed some reworking to work properly so I've made more substantial changes to the layers control and simplified it hopefully.
Also, see what I did on the boxplot dialog. One thing was to ensure all geom parameters have a position, so the layers order correctly. The second was to make variable for all the geom parameter names and then pass this list to the plot subdialog. This is to ensure that you can't delete main dialog layers from the sub dialog.
This will need to be done on every plot dialog to work correctly. Maybe you could look at this with @shadrackkibet?

graphics layers bug fixes

---

instat/DlgDefineClimaticData.vb
instat/dlgPICSACrops.Designer.vb
instat/dlgPICSACrops.vb
instat/frmMain.vb
instat/static/InstatObject/R/data_object_R6.R

- added output message to define climatic
- fixed crash from repeated clicking on view last graph
- PICSA crops renamed planting length to crop length

Climatic changes & bug fixes

---

instat/sdgSummaries.Designer.vb
instat/sdgSummaries.resx
instat/sdgSummaries.vb
instat/ucrInput.vb

Climate normals

---

instat/ucrGeom.vb

Minor edit on geom contour bin width parameter

---

instat/dlgMakeDate.vb

Added a new Option(R) to Make Date Dialog

---

instat/dlgRugPlot.vb

@dannyparsons I have now gone through your boxplot to see what was done about the layers stuff and started implementations on other dialogs on  graphs. Please have a look at this just to counter check that this is whats needed.

Graphs edits

---

instat/dlgConversions.Designer.vb
instat/dlgConversions.resx
instat/dlgConversions.vb
instat/static/InstatObject/R/stand_alone_functions.R

@africanmathsinitiative/developers this is ready for review. Fixes #5395. Here is a dataset to test this dialog [synoptic_stations.zip](https://github.com/africanmathsinitiative/R-Instat/files/3447019/synoptic_stations.zip). Below is the design. @dannyparsons  @rdstern any comments?

Additional feature conversions dialog

---

instat/dlgCalculator.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Added a circular keyboard to the calculator

---

instat/frmMain.resx

@dannyparsons @maxwellfundi this is a small name change on the form main.

Infill missing dates to Fill Date Gaps

---

instat/dlgCalculator.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Fixes #5332
@africanmathsinitiative/developers Ready to be reviewed. Someone to review the changes.

Added a few keys to the circular keyboard and made the proposed changes 

---

instat/DlgUseDate.vb
instat/static/InstatObject/R/data_object_R6.R

fixes #5428
- updated auto define as climatic from Use Date
- updated message output when defining climatic data

Improvements to define climatic

---

instat/dlgSpells.Designer.vb
instat/dlgSpells.vb

fixes #5316 with a simplified design

re-designed element condition options on Spells dialog

---

instat/static/InstatObject/R/instat_object_R6.R

Crop probabilities account for station

---

instat/dlgPICSARainfall.Designer.vb
instat/dlgPICSARainfall.vb
instat/ucrAxes.vb

PICSA Graphs sub dialog bug fixes

---

instat/dlgInfill.Designer.vb
instat/dlgInfill.resx
instat/dlgInfill.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R

Infill missing date- Adding data limits and fixed limits options

---

instat/dlgPICSARainfall.vb
instat/sdgPICSARainfallGraph.vb

fixed date limit bugs on PICSA Rainfall

---

instat/ucrGeom.vb

Added stat_peaks and stat_valleys to list of geoms

---

instat/sdgDoyRange.vb

Minor issue#5499

---

instat/dlgFitModel.Designer.vb
instat/dlgFitModel.resx
instat/dlgFitModel.vb

Fit model#5561

---

instat/dlgCalculator.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Added a new keyboard (Factor) to the calculator

---

instat/dlgBarAndPieChart.Designer.vb
instat/dlgBarAndPieChart.resx
instat/dlgBarAndPieChart.vb
instat/instat_oif0jzjc_wpftmp.vbproj

Added column chart to dlg Bar and Pie Chart

---

instat/ucrGeom.vb

fixes #5544 
@africanmathsinitiative/developers  this can be reviewed

Geom tremap

---

instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Improvements and tooltips for the calculator transform keyboard

---

instat/ucrReceiverExpression.vb

Adding focus to the function in the Receiver Expression

---

instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Fixes #5553 , #5549 , #4347
@africanmathsinitiative/developers Some to review this.
This replaces the three pull request with conflicts.

Tool tips and designer for different keyboards

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj

@rdstern  The treemap is now merged and placed on the location you suggested.

Dlgtreemap

---

instat/dlgOpenNetCDF.Designer.vb

This is related to issue 5510. However it does not solve the issue. This commit is just for me to learn the R-Instat pull request process.

Changed tab order on 'import and tidy NetCDF file' dialog. 

---

instat/ucrDataView.vb

@africanmathsinitiative/developers  this is ready for review.Fixes #4831

View data frame

---

instat/ucrDistributions.vb

@dannyparsons please merge this. Fixes #5638

Added package name

---

instat/frmMain.Designer.vb
instat/frmMain.resx

Close data book#5614

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Suggested change in R-Instat Prepare menu

---

instat/dlgCalculator.vb
instat/sdgCalculationsSummmary.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Show error#5604

---

instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Changing right-click in reogrid a lttle

---

instat/dlgUseModel.Designer.vb
instat/dlgUseModel.vb

Related to #5539
@africanmathsinitiative/developers Someone to check whether the size of the dialog is now okay and that the controls can be clearly seen

Resized the model dialog

---

instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Fixes #5242
@rdstern This is now okay

Implementing right click

---

instat/dlgOpenNetCDF.Designer.vb
instat/dlgOpenNetCDF.vb
instat/sdgOpenNetCDF.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R

Import multiple NetCDF files 

---

instat/ucrDataView.Designer.vb

Fixes  #5242
@rdstern This is now okay

Minor change on cell right click

---

instat/dlgFromLibrary.vb
instat/dlgImportDataset.vb

Remembering Path in Open File location

---

instat/clsRCodeStructure.vb
instat/clsRFunction.vb
instat/clsRParameter.vb
instat/clsRSyntax.vb
instat/dlgHypothesisTestsCalculator.Designer.vb
instat/dlgHypothesisTestsCalculator.vb

Fixes part (a) of #5630 
@shadrackkibet Kindly check if this is okay.

Added three keys to the Hypothesis test dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

FrmMain Changes on Model Menu

---

instat/dlgAugment.Designer.vb
instat/dlgAugment.resx
instat/dlgAugment.vb
instat/instat.vbproj

@maxwellfundi Kindly check if this is okay. It's a new dialog (Augment). Merge it.

Added a new dialog in the used model menu

---

instat/dlgModelling.vb

Fixes #5421. @africanmathsinitiative/developers This is ready for review.

Modelling fixes

---

instat/instat.vbproj

@rdstern  the datasets had been added just that the properties for the datasets were not set properly. 
Please confirm that you can see them when you test this PR
Thank you.

Adding Climatic guide datasets

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Changes in the Prepare menu

---

instat/dlgClimaticBoxPlot.vb
instat/dlgClimaticSummary.vb
instat/dlgDisplayDailyData.vb
instat/dlgExtremesClimatic.vb
instat/dlgInventoryPlot.vb
instat/static/InstatObject/R/data_object_R6.R

@rdstern I have  updated the dialogue to the new system as you suggested .Am however still looking at the issue on the Inventory dialogue  complaining that the data has been defined as climatic.Related to  issue #5572

Climatic commands#5572

---

instat/dlgImportDataset.resx
instat/dlgImportDataset.vb

@rdstern I've moved the changes for the import dialogue  to this pull request.Related to #5700

Minor fix2#5700

---

instat/dlgInventoryPlot.vb

@dannyparsons  does this look right?.fixes #5746

Inventory plot - restrict date receiver to Date types

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

This pull request replaces #5754 
@maxwellfundi Kindly merge this change.

Enabling and showing Tidy and Augment dialogs from the frmmain.

---

instat/sdgCreateFilter.Designer.vb
instat/ucrFilter.Designer.vb
instat/ucrFilter.resx
instat/ucrFilter.vb
instat/ucrInputComboBox.vb

Added a simple keyboard to the filter dialog

---

instat/dlgDeleteRowsOrColums.Designer.vb
instat/dlgDeleteRowsOrColums.resx
instat/dlgDeleteRowsOrColums.vb
instat/ucrNud.vb

Improve the Prepare > Data Frame > Delete Columns/Rows dialogue 

---

instat/dlgAugment.Designer.vb
instat/dlgAugment.vb
instat/static/InstatObject/R/data_object_R6.R

Fixes #5647
This is working for a single model.

Added the augment broom dialog use models

---

instat/dlgTidy.Designer.vb
instat/dlgTidy.resx
instat/dlgTidy.vb
instat/ucrReceiverMultiple.vb

Fixes #5647
This is working for a single model for now!
@africanmathsinitiative/developers  This is ready for review.

Added the tidy broom dialog to use model

---

instat/ucrVariablesAsFactor.vb

@africanmathsinitiative/developers  this is ready for review .Fixes #5707

Minor change to ucrVariableAsFactor

---

instat/dlgPICSARainfall.vb

@lloyddewit  this fixes the issue in pull request #5743

Reading of numeric values  in the PICSA Rainfall dialogue

---

instat/ucrColumnMetadata.vb

@rdstern this is the implementation of your request in #5790. Please test it.

Adding a check to convert non upper cases and string of length one and updating the cell in column metadata

---

instat/dlgHistogram.vb

Having histograms show proportions and percentages

---

instat/dlgRestrict.vb
instat/instat.vbproj
instat/sdgFiltersFromFactor.Designer.vb
instat/sdgFiltersFromFactor.resx
instat/sdgFiltersFromFactor.vb

@maxwellfundi this a new empty subdialog, please merge.,

New Filters from factor subdialog

---

instat/dlgImportDataset.vb

Fixes Issue #5725, and implements comment from @Patowhiz peer review on PR #5767 'Correctly handles special characters in Excel file names'.
I created a new PR for this change because PR #5767 was already merged.
@Patowhiz please could you quickly check that this change is OK? Thanks

New PR to implement peer review suggestions in PR #5767

---

instat/clsRLink.vb

Implements quality improvement comment from @Patowhiz on PR  #5808 (already merged).
This improvement makes 3 variable type declarations explicit rather than dynamic.
@Patowhiz please could you quickly check that this change is OK? Thanks

Addition to PR #5808 Issue multiline commands in script window

---

instat/dlgHomogenization.Designer.vb
instat/dlgHomogenization.resx
instat/dlgHomogenization.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj

This is the start of work on issue #5461. It is an empty dialog at the moment, so nothing to review? @maxwellfundi can you merge this.

New homogenization dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

@maxwellfundi merge this so that @rdstern can test the new homogenization dialog in #5840.

Enabling homogenization in climatic menu

---

instat/dlgCompareSummary.Designer.vb
instat/dlgCompareSummary.resx
instat/dlgCompareSummary.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj
instat/sdgVerificationSummaries.Designer.vb
instat/sdgVerificationSummaries.resx
instat/sdgVerificationSummaries.vb
instat/ucrContinuousVerification.Designer.vb
instat/ucrContinuousVerification.resx
instat/ucrContinuousVerification.vb

@maxwellfundi can you review, approve and merge this? Perhaps @lloyddewit would you like to check and approve it first? This is linked to #5843.

New verification dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes #5839
@africanmathsinitiative/developers This is ready for review. 
@lloyddewit I have managed to redo this since the other pr had conflicts. Could you review this so that it get merged to a void conflicts?

Added a new Structured Menu to R-Instat

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

@lloyddewit @rdstern @maxwellfundi I have enabled the new dialog for verification under **climatic>prepare>compare>summary**. Please approve and merge this so that pull request #5847 can now be tested.

Enabled summary menu item under climatic toolstrip

---

instat/dlgTaylorDiagram.Designer.vb
instat/dlgTaylorDiagram.resx
instat/dlgTaylorDiagram.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj

@rdstern @lloyddewit @maxwellfundi this is a new dialog proposed at #4944. Please review and approve for merging. Notice that I have enabled the dialog menu item (placeholder) on frmmain because I will be putting up a pull request for testing as soon as this is merged.

New Taylor diagram dialog

---

instat/dlgInfillMissingValues.Designer.vb
instat/dlgInfillMissingValues.resx
instat/dlgInfillMissingValues.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj

This is a new dialog suggested [here ](https://tree.taiga.io/project/idems-r-instat/task/219). @rdstern @lloyddewit, please approve and merge so that we can continue with work on this dialog.

New fill missing values dialog

---

instat/dlgTaylorDiagram.Designer.vb
instat/dlgTaylorDiagram.resx
instat/dlgTaylorDiagram.vb

Fixes #4944. @rdstern this is the initial implementation of Taylor diagrams. Please do some initial testing.

Taylor diagrams implementation

---

instat/dlgThreeVariableFrequencies.Designer.vb
instat/dlgThreeVariableFrequencies.resx
instat/dlgThreeVariableFrequencies.vb

@africanmathsinitiative/developers  this is ready for review .Fixes #5871

Design changes to the three variable dialogue

---

instat/dlgScatterPlot.resx

Changes
* Moved the receivers so that it does not overlap with the save
Fixes #5870 
For before screenshot, see the issue. Now looks like this:

Scatter Plot Design

---

instat/dlgCumulativeDistribution.resx
instat/dlgCumulativeDistribution.vb

Fixes #5799 
Changes:
* ucrSave aligned with comment input box
* Controls on right hand side aligned
* Top buttons no longer overlap
* First letter capitilised for items in combo box
* Tab order
(for "Before" see pull request). After:

dlgCumulativeGraph design

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

@lloyddewit as discussed in #5108 I have added the visualise data dialog to the main form.
This has been placed under Prepare > Check Data > Visualise Data at the top, and at the top of the Climatic > Tidy and Examine menu.> Visualise Data as outlined in #5064 

Adding dlgVisualiseData to frmMain

---

instat/dlgInfillMissingValues.Designer.vb
instat/dlgInfillMissingValues.resx
instat/dlgInfillMissingValues.vb

This is still a work in progress. @rdstern we do not yet have an issue for this. Can you also do some preliminary testing? It is in a state that can be tested. Here is a screenshot.

Infilling missing values using zoo package methods

---

instat/dlgBarAndPieChart.vb
instat/dlgBoxPlot.vb
instat/dlgClimaticBoxPlot.vb
instat/dlgClimaticStationMaps.vb
instat/dlgCountryColouredMap.vb
instat/dlgCumulativeDistribution.vb
instat/dlgDescribeTwoVarGraph.vb
instat/dlgDisplayTopN.vb
instat/dlgDotPlot.vb
instat/dlgGeneralForGraphics.vb
instat/dlgHistogram.vb
instat/dlgMosaicPlot.vb
instat/dlgOptionsByContextBoxplot.vb
instat/dlgPICSARainfall.vb
instat/dlgParallelCoordinatePlot.vb
instat/dlgRugPlot.vb
instat/dlgScatterPlot.vb
instat/dlgSummaryBarOrPieChart.vb
instat/dlgTreemap.vb
instat/dlgUseGraph.vb

this fixes  the  errors in the graphics dialogue  raise in PR #5803 and #5896

Adding scale date to all graphics dialogue

---

instat/dlgMakeDate.Designer.vb
instat/dlgMakeDate.resx
instat/dlgMakeDate.vb

Changes:
- design amendments to decrease the depth of the dialog from 613x516 to 533x516
One of the dialogs discussed in #5835 (see point (c))

dlgMakeDate design

---

instat/ucrSave.vb

Partially fixes issue #3577. Inline documentation for ucrSave. Updated comments only. No code changes.
Replaces PR #5794 .
@rdstern the changes are only to the comments, there is nothing to test. Please could you approve?
@maxwellfundi This was already peer reviewed and approved by @Patowhiz in PR #5794. I cannot approve this PR because I am the author. Please could you approve?
Thank you!

Inline documentation for ucrSave, new PR to replace PR #5794

---

instat/instat.vbproj
instat/ucrFilePath.Designer.vb
instat/ucrFilePath.resx
instat/ucrFilePath.vb

A new empty control aimed at solving issue #5606 and to be used and tested in PR #5873.
@lloyddewit this is an empty control. It's design and logic code implementation will be added in PR #5873. So this has to be merged before it.

UcrFilePathControl

---

instat/dlgVisualizeData.Designer.vb
instat/dlgVisualizeData.vb

Still working on this.
* Dialog design
* Code set up to run `vis_dat`, `vis_miss`, `vis_guess`.
Fixes #5064 
For previous discussions and branch on this, see #5108 
Left to work on:
* The R-code won't run for large data sets. The largest data set I have tried is the dodoma data, where I am only having a problem with this for vis_miss. I will have a look to see if there are alternative packages, or another way around handling large data sets.
* The plots sometimes need some clicking between "data frame" and "selected variables" to display the graphic, rather than an empty white box (i.e., to run the $add_graph and $get_graphs lines)

dlgVisualiseData dialog - design and code

---

instat/ucrScript.Designer.vb
instat/ucrScript.vb

Fixes #5868 .
Please note, just like the way the current supported undo is a simple one, this PR aims to implement a simple Redo. Of course it's possible to implement a fully undo and redo just like word or any other code editor but that's a doable long shot.
Vb.NET doesn't offer direct Redo functionality for the VB.NET, I had to develop a work around to achieve this functionality.

UcrScript Redo

---

instat/dlgInfillMissingValues.Designer.vb
instat/dlgInfillMissingValues.resx
instat/dlgInfillMissingValues.vb

@rdstern This is ready for you to test. I have tried to enable **structTS** option to work when infilling missing values. Here I am using `imputeTS` package which seems to work with data with  `frequency=1`.

Fill missing values StructTS option 

---

instat/dlgRestrict.resx
instat/dlgRestrict.vb
instat/sdgFiltersFromFactor.Designer.vb
instat/sdgFiltersFromFactor.resx
instat/sdgFiltersFromFactor.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R

Fixes #4800. @rdstern this is ready for you to test. This implements a new subdialog that generates filters from factor levels.

Generating filters from factor levels

---

instat/frmMain.resx

Fixes #5890. @rdstern @lloyddewit this is a small change. This is ready for you to review.

Small Frmmain change Hide Dataframes to Hide/Show Data Frames.

---

instat/dlgCumulativeDistribution.resx
instat/dlgDescribeTwoVarGraph.resx

Fixes #5899
@africanmathsinitiative/developers Ready for review

Changed Options text property to Plot Options in Cumulative/Exceedance graph and Two Variable graphs dialogs

---

instat/dlgClimsoftWizard.Designer.vb
instat/dlgClimsoftWizard.resx
instat/dlgClimsoftWizard.vb
instat/instat.vbproj

@africanmathsinitiative/developers this is an empty dialog. Will be used in implementing some of the proposals made in issue #4915. 
@rdstern @maxwellfundi can this be merged, it changes the project "solution" files and may cause conflicts if another developer makes changes to those files. I will use this dialog in PR #5502

New Climsoft Import Wizard Dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes #5949 
@africanmathsinitiative/developers Can be reviewed

Added New Menu Items under Climatic Menu

---

instat/ucrCore.vb

Fixing the warning message in the comment in #5926

Ucr core documentation

---

instat/dlgRegularSequence.vb

Proper Setting of the Save Control in the Prepare > Column: Calculate >Regular Sequence and  prepare > Column: Date > Generate Dates

---

instat/dlgClimaticCheckDataTemperature.vb

Added a method to a selector when data frame changes to Climatic>Check Data>QC Temperature

---

instat/dlgCalculator.vb
instat/dlgConditionalQuantilePlot.Designer.vb
instat/dlgConditionalQuantilePlot.resx
instat/dlgConditionalQuantilePlot.vb
instat/dlgOtherRosePlots.Designer.vb
instat/dlgOtherRosePlots.resx
instat/dlgOtherRosePlots.vb
instat/dlgSeasonalPlot.Designer.vb
instat/dlgSeasonalPlot.resx
instat/dlgSeasonalPlot.vb
instat/dlgTimeSeriesPlot.Designer.vb
instat/dlgTimeSeriesPlot.resx
instat/dlgTimeSeriesPlot.vb
instat/dlgWindPollutionRose.Designer.vb
instat/dlgWindPollutionRose.resx
instat/dlgWindPollutionRose.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj
instat/sdgSummaries.vb
instat/sdgTimeSeries.Designer.vb
instat/sdgTimeSeries.resx
instat/sdgTimeSeries.vb

Added menu items under Structured>Circular

---

instat/dlgRegularSequence.vb

Reverts africanmathsinitiative/R-Instat#5956 so that comment can be corrected, as suggested by @Patowhiz

Revert PR #5956 so that comment can be corrected

---

instat/dlgTimeSeriesPlot.Designer.vb
instat/dlgTimeSeriesPlot.vb
instat/sdgTimeSeries.Designer.vb
instat/sdgTimeSeries.vb
instat/static/InstatObject/R/stand_alone_functions.R

The basic main dialog is working.
To do:
@rdstern the basic functionality could be tested now or could wait until the whole dialog is complete

Time series plots dialog

---

instat/clsRLink.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R

Fixes #5884
@africanmathsinitiative/developers this ready for review.

Viewing Last Graph In R Viewer

---

instat/ucrReorder.vb

Reordering of Multiple Items in ucrReorder Control

---

instat/dlgDisplayDailyData.Designer.vb
instat/dlgDisplayDailyData.resx
instat/dlgDisplayDailyData.vb

Improvements to the display daily dialogue

---

instat/instat.vbproj
instat/sdgMissingOptions.Designer.vb
instat/sdgMissingOptions.resx
instat/sdgMissingOptions.vb

@dannyparsons @rdstern @lloyddewit this is an empty form(subdialog) as stated in #6012. Please approve and merge.

New missing options subdialog

---

instat/dlgBarAndPieChart.vb

 Bar and Pie Chart Dialog Bug

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes partly #4915
This PR adds a menu item to the Climate menu. The menu item gives access to the import from climsoft wizard dialog. The dialog  functionality has been added in PR #5694. 
@lloyddewit only 3 lines of code was added in this PR, the rest are designer changes as discussed with @rdstern .

Import From Climsoft wizard menu

---

instat/dlgPolarAnnulus.Designer.vb
instat/dlgPolarAnnulus.resx
instat/dlgPolarAnnulus.vb
instat/dlgPolarCluster.Designer.vb
instat/dlgPolarCluster.resx
instat/dlgPolarCluster.vb
instat/dlgPolarFrequency.Designer.vb
instat/dlgPolarFrequency.resx
instat/dlgPolarFrequency.vb
instat/dlgPolarPlot.Designer.vb
instat/dlgPolarPlot.resx
instat/dlgPolarPlot.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj

@africanmathsinitiative/developers Someone to review these frmmain changes.
I would like these changes to be merged as fast as possible so that I carry on with further work on the dialogs

Added four Dialogs to Structured > Circular > Other Rose Plots menu 

---

instat/dlgSeasonalPlot.Designer.vb
instat/dlgSeasonalPlot.vb
instat/static/InstatObject/R/stand_alone_functions.R

Branched from #5984 
- Changed estimates summary options after discussion with @rdstern. Estimates' summary now fixed to the same as Reference Values' but thresholds can be different.
- Set mean as the default summary
- Fixed R code setting for controls where this was not set up
- Corrected variables from receivers to be as strings not RFunctions

Seasonality Plots dialog (branched from HawardKetoyoMsatsi:seasonalityplots)

---

instat/dlgSeasonalPlot.Designer.vb
instat/dlgSeasonalPlot.vb
instat/static/InstatObject/R/stand_alone_functions.R

Fixes #5980. @dannyparsons @rdstern the seasonality comparisons dialog is ready please have a look.  @shadrackkibet and I worked on the issue.

New seasonality plots dialog

---

instat/static/InstatObject/R/instat_object_R6.R

fixes #5959
This now has the correct rain totals for multiple stations in the PICSA crops dialog, and has the same correct functionality for a single station, but please check both cases in review.

Bug fix: PICSA Crops dialog rain totals

---

instat/ucrSaveGraph.vb

@lloyddewit I wrote the documentation for ucrSaveGraph. Please could you peer review this PR? Thanks.

Documenting ucrSaveGraph

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

@rdstern @dannyparsons @lloyddewit this is a small change in the frmmain as described in #3995. See the screenshot below for the latest change.

Renaming menu item: Climatic>File>Import from IRI Data Library

---

instat/dlgInventoryPlot.designer.vb
instat/dlgInventoryPlot.resx
instat/dlgInventoryPlot.vb
instat/static/InstatObject/R/stand_alone_functions.R

I have added the summary R function in the dlgInventory form of the issue #5833. 
So, I'm waiting for this PR to be review.

Adding the summary R function in dlgInventory

---

instat/dlgClimaticSummary.Designer.vb
instat/dlgClimaticSummary.resx
instat/dlgClimaticSummary.vb
instat/dlgColumnStats.Designer.vb
instat/dlgColumnStats.resx
instat/dlgColumnStats.vb
instat/sdgMissingOptions.Designer.vb
instat/sdgMissingOptions.vb
instat/sdgSummaries.Designer.vb
instat/sdgSummaries.resx
instat/sdgSummaries.vb
instat/static/InstatObject/R/Backend_Components/summary_functions.R

Fixes #6012 and Fixes #6025. This is still a work in progress.

Separating missing value options on summary dialogs and changing single element receiver to a multiple receiver

---

instat/dlgImportGriddedData.Designer.vb
instat/dlgImportGriddedData.resx
instat/dlgImportGriddedData.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R
instat/ucrDateTimePicker.vb

Fixes #3995. @dannyparsons @rdstern I am putting up this for you to have a look. Danny, I am getting below bugs especially with **CHIRPS** when downloading data. Sometimes it works, when I change the time range. Perhaps it is an internet issue? I tried copying the link from VS output window into the browser, sometimes it downloads the file but then when I try to open the file using Netcdf dialog I get an error as shown below. I am not sure why. 
**Download from IRI**
**Import Netcdf**

Download gridded data from IRI as Netcdf format

---

instat/clsRecentFiles.vb
instat/frmMain.vb
instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Data View Window Startup helpful Information

---

instat/dlgVisualizeData.Designer.vb
instat/dlgVisualizeData.vb

Added controls and their functionality to visdat dialogue

---

instat/dlgCalculator.resx
instat/dlgCalculator.vb
instat/sdgCalculationsSummmary.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

@africanmathsinitiative/developers This is work in progress
I have added the new control to the calculator. It adds a new column to the data frame. The part remaining is positioning of the new column.

Replacing the old save control in the calculator with a new save control

---

instat/ucrDataView.Designer.vb

Related to PR #6019 and adds @dannyparsons suggestions in 
[comment](https://github.com/africanmathsinitiative/R-Instat/pull/6019#discussion_r509993908) and  [comment](https://github.com/africanmathsinitiative/R-Instat/pull/6019#discussion_r509995156)

New R-Instat startup

---

installer/inno_install_script_32bit.iss
installer/inno_install_script_64bit.iss
installer/install_bundled_packages.R

@lloyddewit this has no functional changes to the R-Instat code base, only modifying the installation scripts used to create the installer so I suggest it can be merged after your approval.

updated installation scripts

---

instat/sdgPlots.Designer.vb
instat/sdgPlots.resx
instat/sdgPlots.vb

Fixes #6083 @africanmathsinitiative/developers this is ready for review. 
- Added handles on load subroutine
- Added drop checkbox, aligned controls and sorted Tab order
- Added `drop` argument into facet wrap/grid

Adding drop argument into facet_wrap and facet_grid - Plot options subdialog

---

instat/dlgTaylorDiagram.vb

Fixes #6062. @africanmathsinitiative/developers this is ready for review.

Taylor diagram bug when the same variable is used as group and type

---

instat/dlgExportToWWR.Designer.vb
instat/dlgExportToWWR.resx
instat/dlgExportToWWR.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/instat.vbproj
instat/sdgExportToWWR.Designer.vb
instat/sdgExportToWWR.resx
instat/sdgExportToWWR.vb

Added two blank forms dlgExportToWWR and sdgExportToWWR. This solves issue #6110
@africanmathsinitiative/developers and @rdstern this is ready for review. 
It contains frmmain changes therefore it should be merged as soon as possible.

Adding Export to World Weather Record dialog 

---

instat/dlgSPI.Designer.vb
instat/dlgSPI.resx
instat/dlgSPI.vb
instat/static/InstatObject/R/stand_alone_functions.R

- dialog now allows multiple stations
- wrapper R functions added to organise input and output data
**To test**
- Dialog is for monthly data only
- Data must be in date order (within stations)
- Data can't have any gaps i.e. missing months
The dialog should get sensible errors if any of these are not met.

Updated SPI/SPEI dialog to allow multiple stations

---

instat/dlgClimdexIndices.Designer.vb
instat/dlgClimdexIndices.resx
instat/dlgClimdexIndices.vb
instat/sdgClimdexIndices.Designer.vb
instat/sdgClimdexIndices.resx
instat/sdgClimdexIndices.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R

- added wrapper climdex R functions for multiple stations
- updated dialog to new functions
**Please test:**
- Annual and Monthly options
- With and without multiple stations
- That it works with different kinds of year/month column e.g. numeric or factor
- Running multiple times to see if summaries go in the same sheet (if the same station/year/month columns are used)
- Doing other summaries at the same level before and/or after using the dialog to see if they go in the sheet e.g. Climatic Summaries followed by Climdex

Climdex dialog updated for multiple stations

---

instat/dlgClimaticNCMPCountRecords.Designer.vb
instat/dlgClimaticNCMPCountRecords.resx
instat/dlgClimaticNCMPCountRecords.vb
instat/dlgClimaticNCMPIndices.Designer.vb
instat/dlgClimaticNCMPIndices.resx
instat/dlgClimaticNCMPIndices.vb
instat/dlgClimaticNCMPRegionAverage.Designer.vb
instat/dlgClimaticNCMPRegionAverage.resx
instat/dlgClimaticNCMPRegionAverage.vb
instat/dlgClimaticNCMPSummaryFile.Designer.vb
instat/dlgClimaticNCMPSummaryFile.resx
instat/dlgClimaticNCMPSummaryFile.vb
instat/dlgClimaticNCMPTrendGraphs.Designer.vb
instat/dlgClimaticNCMPTrendGraphs.resx
instat/dlgClimaticNCMPTrendGraphs.vb
instat/dlgClimaticNCMPVariogram.Designer.vb
instat/dlgClimaticNCMPVariogram.resx
instat/dlgClimaticNCMPVariogram.vb
instat/instat.vbproj
instat/sdgClimaticNCMPMetadata.Designer.vb
instat/sdgClimaticNCMPMetadata.resx
instat/sdgClimaticNCMPMetadata.vb

@lloyddewit my apologies - does this also need to be merged before I can make any further changes? It's been a while since I added windows forms, and I forgot that editing the dialog adds a resources file.

NCMP Climatic Dialogs

---

instat/dlgInfillMissingValues.vb

Fixed small bug in design under Climatic>Check Data>Filling missing values. When clicking on Fit Single, the controls were not showing well.
@lloyddewit this is ready to review. Thanks

Missing Values: Fixed small bug un design

---

instat/dlgSplitText.Designer.vb
instat/dlgSplitText.resx

@HawardKetoyoMsatsi
Edited dlgSplitText
Changed  size of position button in ucrSaveColumn control.
This fixes issue #6074
@africanmathsinitiative/developers @rdstern @shadrackkibet this is ready for review.

Dlg trivial change in prepare

---

instat/dlgCumulativeDistribution.vb

Added points option. This solves issue #6111
@africanmathsinitiative/developers and @rdstern this is ready for review. Thanks.

Cumulative/Exceedance Graph: Added points option

---

instat/dlgAddLink.Designer.vb
instat/dlgAddLink.resx
instat/dlgAnonymiseIDColumn.Designer.vb

Fixes #6142
I have made very minor edits in rearranging two dialog designs. The old design is given in #6142 and the new designs are given below:

Dlg designs

---

instat/clsInstatOptions.vb
instat/clsInstatOptionsDefaults.vb
instat/dlgOptions.Designer.vb
instat/dlgOptions.resx
instat/dlgOptions.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Made the structured menu option. This solves issue #6148.
@africanmathsinitiative/developers and @rdstern this is ready to review. Thanks

Making Structured Menu Option

---

instat/sdgDataOptions.Designer.vb
instat/sdgDataOptions.resx
instat/sdgDataOptions.vb
instat/ucrFilter.resx
instat/ucrFilter.vb

Fixes #6085. @africanmathsinitiative/developers this is ready for review.
Notes.
- Changing selector
- Showing numeric keyboard appropriately
- Added remove current filter button

Remove current filter and Add buttons - Data Options

---

instat/frmMain.vb
instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Menu Items Visibility  During Startup

---

instat/instat.vbproj
instat/sdgMergeColumnsToInclude.Designer.vb
instat/sdgMergeColumnsToInclude.resx
instat/sdgMergeColumnsToInclude.vb

Creating a new empty sub-dialog for the Merge dialog as outlined in #6265 
@maxwellfundi @dannyparsons this is ready to merge

Adding new windows form - sub-dialog for the Merge dialog

---

instat/dlgStartofRains.Designer.vb
instat/dlgStartofRains.vb

Fixes #5925 
In this PR, the TestOK is changed after a minor bug was spotted.

Fixing when OK is enabled in the Start of Rains dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx

@maxwellfundi I have created this PR to enable the Climatic>Data Entry menu and avoid conflicts.

Enabled Climatic Data Entry menu

---

instat/dlgImportDataset.vb

Fixing a small bug in the input of the Excel file. This solves issue #6129
@africanmathsinitiative/developers and @rdstern this is ready for review. Thanks.

Small bug fixes in input of Excel file

---

instat/dlgImportDataset.vb

Fixing the issue when setting the missing value code in importing excel file. This solve issue #6192
@africanmathsinitiative/developers and @rdstern this is ready for review. Thanks.

Resolved issue when importing Excel files with missing data values

---

instat/frmMain.Designer.vb
instat/frmMain.resx

@maxwellfundi this is just to rename the Data Entry menu item as suggested by @rdstern in #6250

Renamed the menu item name

---

instat/dlgInfill.Designer.vb
instat/dlgInfill.resx
instat/dlgInfill.vb
instat/static/InstatObject/R/data_object_R6.R

fixes #6327
@rdstern this is not yet ready for the full review. Please do some initial testing just to check that I am on the right path.

Added "Fixed End Limit" and "Fixed Start Limit" options into Fill Date Gaps  dialog

---

instat/dlgLocatingPointsInShapeFile.Designer.vb
instat/dlgLocatingPointsInShapeFile.resx
instat/dlgLocatingPointsInShapeFile.vb

Fixes #5422
@maxwellfundi , @rdstern @dannyparsons @shadrackkibet @lloyddewit  This is ready for review kindly take a look.

Added new dialog for finding points in a polygon

---

instat/dlgTaylorDiagram.Designer.vb
instat/dlgTaylorDiagram.resx
instat/dlgTaylorDiagram.vb

Improved the design of the Taylor Diagram dialog and small changes in the code. This fixes the comments in issues #5885 
@africanmathsinitiative/developers this is ready to review. Thanks.

Improving Taylor Diagram Dialog

---

instat/dlgConditionalQuantilePlot.Designer.vb
instat/dlgConditionalQuantilePlot.resx
instat/dlgConditionalQuantilePlot.vb
instat/static/InstatObject/R/Rsetup.R

@rdstern I have implemented the Conditional Quantile dialog of issue #5974. Could you please check this dialog if it works well? Thanks

Implementing the Conditional Quantile and conditionalEval Options

---

instat/dlgImportERA5Data.Designer.vb
instat/dlgImportERA5Data.resx
instat/dlgImportERA5Data.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/static/InstatObject/R/instat_object_R6.R

fixes #6253
**Current design**

Added Import from CDS (Climate Data Store) dialog

---

instat/dlgClimaticDataEntry.Designer.vb
instat/dlgClimaticDataEntry.resx
instat/dlgClimaticDataEntry.vb
instat/sdgClimaticDataEntry.Designer.vb
instat/sdgClimaticDataEntry.resx
instat/sdgClimaticDataEntry.vb

@Patowhiz this ready. Could you test and proceed with the next? Thanks.

Added facilities in the climatic data entry grid system

---

instat/instat.vbproj
instat/sdgClimaticDataEntryOptions.Designer.vb
instat/sdgClimaticDataEntryOptions.resx
instat/sdgClimaticDataEntryOptions.vb

@lloyddewit this is a new and empty sub dialog for Climatic Data Entry Dialog.
Could you merge this? It doesn't have any code. Thanks.

New Sub Dialog for Climatic Data Entry Dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx

@africanmathsinitiative/developers @lloyddewit this is ready for review.
I have enabled the Wind/Pollution Rose menu. The dialog is ready, kindly merge it quickly so that I can open another PR.

Enabled Wind Rose pollution dialog

---

instat/ucrDataView.Designer.vb
instat/ucrDataView.resx
instat/ucrDataView.vb

This PR fixes "marked" points in issue #6384
- Moved add comment into the main right-click 
- Enable levels/labels only on the factor column

Enhancement of cell right click 

---

instat/dlgAddComment.Designer.vb
instat/dlgAddComment.resx
instat/dlgAddComment.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/ucrColumnMetadata.Designer.vb
instat/ucrColumnMetadata.vb
instat/ucrDataFrameMetadata.Designer.vb
instat/ucrDataFrameMetadata.vb
instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

fixes #6384
@africanmathsinitiative/developers this is ready for review. This feature is also available via right-clicks.

Allow comments to be added to columns and dataframes

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

@lloyddewit this PR adds a menu for Setup Data Entry dialog.

Added menu for Setup data entry dialog

---

instat/dlgImportDataset.vb

Added new options to the Import dialog for importing CSV and text files

---

instat/instat.vbproj
instat/sdgCommentForDataEntry.Designer.vb
instat/sdgCommentForDataEntry.resx
instat/sdgCommentForDataEntry.vb

@lloyddewit @rdstern this an empty sub dialog and requested in #6405. Could you approve? Thanks.

New sub dialog of Comment for Data entry system

---

instat/dlgCompareColumns.Designer.vb
instat/dlgCompareColumns.resx
instat/dlgCompareColumns.vb

Fixes #6393
@africanmathsinitiative/developers @rdstern this is ready for review.

Added option to compare by row in the Compare Columns dialogue

---

instat/dlgClimaticDataEntry.vb
instat/sdgClimaticDataEntry.resx
instat/sdgClimaticDataEntry.vb
instat/sdgClimaticDataEntryOptions.resx
instat/sdgClimaticDataEntryOptions.vb
instat/sdgCommentForDataEntry.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R

fixes  #6394 and fixes #6437
@rdstern this is ready for you to test. Thanks

Adding flag fields on climatic data entry

---

instat/dlgSetupForDataEntry.vb

Fixes #6441
@lloyddewit I have fixed the small bug. Could you test? Thanks.

Small bug fixe in Setup for data entry dialog

---

instat/dlgClimaticDataEntry.vb
instat/dlgEnter.resx

@rdstern @lloyddewit this partially fixes #6454.

Small design fixes in Enter dialog

---

instat/dlgClimaticDataEntry.vb

Fixes #6462
@rdstern @africanmathsinitiative/developers this is ready for review. Thanks.

Bug fixes in grid data entry dialogue

---

instat/ucrButtonsSubdialogue.designer.vb
instat/ucrButtonsSubdialogue.resx
instat/ucrButtonsSubdialogue.vb

Fixes #6490
This PR add the language toggle button to subdialogs.
@africanmathsinitiative/developers  @rdstern this is ready for review. Thanks

Added 'Lan' language toggle button for subdialogs

---

instat/clsRecentFiles.vb

Added a 'More...' option to the file menu and icon toolstrip

---

instat/static/InstatObject/R/Rsetup.R

@africanmathsinitiative/developers this is related to PR #6508 which requires the purrr package
@shadrackkibet  could you review this

Added purrr to the list of packages loaded explicitly on start up

---

instat/dlgPasteNewDataFrame.Designer.vb
instat/dlgPasteNewDataFrame.vb

Fixes #6061
@africanmathsinitiative/developers this is ready for review once PR #6505 is merged

Added Paste New Data Frame dialog

---

instat/dlgOptions.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes issue #6570
Fixes issue #5161 
@rdstern for space issue I suggest adding the Lan button on the toolbar in this PR.

Added toggle button on Tool Bar to switch the main window to/from English

---

instat/clsRLink.vb
instat/dlgAddKey.Designer.vb
instat/dlgAddKey.resx
instat/dlgAddKey.vb
instat/dlgAddLink.Designer.vb
instat/dlgAddLink.resx
instat/dlgAddLink.vb
instat/ucrInput.vb
instat/ucrInputComboBox.vb
instat/ucrSave.vb

This fixes the first point in issue #6349

Added functionality to have key and link names increment after subsequent keys and links saving 

---

instat/dlgCircular.Designer.vb
instat/dlgCopySpecial.resx
instat/dlgCopySpecial.vb
instat/dlgPasteSpecial.Designer.vb
instat/dlgPasteSpecial.resx
instat/dlgPasteSpecial.vb
instat/instat.vbproj

Partly fixes issue #6579
@lloyddewit @rdstern this adds Copy Special and Paste Special dialogs. They have no functionality and therefore nothing to test.
The PR has "Solution" changes there merging it will help avoid conflicts.

Added Copy and paste special empty dialogs

---

instat/dlgOptions.Designer.vb
instat/dlgOptions.resx
instat/dlgOptions.vb

Fixes #6601
@africanmathsinitiative/developers @rdstern @rachelkg this is ready for review. Thanks.

Added Lan button into the Options dialog

---

instat/dlgPivotTable.Designer.vb
instat/dlgPivotTable.resx
instat/dlgPivotTable.vb
instat/instat.vbproj

@africanmathsinitiative/developers  this is adding the Pivot table dialogue

Adding the pivot table dialogue

---

instat/dlgColumnStats.vb
instat/sdgSummaries.Designer.vb
instat/sdgSummaries.resx
instat/sdgSummaries.vb
instat/static/InstatObject/R/Backend_Components/summary_functions.R

fixes #6646
@rdstern here is the addition of sampling into the summary system. Please test.

Added sample as a summary into column statistics dialog

---

instat/dlgCumulativeDistribution.resx
instat/dlgFindNonnumericValues.resx
instat/dlgScatterPlot.resx
instat/dlgTransformClimatic.resx
instat/dlgVisualizeData.Designer.vb
instat/dlgWindrose.Designer.vb
instat/sdgInventoryPlot.resx
instat/sdgPICSARainfallGraph.resx

@lloyddewit @rdstern this PR completes the files removed in PR #6543 due to the conflicts.
@rachelkg could you review this? Thanks.

Improved remained dialog layouts for french translation under climatic menu

---

instat/dlgThreeVariablesModelling.vb

Ensure correct visibility of Convert to Variate check box in the Three variable Modelling dialog

---

instat/dlgHistogram.designer.vb
instat/dlgHistogram.resx
instat/dlgHistogram.vb

@africanmathsinitiative/developers This is ready for review. 
@Cal-Insta @rdstern This will fix the first part of issue #6615, in case we find options to add, that will be done in another PR.

Added Display as Dotplot checkbox to Histogram dialog

---

instat/dlgPivotTable.Designer.vb
instat/dlgPivotTable.resx
instat/dlgPivotTable.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

this fixes  #6634 and specifically for the Describe >Two Variable case.

Added Pivot Table dialog to the Describe> Two Variable menu

---

instat/frmMain.resx

fixes issue #6701 
fixes issue #6713 
@africanmathsinitiative/developers , This is ready for review
@Patowhiz , This is ready for review.
- Corrected Spelling for  Calculate Difference Between Options menu item.
- Corrected Spelling for Corruption Risk Index (CRI) and Define Corruption Risk Index (CRI) menu items

Corrected Spellings in Main form menus

---

instat/ApplicationEvents.vb
instat/dlgImportDataset.vb

@lloyddewit this refactors the import dialog code
@rdstern this requires thorough testing.
Also Fixes #6583.

Refactored the Import dialog and ensure correct reading of multiple SPSS files

---

instat/dlgBarAndPieChart.Designer.vb
instat/dlgBarAndPieChart.resx
instat/dlgBarAndPieChart.vb

Fixes #6726 
@rdstern I have made the first implementation of the lollipop option, please have a look so that we can move further.

Implemented the lollipop option in the Bar Chart dialog

---

instat/dlgScript.Designer.vb
instat/dlgScript.resx
instat/dlgScript.vb
instat/instat.vbproj

Partly fixes issue #5986.
@lloyddewit @shadrackkibet this is just an empty new script dialog. Please merge this to avoid conflicts.

New empty script dialog

---

instat/Pivot Table.Designer.vb
instat/Pivot Table.resx
instat/Pivot Table.vb
instat/instat.vbproj

@lloyddewit  could we have this merged. It's  addition of an empty pivot table form

Adding an empty pivot table dialogue for the three variables

---

instat/dlgDefineCRI.resx
instat/dlgDefineCorruptionOutputs.resx
instat/dlgOneWayFrequencies.resx
instat/dlgRecodeNumericIntoQuantiles.Designer.vb
instat/dlgRownamesOrNumbers.resx
instat/frmMain.resx

Fixes #6660
Fixes #6701 
Fixes #6702 
Fixes #6711 
Fixes #6712 
Fixes #6713 
Improved English text in multiple dialogs, and ensured that the updated English text is in the translations database (otherwise it won't display correctly in English or translate correctly to other languages).

Improved English text in multiple dialogs

---

instat/dlgGeneralForGraphics.Designer.vb
instat/dlgGeneralForGraphics.resx
instat/dlgGeneralForGraphics.vb
instat/sdgPlots.resx
instat/sdgPlots.vb

Fixes #6633
@rdstern please have a look. Thanks.

Improved usability of the General Graphics dialog

---

instat/dlgPivotTable.Designer.vb
instat/dlgPivotTable.resx
instat/dlgPivotTable.vb

@mmulahvictor and I fixed this issues.
This fixes the improvement issues: row variable be changed to multiple receiver and OK be enabled in the dialogue without having to input either the rows or columns raised on #6634 
@rdstern could you have a look at it

Allow multiple row factors in Pivot Table dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Partly fixes issue #5986.
This PR adds a new menu item under the edit in the main form.
@shadrackkibet @lloyddewit please merge this so that @rdstern can test PR #6752.

Script dialog menu item

---

instat/sdgPlots.resx

I noticed that the xtab had a layout issue whereby not all the text was visible so I extended the surrounding box to resolve this. 
Thanks, 
Rachel

Small fix to the layout of the xtab in the Plot options dialog

---

instat/dlgCalculateTreatmentDifferences.resx
instat/dlgColumnStats.resx
instat/dlgCountryColouredMap.resx
instat/dlgDeleteRowsOrColums.resx
instat/dlgFindNonnumericValues.resx
instat/dlgModelling.Designer.vb
instat/dlgModelling.resx
instat/dlgRandomSample.resx
instat/frmMain.resx

Fixes #6710
@africanmathsinitiative/developers , This is ready for review
@rachelkg  , I have made all the changes listed on the [Inconsistencies between Menu and Dialog names.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7156493/Inconsistencies.between.Menu.and.Dialog.names.xlsx)
@lloyddewit , Please review the changes I have made on this new PR.

Making the Menu names and Dialog names Consistent

---

instat/frmMain.Designer.vb
instat/frmMain.resx

Hello @shadrackkibet I have changed the name Specific to Specific Tables/Graphs in the form main. You can have a look at it.

Changed the name Specific to Specific Tables/Graphs in the main menu

---

instat/dlgRugPlot.Designer.vb
instat/dlgRugPlot.resx
instat/dlgRugPlot.vb

@africanmathsinitiative/developers @rdstern @shadrackkibet @fran2or 

Added shape receiver to the heat map dialogue

---

instat/dlgRownamesOrNumbers.Designer.vb
instat/dlgRownamesOrNumbers.resx
instat/dlgRownamesOrNumbers.vb

Fixes issue #6684 
@africanmathsinitiative/developers , this is ready for review
The saving control was set as a text instead of a combo. I have fixed the issue and resized the dialog.
@rdstern , @Patowhiz , This is ready for review

Adjusted the position button, changed save control into a drop down and prefix of the new column in copy Row names dialog

---

instat/dlgBarAndPieChart.Designer.vb
instat/dlgBarAndPieChart.resx
instat/dlgBarAndPieChart.vb

Fixes #6582
@rdstern please have a look. Thanks.

Added reorder feature and minor bug fixes to the bar chart dialogue

---

instat/clsRLink.vb
instat/dlgSelect.Designer.vb
instat/dlgSelect.vb
instat/dlgSelectColumns.Designer.vb
instat/dlgSelectColumns.resx
instat/dlgSelectColumns.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/labels_and_defaults.R
instat/ucrInput.vb
instat/ucrInputComboBox.vb
instat/ucrReceiver.vb

fixes #6426
This is not yet ready for review. I will send a notification when it is ready. 
Design screenshots below.

Added selection of columns functionality

---

instat/dlgRecodeFactor.Designer.vb
instat/dlgRecodeFactor.resx
instat/dlgRecodeFactor.vb

Improved the Recode Factor Levels dialog in differents way with forcats functions

---

instat/instat.vbproj
instat/sdgConstructRegexExpression.Designer.vb
instat/sdgConstructRegexExpression.resx
instat/sdgConstructRegexExpression.vb

@shadrackkibet this is needed from #6893. Could this be merged then after pass to the implementation? Thanks.

New sub dialog for Regex expression

---

instat/dlgBarAndPieChart.Designer.vb
instat/dlgBarAndPieChart.resx
instat/dlgBarAndPieChart.vb

@rdstern @shadrackkibet I have added the Treemaps and Wordcloud in the Bar chart dialog you can have a look at it.

Added Treemap and Wordcloud in the Bar chart dialog

---

instat/Model/DataFrame/clsDataFramePage.vb
instat/ucrDataView.vb

Add Has Changed flag to dataframe page to stop unnecessary gird refresh.

Improved speed issues

---

instat/Model/DataFrame/clsDataFrame.vb
instat/Model/DataFrame/clsDataFramePage.vb
instat/ucrDataView.vb

Add refresh and made sure Dataframe page knows current total from filter and resets paging if needed

fixes 6907 Updated refresh of info on refresh

---

instat/ucrColumnMetadata.Designer.vb
instat/ucrDataFrameMetadata.Designer.vb
instat/ucrDataView.Designer.vb

fixes #6922 
@ChrisMarsh82 @shadrackkibet @rdstern @africanmathsinitiative/developers Could you check that this fixes the tab size issue (if it was an issue on your machines) and also that it doesn't change the sizing of anything else incorrectly?

fixed sizing of windows caused by DPI scaling

---

instat/static/InstatObject/R/instat_object_R6.R
instat/ucrColumnMetadata.vb

fixes refreshing issue on delete

---

instat/ucrDataView.vb

fixes accidental change noticed here https://github.com/africanmathsinitiative/R-Instat/pull/6925#issuecomment-966647599
The grid info now refreshes correctly.

added back display info refresh

---

instat/dlgSpells.Designer.vb
instat/dlgSpells.vb

Fixes #5575
I have made the improvement of the Spells Dialogue as requested in the corresponding issue. It doesn't yet with the Filter and it seems to be a general issue with calculations.
@africanmathsinitiative/developers @rdstern this is ready for review.

Improved the Spells Dialogue following ICPAC Dialogue

---

instat/frmMain.Designer.vb
instat/frmMain.resx

@dannyparsons these are just minor changes in the frmmain and translation db as suggested in #6934

Name changes in the translation db and frmmain

---

installer/Installer_Generation_Guide.md
installer/inno_install_script_32bit.iss
installer/inno_install_script_64bit.iss

@ChrisMarsh82 I think the guide is quite complete now. It would be good to discuss it at some point and discuss automations as well.

updated installer scripts and installer generation guide

---

instat/static/InstatObject/R/instat_object_R6.R

this solves part c) from #6947
@shadrackkibet @N-thony @Ivanluv Could you confirm this fixes the bug with reopening newly saved files?

fixes bug importing saved files

---

instat/dlgClimaticCheckDataRain.Designer.vb
instat/dlgClimaticCheckDataRain.resx
instat/dlgClimaticCheckDataRain.vb

Fixes #6951
@rdstern @africanmathsinitiative/developers this is ready for review. Thanks.
It allows the Element receiver to receive another type of variable if not rain variable.

Bug fixed on the Element receiver under Climatic Check Data Rainfall

---

instat/dlgSPI.vb

Bug fixed when the Filter is applied in Climatic>Prepare>SPI/SPEI dialog

---

instat/dlgFromLibrary.vb

Fixes #6969
@rdstern this fixes the bug that was appearing when trying to load the data library especially in the case described in the corresponding issue. Could you take a look? Thanks.

Bug fixed when reading data sets from library

---

instat/dlgClimaticCheckDataTemperature.Designer.vb
instat/dlgClimaticCheckDataTemperature.resx
instat/dlgClimaticCheckDataTemperature.vb

Fixes #6971
@africanmathsinitiative/developers  @rdstern I made a small improvement as suggested in the corresponding issue apart from the tooltip on the Multiple radio button that seems to not work yet since the control is disabled. Please take a look. Thanks.

Changed the increment in the acceptable range controls in the Climatic Check Data Temperature dialog (plus other small enhancements)

---

instat/dlgSplitText.Designer.vb
instat/dlgSplitText.resx
instat/dlgSplitText.vb

Corrected and improved the Prepare > Column: Text > Split dialog

---

instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Fixes #7017 
@africanmathsinitiative/developers this is ready for review. Thanks

Small fixes on opening the dataset from DataView Window and setted the activated links color under Start and Help consistent to the Recent

---

instat/dlgScript.Designer.vb
instat/dlgScript.vb
instat/frmMain.resx

This PR replaces PR #6752. It includes the latest frmMain changes and enables the new Edit/Script menu option.

Added Script dialog

---

instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb

The issue is with updating grids when the column is selected.

Fixes #7043 Added clear selection before adding columns as causes issue on linux

---

instat/dlgClimaticCheckDataRain.vb

Fixes #7050 
@africanmathsinitiative/developers  @rdstern I have made a small change in the OK condition so that it will be enabled if at least one checkbox is checked. please take a look. Thanks

Corrected the OK condition in Climatic > Check Data > QC Rainfall dialog

---

instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Fixes #7008 
@africanmathsinitiative/developers @ChrisMarsh82 @dannyparsons this is ready for review. Thanks.

Dynamically resize info text in Data View

---

instat/UserControl/ucrOutputPages.Designer.vb
instat/UserControl/ucrOutputPages.vb

fixes #7005
Suggest not merging until #7072 is merged.

Rename Main output window tab

---

instat/Model/Output/clsOutputLogger.vb

_output was not being populated with anything other than scripts

Added all outputs to _output list to fix commit

---

instat/Model/Output/clsOutputElement.vb
instat/UserControl/ucrOutputPage.vb

Fixes #7015 
@dannyparsons @ChrisMarsh82  I have tried to fix the bug on the InventoryPlot, please take a look.

Fixed bug on Climatic > Inventory Plot dialog

---

instat/ucrTry.vb

Corrected typo identified by @shadrackkibet in PR #7051.
@rdstern @shadrackkibet Please could you approve/merge? thanks

Corrected typo identified by @shadrackkibet in PR #7051

---

instat/static/InstatObject/R/Backend_Components/summary_functions.R

@rdstern @Ivanluv @dannyparsons this should fix the ordering issue outlined in the email from @rdstern 
@rdstern @Ivanluv - can you check this sorts the problem?

Fixing order of labels in the summary tables R code

---

instat/clsRecentFiles.vb
instat/dlgCompareModels.Designer.vb
instat/dlgExportToCPT.vb
instat/dlgImportDataset.vb
instat/dlgOpenNetCDF.vb
instat/dlgRandomSample.designer.vb
instat/dlgSaveAs.Designer.vb
instat/dlgSaveAs.resx
instat/dlgSaveAs.vb
instat/dlgShowModel.Designer.vb
instat/frmMain.vb
instat/sdgAddNewDistribution.Designer.vb
instat/ucrDataView.vb
instat/ucrFilePath.Designer.vb

@africanmathsinitiative/developers This is ready for review. This should not have any changes to the Windows version. Please just confirm that open from file/library still works, also from Open NetCDF and paths are set correctly.

updated paths to use / instead of \ in some places for Linux version

---

instat/dlgExportDataset.Designer.vb
instat/dlgExportDataset.resx
instat/dlgExportGraphAsImage.Designer.vb
instat/dlgExportGraphAsImage.resx
instat/dlgExportRObjects.Designer.vb
instat/dlgExportRObjects.resx
instat/dlgExportRWorkspace.Designer.vb
instat/dlgExportRWorkspace.resx
instat/ucrFilePath.Designer.vb

@africanmathsinitiative/developers Please check the Export dialogs are now the correct size. In the current version they are too large.

Fixed export dialog sizes

---

instat/translations/translateIgnore.txt
instat/translations/translationsManuallyEntered.csv

Partially fixes #6185, #6989
@lloyddewit this PR contains the updated database as suggested on PRs #6956, #7058, and #7062 due to the conflicts. Please take a look. Thanks

Updated database from PRs 6956, 7058 and 7062

---

instat/dlgSplitText.Designer.vb
instat/dlgSplitText.vb
instat/dlgStringHandling.Designer.vb
instat/dlgStringHandling.vb
instat/sdgConstructRegexExpression.Designer.vb
instat/sdgConstructRegexExpression.resx
instat/sdgConstructRegexExpression.vb

Fixes (partially) #6893
@africanmathsinitiative/developers @rdstern this replaces PR #7062 due to the build errors. Please take a look.

 Implemented the regex sub dialog under Prepare > Column:Text > Find/Replace Dialogue

---

instat/frmMain.vb
instat/ucrDataView.vb

Fixes #7102 
@dannyparsons this PR fixed the small bug related to the corresponding issue. Please take a look. Thanks.

Fixed the message to not appear when no data is loaded

---

instat/dlgMerge.Designer.vb
instat/dlgPermuteColumn.Designer.vb
instat/dlgStringHandling.Designer.vb
instat/frmMain.Designer.vb

Fixes #6904
@lloyddewit thanks for the quick call. As discussed I have updated the database and changed the dialogue text as requested in the corresponding issue from `Merge` to `Merge (Join)`. I have at the same time clearly demonstrated to @EstherNjeriLiberatta how to make such a change in the database and the required tool which `DB Browser for SQLite` for manipulating our database. This PR replaces PR #7108. Please take a look.

Updated the Prepare>Data Reshape>Merge title to Merge (Join)

---

instat/dlgClimdexIndices.Designer.vb

fixes #7092 
This PR was made to correct the previous PR #7094 
@N-thony can you please test this one .

fixes small issue with labelling in the Climdex dialogue

---

instat/dlgRegularSequence.designer.vb
instat/dlgRegularSequence.vb

fixes #6672 from the previous PR #7071 
moved the preview up in the dialogue to allow room for the Position button and also fixes issue with some controls
resetting back to the original default

Resolved issues with layout of the Regular Sequence Dialog

---

instat/sdgClimaticDataEntry.Designer.vb

fixes issues #7134 
Small issue with design bug in the climatic data Entry sub dialogue
Climatic > Tidy and Examine > Daily data Entry > sub dialogue

Fixed button position issue in the Climatic Data Entry subdialog

---

instat/static/InstatObject/R/data_object_R6.R

Fixes #7027 
@dannyparsons please take a look. Thanks

Returning the quarter abbr as factor on the Use Date Dialogue 

---

instat/dlgNewDataFrame.Designer.vb
instat/dlgNewDataFrame.vb

Changed default on File > New Data Frame

---

instat/dlgImportDataset.Designer.vb

Fixes #7112
@africanmathsinitiative/developers , This is ready for review.
@dannyparsons , I have set the Auto-size to false as you advised. Kindly review. Thank you.

Corrected the Import Dialog Auto-size setting

---

instat/dlgImportDataset.vb

Fixes #7164 
@rdstern sorry for the delay. I have made a small change that fixes the problem raised in the corresponding issue. Please could you test it? Thanks. Then I will have a look at loading the multiple files with a given extension within subfolders.

Improved Import from Library for Instat files

---

installer/Installer_Generation_Guide.md
installer/inno_install_script_32bit.iss
installer/inno_install_script_64bit.iss

@lloyddewit This only updates the scripts to produce the releases and the markdown documentation, and no software functionality, so merging without review

updated installation scripts and guide

---

instat/frmMain.Designer.vb
instat/frmMain.vb

Partial fixes issue #7196 and #5991.
@africanmathsinitiative/developers this is ready for review. 
@lloyddewit @shadrackkibet this just has changes to menu item label and dialog call. @rdstern will need this merged for testing PR #7224.
Thanks.

Added main form copy paste menus

---

instat/Model/DataFrame/clsDataFrame.vb
instat/Model/DataFrame/clsDataFrameFilter.vb
instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/ucrColumnMetadata.vb
instat/ucrDataView.vb
instat/ucrSave.vb

@shadrackkibet I have pushed the wrong branch in #7256, here is the change requested. Thanks.

Changed variable text colour when columns selection is applied

---

instat/dlgRandomSplit.Designer.vb
instat/dlgRandomSplit.resx
instat/dlgRandomSplit.vb
instat/instat.vbproj

This is a new empty Random Split dialog.
@africanmathsinitiative/developers 

New Random Split dialog

---

instat/dlgClimaticDataEntry.Designer.vb
instat/dlgClimaticDataEntry.vb
instat/frmMain.Designer.vb

Fixes (partially) #7279
@rdstern  I have solved items a) b) and c) as requested in the corresponding issue. Please take a look.

Corrected and fixed the oddity in the Climatic Data Entry Dialogue

---

instat/ucrColumnMetadata.Designer.vb
instat/ucrColumnMetadata.vb
instat/ucrDataView.Designer.vb
instat/ucrDataView.vb
instat/ucrScript.Designer.vb
instat/ucrScript.vb
instat/ucrSelector.designer.vb
instat/ucrSelector.vb

Added Help to each right-click menu and also to the script window

---

instat/UcrGeomListWithAes.designer.vb
instat/ucrLayerParameters.Designer.vb
instat/ucrLayerParamsControls.Designer.vb
instat/ucrReceiverMetadataProperty.Designer.vb

fixes #7296
@rdstern Can you check the sizing and visibility is fixed? It looks ok on my machine now.
I had to make the nud control wider, but I think it looks ok still. See what you think.
The sizing is not quite perfect but I think it's not very noticeable and all controls are non-overlapping and visible.

fixes sizing of geom list with aes

---

instat/dlgRecodeFactor.vb
instat/ucrFactor.vb

Fixes #7275 
@rdstern @shadrackkibet  as discussded on skype I have added the delete of labels to the new recoded column factor, please take a look. Thanks.

Added delete labels to the new recoded factor column in Recode Factor Dialogue

---

instat/dlgFindNonnumericValues.vb

Fixes #7310 
I made the correction of the R code as provided in the corresponding issue.

Corrected the error on the check values type in Non Numeric Dialogue

---

instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
instat/frmConvertToNumeric.Designer.vb
instat/frmConvertToNumeric.resx
instat/frmConvertToNumeric.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R
instat/ucrDataView.vb

Fixes #7293
I have added the checking when nothing is a numeric in the column to convert to numeric and also changed `Labelled Convert` to `Ordinal Convert`

Corrected the convert in Numeric Popup dialog

---

instat/dlgClimaticCheckDataTemperature.vb

Fixes #7331 
@rdstern @shadrackkibet , this PR makes tmax and tmin to use the limits specified at the bottom and at the top

Fixing limits issue in Temperature Quality Control dialog

---

instat/dlgMergeAdditionalData.Designer.vb
instat/dlgMergeAdditionalData.vb

Fixes #7029
This PR replaces PR #7333 due to the conflicts.
@rdstern I made the changes here from your review in PR #7333, please take a look. Thanks.#7123 

Improved Options by Context > Prepare > Merge Additional Data dialog

---

instat/static/InstatObject/R/data_object_R6.R

Enabled importing of data frames with duplicate column names

---

instat/frmMain.vb
instat/ucrSelector.vb

Fixed refreshing of Selector control when new column added

---

instat/dlgCalculator.vb
instat/dlgTransform.vb

Fixes (partially) #7274 
@rdstern @shadrackkibet could you test? Thanks.

Deleting labels in the new column created in Calculator and Transform Dialogues

---

instat/dlgRenameDataFrame.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R

Fixes #7350 
@rdstern @N-thony , this PR adds the  original label to dataframe when it exists

In Prepare > Data Object > Rename Data Frame dialog, if original label exists, then include it

---

instat/dlgTransformText.Designer.vb
instat/dlgTransformText.vb

fixes #7398 
@rdstern @lilyclements 
This is ready for review

Minor Changes to Column:Text > Transform Dialogue

---

instat/dlgNewDataFrame.Designer.vb
instat/dlgNewDataFrame.vb

Fixes (partially) #7387 
@rdstern I have added the Sequence data type as suggested in the corresponding issue, please take a look.

In File > New Dataframe, added the Sequence data type to the new dataframe grid

---

instat/static/InstatObject/R/install_packages.R

Adding in `skimr` package after #7343
@rdstern @lloyddewit are there any other packages we want to add in for the release?
If not, this is ready for review.

Added R `skimr` package

---

instat/Model/DataFrame/clsColumnMetaData.vb
instat/ucrSelector.vb

Fixes #7421
@africanmathsinitiative/developers @anastasia-mbithe this is ready for review.

Fixes updating of the selector when the columns metadata changes

---

instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/labels_and_defaults.R

Fixes (partially) #7339
@rdstern I did items 1) 2) and 3) the remaining items 4) and 5) are a bit tricky to implements, probably in another PR. Please take a look.

Reordered columns on the DataFrame Metadata grid

---

instat/static/InstatObject/R/install_packages.R

As requested by @dannyparsons in #7429
@lloyddewit @rdstern this is ready for you. I have only added a comment so there are no functionality changes here.

Adding skimr description in install_packages.R

---

instat/frmMain.Designer.vb
instat/frmMain.vb

I have added the new Random Split dialog to the form main.
This PR is replacing #7376 
@shadrackkibet and @lloyddewit can you merge this for @rdstern to review PR https://github.com/africanmathsinitiative/R-Instat/pull/7272.

Adding the random split dialog to form main

---

instat/dlgClimaticBoxPlot.Designer.vb
instat/dlgClimaticBoxPlot.vb

Fixes  #7485 
@N-thony @rdstern @africanmathsinitiative/developers This is ready for review.

Fixes Climatic Boxplot Dialogue 

---

instat/dlgSaveAs.vb
instat/frmMain.vb

Fixes #7475
@lloyddewit as discussed this bug was due to the fact the check when closing the databook was not done correctly, please take a look.

Bug fixed: File > Close Data Book

---

instat/static/InstatObject/R/Backend_Components/summary_functions.R

In Summary Tables dialog, prevent error message triggered by invalid R code

---

instat/static/InstatObject/R/stand_alone_functions.R

Fixed grid row sizes for shape file data frames

---

instat/dlgViewLabelsAndLevels.vb

Removed the Data Type restriction for the  Prepare > Check Data > View/Delete Labels dialog

---

instat/ucrDataView.vb

@lloyddewit this fix the bug that I have reported in issue #7526, please have a look.

Minor bug fix in column metadata with Linux

---

instat/dlgClimaticStationMaps.Designer.vb
instat/dlgClimaticStationMaps.vb

Fixes #7528 
This is not ready for review.

Added Point and Label options to the drop down menu in the Mapping dialog 

---

instat/ucrSelectorByDataFrameAddRemove.Designer.vb
instat/ucrSelectorByDataFrameAddRemove.resx
instat/ucrSelectorByDataFrameAddRemove.vb

Added menu items under the selector add button

---

instat/dlgScatterPlot.vb

Fixes #7507 
@rdstern @N-thony @lloyddewit , this PR re-orders the code by Setting initial values for the controls in `InitialiseDialog()` sub and setting defaults for the function  in `SetDefaults()` sub

Re-ordered codes in Scatter plot dialog to follow the normal system

---

instat/dlgPICSARainfall.vb

Fixes issue #7534 
This PR is ready for Review. 
@lilyclements , @N-thony  could test and confirm also

Fixed plotting bug on PICSA Rainfall Graph dialog

---

instat/dlgReorderDataFrame.vb
instat/frmMain.vb
instat/ucrColumnMetadata.vb
instat/ucrDataView.vb

Fixes (partially) #7550
@rdstern I have made the change here that fixes the bug you are facing in the workshop, this will allow the reordering only when we do it. Please test it.
@lloyddewit please have a look.

Fixed bug related to reordering of data frame tabs in Data View

---

instat/dlgRatingScales.Designer.vb
instat/dlgRatingScales.vb

Fixes #7608 
This is still in progress, I have implemented parts (a) and (b).

Improved the Describe > One Variable >Rating Data dialog

---

instat/frmMain.Designer.vb

Changes on View Menu

---

instat/dlgCalculator.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.vb

Fixes #7565 
@rdstern, I have added the nth_prime key and the prime key that generates primes with n= nrows(dataframe).
Kindly have a look at it. You can suggest other keys to add from the primes package.

Added prime keys to the Calculator dialog

---

instat/dlgConditionalQuantilePlot.Designer.vb

Fixes #7663 
@N-thony , this PR is ready for review

Removing unwanted base space in Conditional Quantile Plot dialog

---

instat/ucrDataFrameMetadata.vb

Fixes #7568 
@N-thony can you test

Ensured that dataframe can be renamed in Data Frame MetaData Grid

---

instat/dlgPICSARainfall.Designer.vb
instat/sdgPICSARainfallGraph.Designer.vb
instat/sdgPICSARainfallGraph.vb
instat/sdgPlots.Designer.vb

I made a few small changes to make French text visible.

Layout updates to PICSA menu

---

instat/dlgMosaicPlot.Designer.vb
instat/dlgMosaicPlot.resx
instat/dlgMosaicPlot.vb

Fixes (partially) #7556,
Modifying the plot option control in Mosaic Options
@N-thony , this PR is ready for review

Modified the plot options in Mosaic Plot dialog

---

instat/dlgSelectColumns.Designer.vb
instat/dlgSelectColumns.vb

Replaces #7723 
@lloyddewit please have a look.

Minor bug fix and design adjustment in Select Columns Dialog

---

instat/dlgEndOfRainsSeason.vb

Fixes #7690 
@N-thony , this PR is ready for review

In End of Rains Season dialog, increased capacity default from 1 to 100

---

instat/dlgImportShapeFiles.Designer.vb

Fixes #7633
@N-thony, I have made the changes requested

Minor adjustments on the ucrImput text Dataframe name control

---

instat/ucrAxes.Designer.vb

I made minor layout changes to the Axis tab to account for the french text.

Layout update to Plot Options sub dialog of PICSA rainfall graphs

---

instat/dlgOptions.vb

Added Russian language option and merged Russian translations in CrowdIn PR #7756 into database.
Please note that:
- These are currently machine translations and have not been reviewed
- The menus and dialogs have not been tested in Russian, there may be positional and other problems
@rdstern Normally, I would not want to merge beta functionality into master. However, if we don't merge this PR very soon, then it will cause a merge conflict the next time we want to update the database. Also, this PR only affects users who specifically change the language option to Russian.
If you agree, then please could you do a sanity check and approve?
Thanks!

Added Russian language option (beta)

---

instat/dlgRestrict.vb

In the  Prepare > DataFrame > Filter Row dialog, ensured that filter is updated when a dataset is deleted and reopened

---

instat/DlgDefineClimaticData.Designer.vb
instat/dlgAppend.Designer.vb
instat/dlgClimaticCheckDataRain.Designer.vb
instat/dlgConversions.Designer.vb
instat/dlgExportToCPT.Designer.vb
instat/dlgInventoryPlot.designer.vb
instat/dlgOneWayFrequencies.Designer.vb
instat/dlgStack.Designer.vb
instat/sdgSaveColumnPosition.Designer.vb

@rdstern please could you check this. it is the issues you pointed out in issue #7792

Adjusted layout of Climatic menu dialogs to allow longer French text

---

instat/dlgClimaticCheckDataTemperature.vb

Fixes #7662 
This PR is ready for Review
@N-thony, could you test this

Ensured that 'Difference' checkbox has persistent state in Climatic > Check Data > QC Temperature dialog

---

instat/ucrCalculator.vb

Fixes #7819 and  Fixes #7800 also.
@rdstern, This is ready for review.

Improved the Probability and Integer keyboards in the Calculator

---

instat/dlgOneWayFrequencies.Designer.vb

Fixes #7795
@lloyddewit this is just a small improvement, please take look and probably merge. Thanks.

Minor design change in the Frequency dialog

---

instat/dlgClimaticCheckDataTemperature.vb

Fixes #7759 
@lloyddewit I made a small code change so that text of checkbox will match the one in the database for Days and Jump checkboxes.

Minor code change in QC Temperature Dialogue

---

instat/Model/DataFrame/clsDataFramePage.vb

Fixes (partially) #7493
@rdstern please have a look. Thanks.

Added date time and time data types to column headers

---

instat/ucrFilter.Designer.vb
instat/ucrFilter.vb

Fixes #7752
@lloyddewit please take a look.

Minor code and design changes in Filter Dialogue

---

instat/frmConvertToNumeric.Designer.vb
instat/frmConvertToNumeric.vb

Fixes (partially) #7742
@lloyddewit there one signle label that contians this small paragraph with the three options of conversion, so we need to add this paragraph in the Json file

Minor code and design changes in Convert To Numeric Dailogue

---

instat/sdgDataOptions.Designer.vb

Fixes #7683
@lloyddewit this PR replaces PR #7847, could we merge it quickly since it has database changes? Thanks.

Update database for translation

---

instat/dlgClimaticSummary.Designer.vb
instat/sdgSummaries.Designer.vb

Fixes #7758 
@N-thony , @MeSophie this PR is ready for review
Thanks

Climatic translation fixes

---

instat/frmMain.Designer.vb

Fixes #7866.
@N-thony Please have a look.

Hid 'Paste New Columns' and 'Copy Special' options in Edit Menu

---

instat/instat.vbproj
instat/sdgWindowNumber.Designer.vb
instat/sdgWindowNumber.resx
instat/sdgWindowNumber.vb

@lloyddewit this PR contains an empty sub dialogue needed in issue #7630, could we merge it quickly? Thanks.

Added an empty new Window Number subdialog

---

instat/dlgOptions.vb

This is a machine translation, the translations still need to be reviewed.
@rdstern If you can test/approve, then we can merge, thanks

Added Spanish language option

---

instat/Model/DataFrame/clsDataFramePage.vb

Fixes (partially) #7493
@rdstern please have a look. Thanks

Made variables of class bigz or bigq to type S in the data view

---

instat/ucrCalculator.vb

Improved Wakefield keyboard in the Calculator dialog

---

instat/ucrScript.vb

**Automatic indentation**
In the Script window, if the user presses the Enter key, then automatically sets the indent of the new line. Normally the indent is set to the same indent as the last previous non-empty line. However, if the caret was between '{}' when enter was pressed, then increases the indent by 2 spaces and moves the '}' to the next line. This results in code with nested indents. Please see example below. 
**Code folding**
In the margin, displays '+' and '-' buttons for each (nested) block. If the user clicks '-' then it collapses the block. If the user clicks '+', then it expands the block.
This will be useful if/when users display longer scripts in the Script window. I added it now because it was easy to do so while working on the indentation.
@N-thony Please could you …

Added automatic indentation and code folding to the Script window

---

instat/dlgWordwrap.Designer.vb
instat/dlgWordwrap.resx
instat/dlgWordwrap.vb
instat/frmMain.Designer.vb
instat/frmMain.vb
instat/instat.vbproj

@N-thony and @lloyddewit  can you have a look at this

Adding Window Forms for Wordwrap dialog

---

instat/dlgOptionsByContextBoxplot.Designer.vb
instat/dlgOptionsByContextBoxplot.resx
instat/dlgOptionsByContextBoxplot.vb

Fixes (partially) #7556, 
modifying the Plot option control in OptionsBycontext>Boxplot

Improved plot options in Options by Context dialog

---

instat/static/InstatObject/R/install_packages.R

@lloyddewit @ChrisMarsh82  This PR replaces PR #7934, please have a look. Thanks.

Added missing packages (coin, pingr,  and vcdExtra)

---

instat/dlgColumnStats.vb
instat/dlgDescribeTwoVariable.Designer.vb
instat/dlgDescribeTwoVariable.vb
instat/dlgOneVariableSummarise.Designer.vb
instat/dlgOneVariableSummarise.vb
instat/dlgSummaryTables.Designer.vb
instat/dlgSummaryTables.vb

Fixes #7917 
Added Options subdialog to Describe > Two variables dialog, Describe > Specific Tables and graphs> Frequency/summary dialog and Prepare > Data Reshape > Column Summaries dialog.
@N-thony, have a look at this and test it as well.

Added Options subdialog to Two variables, Frequency/summary and Column Summaries dialogs

---

instat/dlgLinePlot.designer.vb
instat/dlgLinePlot.vb

Fixes (partially) #7650 
fixes translation layout in french
Describe>Specific Tables/Graphs>Line/Smooth/Dumbbell/Slope plot....
@N-thony , @rdstern , this PR is ready for review

Fixed Line Plot dialog translation layout

---

instat/dlgSearch.Designer.vb
instat/dlgSearch.resx
instat/dlgSearch.vb
instat/frmMain.Designer.vb
instat/frmMain.vb
instat/instat.vbproj

partially fixes #7950 
@africanmathsinitiative/developers this is ready for review. This is an empty Search dialog which should be merged so that I may progress with it.
- create the search dialog
- added the search dialog to form Main

Create empty Search dialog

---

instat/dlgThreeVariableFrequencies.vb
instat/dlgThreeVariablePivotTable.vb
instat/sdgMissingOptions.vb

Fixes (partially) #7911
@rdstern this is ready for review, please have a look. Thanks.

Updated the help ids

---

instat/dlgMergeAdditionalData.vb
instat/static/InstatObject/R/instat_object_R6.R

Fixes (partially) #7777
@lloyddewit @rdstern this fixes part b) of the corresponding issue

Fixed small bugs in Add Prepare > Data Frame > Add (Merge) Data dialog

---

instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb

fixes partly #7956 and #7273
@N-thony and @rdstern  this PR is ready for review

Implemented Tab and arrow keys in Data grid

---

instat/dlgStack.Designer.vb
instat/dlgStack.vb

Fixes #7941 
@rdstern , @N-thony @lloyddewit , the button converts a frequency table to a data frame representing individual observations in the table. I have convert the dataframe generated from characters to factors .

Added Expand button to the Stack dialog

---

instat/clsRCodeStructure.vb
instat/clsRLink.vb
instat/dlgExtremes.vb
instat/dlgFitModel.vb
instat/dlgOneVarFitModel.vb
instat/dlgOneVariableSummarise.vb
instat/dlgRandomSample.designer.vb
instat/dlgRandomSample.vb
instat/dlgShowModel.vb
instat/dlgThreeVariableFrequencies.vb
instat/dlgThreeVariablesModelling.vb
instat/dlgTwoVariableFitModel.vb
instat/dlgTwoWayFrequencies.vb
instat/frmMain.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R
instat/ucrButtons.vb

Fixes some items in issue #7852

Refactors model dialogs to use the new output system

---

instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

fixes #8031 
this PR is ready for review
I also added the `ContextMenuStrip` for the `List keyboard` (see above) so that it can be added when the keyboard is ready

Included the new R Help button on all calculator keyboards

---

instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb

Fixes bug remaining in PR #8015 .
@rdstern could you test this?

Minor bug fix of display of list variables from PR #8015

---

instat/dlgRegularSequence.vb

Fixes #8051
@rdstern @berylwaswa please take a look.

Fixed small bugs in the Regular Sequence dialog

---

instat/dlgOptions.vb

Added Italian and merged in all CrowdIn updates from PR #8061.

Added Italian language option (beta)

---

instat/dlgName.vb

Fixes #7938 
This PR is fixes the bug on Prepare > Data Frame > Rename Column  
This PR  is ready for Review.

Fixed bug renaming columns in bug on Prepare > Data Frame > Rename

---

instat/dlgOptions.Designer.vb
instat/dlgOptions.vb
instat/frmMain.Designer.vb

Added version number to main form
Added version number including revision to options dialog

Updated version number display

---

instat/dlgLinePlot.designer.vb
instat/dlgLinePlot.resx
instat/dlgLinePlot.vb

fixes (partly) #7556
replaces PR #7814
@rdstern  this PR is ready for review

Implemented plot options in Line Plot dialog

---

instat/dlgThreeVariableFrequencies.vb

fixes partly #8104 
@lloyddewit, @berylwaswa  This PR is ready for review.

Ensured Three-way Frequency dialog output is correct

---

instat/static/InstatObject/R/InstallPackages.R
instat/static/InstatObject/R/install_packages.R

Fixes #8109 
@ChrisMarsh82  this PR is ready for review

Added R packages 'primes' and 'Zseq' 

---

instat/dlgBarAndPieChart.Designer.vb
instat/dlgBarAndPieChart.resx
instat/dlgBarAndPieChart.vb

fixes partly #7556 
Replace #7810 
@N-thony , @rdstern this PR is ready for review

Added Plot Options to Bar and Pie Chart dialog

---

instat/dlgFindInVariableOrFilter.Designer.vb
instat/dlgFindInVariableOrFilter.resx
instat/dlgFindInVariableOrFilter.vb
instat/instat.vbproj

@lloyddewit this PR contains an empty dialogue required in issue #7950

Empty dialogue for issue 7950

---

instat/NLog.config
instat/clsRLink.vb
instat/frmMain.vb

updated logs to use AppData/Roaming/RInstat
Added version number and R location to logs

Updated logging to use appData folder

---

instat/static/InstatObject/R/InstallPackages.R

fixes #8138 
set the locale for date format in bundled version of R

Added locale to installed R

---

instat/static/InstatObject/R/Rsetup.R

fixed Rsetup.R by adding back the commas

fixes for install

---

instat/dlgCalculator.vb
instat/ucrCalculator.Designer.vb
instat/ucrCalculator.vb

Fixes #8176 
@rdstern I have fixed the issue reported in the corresponding. The addition feature quested there is a bit tricky to differentiate the type of script we would like to display or not, I did look at the code and will a have a quick discussion with @ChrisMarsh82 in few about. Meanwhile, you can check if the issue is fixed.

Correcting the issue on the Calculator when the result is not saved

---

instat/dlgClimaticCheckDataRain.vb

Fixes partially #8213
Fixes part g) of the issue
@rdstern , @lloyddewit , Made  rain variable be completed automatically

Ensured that rainfall is filled automatically in Climatic > Check QC Rainfall dialog

---

instat/dlgTidyDailyData.Designer.vb
instat/dlgTidyDailyData.vb

Fixes partially   #8213 
Fixes part b) of the issue
@rdstern , @lloyddewit , Made `Day Columns` to be default button

Made day column the default button in the Climatic > Tidy > Tidy Daily Data dialog

---

instat/static/InstatObject/R/install_packages.R

fixes #8234 
I have added the agriTutorial package. 
@lloyddewit this PR is ready for review. 
Thanks

Added agriTutorial package

---

instat/static/InstatObject/R/install_packages.R

Fixes partly #7681 
I have added the packages : `arm`, `rstanarm` and `statsr` in this PR
@lloyddewit can you have a look 
Thanks

Added New R packages to R-Instat

---

instat/ucrDataView.vb

Fixes partly #8278 
this fixes item D on the list
@lloyddewit , @rdstern This PR is ready for review.

Updated Help IDs for DataView

---

instat/dlgImportDataset.Designer.vb
instat/dlgImportDataset.vb
instat/dlgOptions.Designer.vb
instat/dlgRecodeNumericIntoQuantiles.Designer.vb
instat/ucrButtons.Designer.vb
instat/ucrSave.Designer.vb
instat/ucrScript.Designer.vb

Fixes #8247
Fixes #7749
Fixes #6563
Fixes #7598
Fixes #6700 
Fixes #6556

Translation changes

---

instat/Translations.vb
instat/sdgWindowNumber.Designer.vb
instat/sdgWindowNumber.vb
instat/translations/translateIgnore.txt
instat/ucrDataFrameMetadata.Designer.vb
instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Fixes #8325 
@rdstern Thank you for the discussion this morning about your comments in PR #8319. Here are the requested changes for the Window Number popup and the row/column status at the bottom of the data grid.
Please could you test?
If you're willing to approve today, then we can include in the new release.
Thanks

Translation changes requested by PR #8319 comments

---

instat/dlgBarAndPieChart.vb

Fixes #8300 
This pull request fixes the issue of the graphic presentation of the back-to-back plot in the bar chart dialog.
@derekagorhom , @rdstern this is ready for review.

Improved the back-to-back charts in the Bar Chart dialog

---

instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
instat/dlgEdit.Designer.vb
instat/dlgEdit.resx
instat/dlgEdit.vb
instat/instat.vbproj
instat/ucrDataView.Designer.vb
instat/ucrDataView.vb

Fixes partly #8239 
Replaces #8264 
This PR is ready for Review
@rdstern , @N-thony can you review/Test this PR 
Thanks

Added new dialog to edit cell contents in Data View

---

instat/dlgInventoryPlot.vb
instat/static/InstatObject/R/stand_alone_functions.R

Fixes Partially #8342 
@rdstern , @lloyddewit @N-thony , Fixes Part **a**, **b** and **c** of the issue. Part **d** will be fixed during the sprint with help of @lilyclements

Improved Climatic >Inventory dialog

---

instat/dlgSPI.Designer.vb
instat/dlgSPI.vb

Fixes (partially) #8244 
@rdstern , @N-thony @lloyddewit  , it works now well including plot for single station. I will check with @lilyclements  for  the multiple stations, I realized it was not working before.

Fixed a bug in the SPI dialog

---

instat/dlgDeleteRowsOrColums.Designer.vb
instat/dlgDeleteRowsOrColums.vb
instat/static/InstatObject/R/data_object_R6.R

Fixes #8296 with @Vitalis95 
@rdstern @N-thony this is ready to review

Ensured that If a variable is deleted, and the variable is part of a key, then the key is also deleted

---

instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb

Fixes #8415 
@rdstern please test.

Ensured that insert/delete row in Data grid does not trigger jump to the top of the page

---

instat/frmMain.Designer.vb

Fixes Partly #8384 
I have added tooltips to the following dialogues 
Bar Chart. 
Boxplot. 
Histogram
Line
HeatMap
Cumulative Distribution
Describe > One Variable > Frequencies. 
Describe > One Variable > Rating Data.
Describe > One Variable > Summarise
Describe > Two/Three Variable > Summarise 
Describe > Two/Three Variable > Two Way Frequencies 
Describe > Two/Three Variable > Three Way Frequencies 
Describe > Multivariate > Correlation 
Describe > Two/Three Variable > Cluster Analysis
@rdstern please can you review this PR. 
Thanks

Added tooltips to selected dialogs in the Describe menu

---

instat/Interface/IDataViewGrid.vb
instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
instat/dlgFindInVariableOrFilter.Designer.vb
instat/dlgFindInVariableOrFilter.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb
instat/static/InstatObject/R/stand_alone_functions.R
instat/ucrDataView.vb

replaces #8423
@rdstern please test.
Fixes #8427
Fixes #7950
I have also added CTRL + F to open the dialgoue.

Implemented Find Row(s) in the Data View Grid and fixed bug in the Edit Cell dialog

---

instat/Interface/IDataViewGrid.vb
instat/Model/DataFrame/clsDataFramePage.vb
instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/dlgWordwrap.Designer.vb
instat/dlgWordwrap.vb
instat/frmMain.Designer.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R
instat/ucrDataView.vb

Replaces #7922
Fixes #7812
Fixes partially #8443
@rdstern @derekagorhom please test the wrapping and unwrapping here.

Implemented wrapping and unwrapping on the DataView Grid

---

instat/UserControl/ucrOutputPages.Designer.vb
instat/UserControl/ucrOutputPages.resx
instat/UserControl/ucrOutputPages.vb
instat/UserControls/frmMaximiseOutput.Designer.vb
instat/UserControls/frmMaximiseOutput.vb

Fixes #8278 
I have added help buttons on both Maximise and Output windows and also added the help context numbers
@rdstern , @N-thony can you review this PR
Thanks

Added Help Button to Maximise window and Output window

---

instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/dlgFindInVariableOrFilter.Designer.vb
instat/dlgFindInVariableOrFilter.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/ucrDataView.vb

Fiexs partially #8217
@rdstern I have enabled and implemented the `Filter` option, have a look. If it is okay, we can merge it and will continue with the `Select` option.

Implemented find feature in Filter option in the Find dialogue

---

instat/Interface/IDataViewGrid.vb
instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/dlgFindInVariableOrFilter.Designer.vb
instat/dlgFindInVariableOrFilter.resx
instat/dlgFindInVariableOrFilter.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R
instat/ucrDataView.vb

Fixes #8217
@rdstern I have now implemented the find feature in Select option, have a look. Thanks.

Added find feature to Select option in Find dialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes partially #8421 
@rdstern this fixes part (b) of the issue and it's ready for review

Improved Describe>General menu and Describe<Graph options

---

instat/Model/Output/clsOutputElement.vb
instat/clsRLink.vb

Fixes part a of #8285 
Fixes #8308

Allow R script key words to be used in Log/Script window

---

instat/frmMain.Designer.vb
instat/frmMain.vb

Fixes #8476 
@rdstern @N-thony , have a look at it

Added a copy of Pivot Tables to the Prepare > Check Data menu

---

instat/dlgFindInVariableOrFilter.Designer.vb
instat/frmMain.Designer.vb
instat/frmMain.vb

fixes issue #8466,
@rdstern , this PR is ready for review

Deleted unused items in the Edit menu

---

instat/dlgGeneralForGraphics.Designer.vb
instat/frmMain.Designer.vb
instat/frmMain.vb

fixes #8421 ,
@rdstern this PR is ready for review

Improved the Describe>General and Describe>Graph menus

---

instat/static/InstatObject/R/install_packages.R

fixes partly #7227 
I have added  `rsplit `package in this PR from Roger's comment [Here](https://github.com/africanmathsinitiative/R-Instat/pull/7519#pullrequestreview-1549446627)
@lloyddewit can you have a look

Added rsplit package to R-instat 

---

instat/dlgNewDataFrame.vb

Fixes #8499
@rdstern please have a look.

Ensured correct R code generated by File > New Data frame

---

instat/dlgScatterPlot.Designer.vb
instat/dlgScatterPlot.vb

Fixes #8524
@rdstern, @N-thony I Added Jitter check box on ScatterPlot Dialog. Please have a look.

Added Add Jitter check box to the Describe > Graphs >Scatterplot dialog

---

instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb

Fixes #8587 
@rdstern the small bug found with the Row is now fixed, have a look.

Minor bug fixes in Edit > Find Dialogue

---

instat/sdgProportionsPercentages.vb

Fixes #8588 
I have fixed the problem with the receiver not appearing when the sub-dialog is used for the first time 
@N-thony , @rdstern can you review this
Thanks

Fixed small bug in Column summaries sub-dialog

---

instat/ucrAdditionalLayers.Designer.vb
instat/ucrAdditionalLayers.resx
instat/ucrAdditionalLayers.vb

Fixes partially #8527 
@rdstern I have changed the Add button to the Add buttom with menu context containing the geom functions as requested. Have a look

Added geoms in the Add menu context

---

instat/static/InstatObject/R/data_object_R6.R

Fixes #8488 
@rdstern @lloyddewit this fixes the bug reported in the Rename Dialogue when trying to rename a column from selected columns. Have a look. Thanks.
@MeSophie you can also have a look.

Bug fixes in the Rename Dialogue when Select is applied

---

instat/frmMain.Designer.vb

Added version number to main form

Add version number back in

---

instat/Model/DataFrame/clsColumnMetaData.vb
instat/Model/DataFrame/clsDataFramePage.vb
instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/clsRLink.vb
instat/dlgSelect.Designer.vb
instat/dlgSelect.vb
instat/dlgSelectColumns.vb
instat/frmMain.vb
instat/sdgDataOptions.vb
instat/static/InstatObject/R/data_object_R6.R
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R
instat/ucrColumnMetadata.vb
instat/ucrDataView.vb

Fixes #8600 
Fixes #8650
The dialogue checkbox is disabled and I was thinking that it will be good if the selection is applied to a specific dialogue?

Improved column selection to apply or not to dataframe, metadata or dialogue

---

instat/frmMain.Designer.vb

Added back version number

---

instat/dlgAddLink.vb

Fixes partially #8687
@rdstern have a look. Thanks

Fixed bug in Add Link Dialogue

---

instat/ucrScript.vb

@rdstern @lloyddewit have a look. Thanks

Ensure the cursor is visible in Script Window when executing the command with Run buttons

---

instat/dlgUnstack.vb

Fixes #8686 
@rdstern have a look,

 Added key and link in Restore Hierarchy option on Prepare > Data Reshape > Unstack dialog

---

instat/dlgColumnStats.Designer.vb
instat/dlgColumnStats.vb
instat/sdgProportionsPercentages.vb
instat/sdgSummaries.Designer.vb
instat/sdgSummaries.vb

Moved the Percentage sub-dialog into the Summaries sub-dialog in Prepare > Data Reshape > Column Summaries

---

instat/ucrReceiverMultiple.vb

Fixes #8797
@rdstern have a look

Disabled horizontal scrollbar in multiple receiver

---

instat/sdgCalculationsSummmary.vb

Fixes #8744
@rdstern I don't get the script you have posted in the issue but I fixed some bugs reported there. Have a look

Bug fixes in General Summary Dialogue

---

instat/ucrReceiverMultiple.vb

This will complete PR #8690 and anywhere neede. It adds the possibility of setting the maximum number of variables to add in a multiple receiver.

Setting the limit of variables to add in the multiple receiver

---

instat/clsRLink.vb
instat/dlgDescribeTwoVariable.vb
instat/static/InstatObject/R/instat_object_R6.R
instat/static/InstatObject/R/stand_alone_functions.R

Fixes #8855
@rdstern I couldn't reproduce your example in the corresponding issue on having multiple tables to the default browser. 
This is a quick check but will still investigate on having the multiple tables in output window rather than default browser. Can you test this?

Displaying multiple tables (html) in the output window

---

instat/dlgCalculator.vb
instat/static/InstatObject/R/stand_alone_functions.R

Fixes #8906
Fixes partially #7979 
@rdstern have a look

Sorting the display of numbers in the output window and the grid

---

instat/ucrDataView.vb

Convert to Numeric for logical variables

---

instat/static/InstatObject/R/data_object_R6.R

Fixes #8815 
@rdstern @rachelkg @Patowhiz this fixes the pasting of multiple columns. I used the scripts suggested by Patrick in the issue. Have a look.

Bug fix on pasting multiple columns

---

instat/dlgHideDataframes.vb

Fixes partially #8956 
@rdstern , @N-thony  I have made the change requested on PR #8961

Fixed bug when using Hide/Unhide Data Frame Dialogue

---

instat/Model/Output/clsOutputLogger.vb
instat/UserControl/ucrOutputPage.vb
instat/UserControl/ucrOutputPages.resx
instat/UserControl/ucrOutputPages.vb

Fixes partially #7979 
@rdstern I have added a checkbox to Select/Deselect All elements to the output window, have a look

Added Select/Deselect All checkbox to the output window

---

instat/clsRSyntax.vb
instat/dlgCalculator.vb

Fixed the error caused by attach and detach functions when there is no data in Calculator

---

instat/ucrDataView.vb

Fixes #9020 
@rdstern have a look

Corrected regression in the right-click Convert to numeric option

---

instat/dlgEnter.Designer.vb
instat/dlgEnter.resx
instat/dlgEnter.vb

Fixes #9023
@rdstern  have a look

Added Scalars to the Enter Dialogue

---

instat/frmMain.Designer.vb
instat/frmMain.vb

@rdstern sorry for your laptop, I hope you will be able to review this by next week when you are also fully back. I may add the fix on the R-instat library here too.

Fixes bug in the recovery feature and version number back

---

instat/Model/DataFrame/clsDataFramePage.vb
instat/static/InstatObject/R/stand_alone_functions.R

Fixes #9005 
@rdstern @Fidel365 I have fixed the displaying of roman in the grid. Have a look.

Fixing the displaying roman in the grid

---

instat/dlgExportToClimsoft.Designer.vb
instat/dlgExportToClimsoft.vb

Fixes #9095 
@rdstern @Patowhiz , have a look at it

Improvements to the Climsoft Export dialog 

---

instat/frmMain.vb

Replaces PR #9163 
Partially fixes #9164
@N-thony @rdstern  have a look it

Bug fix for new machine running R-Instat 

---

instat/frmMain.Designer.vb
instat/frmMain.vb

From comments on PR #9159
https://github.com/IDEMSInternational/R-Instat/pull/9159#discussion_r1780639924
I have added the version number function into the code file 
@N-thony , @Patowhiz can you check and confirm
Thanks

Version Number in the Frmmain code file

---

instat/clsRLink.vb

@ChrisMarsh82 as discussed I have updated the message for the current R version

Updated the message for the current R version

---

instat/dlgColumnStats.vb

@rdstern take a look if this helps with the output

Minor correction in the Prepare > Data Reshape > Column Summary Dialogue

---

instat/dlgSummaryTables.Designer.vb
instat/dlgSummaryTables.resx
instat/dlgSummaryTables.vb

Fixes partly #9010 
@rdstern , @N-thony  @lilyclements 
Added  Column factors control

Improvement to Describe > Tables dialog

---

instat/frmMain.vb

fixes partially #9088
@rdstern have a look

Set No loaded data text correctly after auto saving

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes partially #9308
@rdstern, this fixes point c), the message has been improved for the case there is a new version on the website. I have also updated the version number on the website to 0.8.0. This can be tested well in the release version.

Improved the message for checking the version available on the website

---

instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
instat/static/InstatObject/R/data_object_R6.R

Fixes #9160 
@rdstern, this tempts to fix the corresponding issue, so far the display of the geometry data has been replaced by "MULTIPOLYGON" and set the column to read only in the reogrid. Can you also check the speed issue and probable share with me the data you have used?

Improved the display of shapefile data

---

instat/frmMain.Designer.vb
instat/frmMain.vb
instat/ucrScript.Designer.vb
instat/ucrScript.resx
instat/ucrScript.vb

Fixes #8568
@rdstern, as the title said, have a look. 
You can find this under the insert button

Implementing Comment/Uncomment lines in Script Window

---

instat/dlgScript.vb

@rdstern, is this what you wanted?

Formatting script from preview window in Insert Dialogue

---

instat/static/InstatObject/R/data_object_R6.R

Bug fix in Levels/Labels dialogue when filter is applied

---

instat/Model/DataFrame/clsDataFramePage.vb
instat/clsRLink.vb

Fixes #9385
This issue was reported in PR #9372

Skipping enable disable undo script in the output window

---

instat/clsInstatOptionsDefaults.vb
instat/dlgOptions.vb
instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes (partly) #9268
Replaces #9495
@rdstern @derekagorhom have a look of this if it does what is expected.

Hiding Structured and Procurement Menus upon opening

---

instat/clsInstatOptions.vb
instat/clsInstatOptionsDefaults.vb
instat/dlgOptions.Designer.vb
instat/dlgOptions.vb
instat/frmMain.Designer.vb
instat/frmMain.vb

Fixes (partly) #9513
@rdstern, I have added the Tricot menu and sub menus as requested in the corresponding issue. Have a look.

Added Tricot Menu

---

instat/clsInstatOptions.vb
instat/clsInstatOptionsDefaults.vb
instat/dlgOptions.Designer.vb
instat/dlgOptions.vb
instat/dlgTraits.Designer.vb
instat/dlgTraits.resx
instat/dlgTraits.vb
instat/frmMain.Designer.vb
instat/frmMain.vb
instat/instat.vbproj
instat/ucrReceiver.vb

Fixes #9507
@rdstern @lilyclements this branch has been created from PR #9514. Have a look.

Implemented Tricot > Describe > Traits Dialogue

---

instat/dlgOutfillingStationData.Designer.vb
instat/dlgOutfillingStationData.vb
instat/instat.vbproj
instat/sdgAdvOptions.Designer.vb
instat/sdgAdvOptions.resx
instat/sdgAdvOptions.vb

Fixes #9510 
@rdstern @lilyclements , Roger suggested we keep Stations and Dry Months on the main dialog

Improving Outfilling dialog

---

instat/ucrDataView.vb

Fixes #8555
@rdstern, to test this very well, I suggest you restart your laptop and then run this branch.

Fixes issue in Open Library Dialogue

---

instat/dlgDefineTricotData.Designer.vb
instat/dlgDefineTricotData.vb

Fixes #9523
@lilyclements you can have a look now. The code generated from the dialogue looks okay, only some packages problem reported in the issue.

Implementing Tricot > Define tricot data

---

instat/dlgDescribeTwoVariable.vb

Improvements to hide the display margins checkbox and retain the selected columns

---

instat/instat.vbproj
instat/sdgTricotModelOptions.Designer.vb
instat/sdgTricotModelOptions.resx
instat/sdgTricotModelOptions.vb

@lilyclements and @rdstern 
I have created a Blank form for Tricot Model Options Subdialog, as per the discussion in #9570

Created a Blank form for Tricot Model Options Subdialog

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

@rdstern I have implemented what we discussed, please check
1. Prepare Menu on the Tricot dialogue is deleted
2. Transform climMob from Tricot dialogue is gone . I have placed  transform Tricot data in Tidy data
3. Changed order by putting "Tidy data" to the top before horizontal line
4. Changed the wording mistake to now " add (Merge) Columns..."

Refined Tricot dialogue

---

instat/frmMain.Designer.vb
instat/frmMain.resx
instat/frmMain.vb

Fixes partly #9308 
Removed "Run R code " and "Save Current Options" from the Tools Dialogues
Fixes partly #9556
Added to Tricots dialogue
Prepare - Visualize
- Pivot tables
- One variables commands
- Duplicates ( Key variable checks)
Describe - Two/ Three variable / graph summarize
fixes partly #9552 
Refine the Help Dialogue
In the "Menus and Dialogues" -  I replaced that with "Menu" and add below "Optional Menu".
In the Menus - I removed the other dialogues and left the compulsory dialogues only that is
- Menu and Dialogues
- File
- Edit
- Prepare
- Describe
- Model
- Tools
- View
I removed the line between Model and structured
In the Optional Menu - I added the Dialogues below
- Structured
- Climatic
- Procurement
- Experiments
- Tricot
- Tricot XP
@rdstern I have implemented what we …

1. Removed "Run R code " and "Save Current Options" from the Tools Dialogues   2. Add to Tricots  3.Refine the Help Dialogue 

---

instat/dlgTricotModelOneVarCov.Designer.vb
instat/dlgTricotModelOneVarCov.vb

Fixes Partially #9519 
@rdstern and @lilyclements Added the Tricot One Variable main dialog. This is ready for review. 
The subdialogs will be added once ready.

Added Tricot One Variable Covariate dialog

---

instat/dlgModellingTree.Designer.vb
instat/dlgModellingTree.vb

Fixes Partly #9518 
@rdstern, @lilyclements Kindly review the modelling (tree) tricot dialog.

Added the tricot dialog: Modelling (tree)

---

instat/dlgPlacketLuceModel.vb
instat/sdgDisplayModelOptions.Designer.vb
instat/sdgDisplayModelOptions.vb

Partly Fixes #9513 
Fixes #9565
@lilyclements I have updated my `instatExtra` package and `icalltype` in vb. But I am afraid that's not enough. When I first ran a graph, am empty viewer window appeared for a few seconds and then disappeared. No graph was displayed on either the output window or the viewer window. Could you please try if it works correctly for you, then it's certainly a problem from my side.

Small Change in No Cavariate Tricot Dialog

---

instat/dlgDefineTricotData.vb

Adding checks for the Define Tricots Dialog

---

instat/dlgDescribeTwoVariable.vb

Describe Dialogue ->2/3 Variables -> Summarise
a. Deleted one column from the display which was the second column
b. If multiple tables then make text into a title - This is done
@rdstern I have implemented what we discussed, please check

Describe 2/3 Variables Summary.

---

instat/dlgDescribeTwoVariable.vb
instat/dlgRPackages.vb

I do not know what issue this fixes;
This PR solves the problem with the R Packages dialog not properly installing packages from IDEMSInternational and also added the 4 new packages which were created by @lilyclements in the Packages dropdown.
This PR also has removed some commented code which was found in PR #9547.
@lilyclements , @rdstern this is ready for review.
Thanks

Improvements to R Packages Dialog

---

instat/dlgClimdexIndices.vb

@rdstern and @lilyclements
this relates to the issues #9561, despite I haven't been able to finish, but am puting it here so that someone can provide an idea on how to solve the issue, althought am still working on it behind. I'll appreciate if someone shares his idea

Issues 9561 related about the R code in IntatClimatic

---

instat/frmMain.Designer.vb
instat/frmMain.vb

@rdstern I have implemented what we discussed 
1. Changed "Exit/Edit Data" to Exit Data
2. put a line after import from ClimMob
3. Changed order on optional menu and now structured comes first before climatic
4.  In the menus sub dialogue put "Menus and Dialogues"

Changed "Exit/Edit Data" to Exit Data

---

instat/dlgAddKey.vb
instat/dlgDescribeTwoVariable.vb
instat/dlgDuplicates.vb
instat/dlgMergeAdditionalData.vb
instat/dlgOneVariableGraph.vb
instat/dlgOneVariableSummarise.vb
instat/dlgOneWayFrequencies.vb
instat/dlgThreeVariablePivotTable.vb
instat/dlgVisualizeData.vb
instat/sdgMerge.vb
instat/sdgOneVarGraph.vb
instat/sdgOneWayFrequencies.vb

@lilyclements  @rdstern * Examine menu:
- Added Help links to the following dialogs and sub-dialogs:
• Visualise Data
• Pivot
• One Variable Summary
• One Variable Graph and its sub-dialog
• Variable Frequencies and its sub-dialog
* Tidy menu:
- Added Help links for:
• Duplicate
• Add/Merge Columns
• Add Key
• Joining Columns (sub-dialog)
* Describe menu:
- Added Help link for:
• Summarise 2/3 Variables dialog
- Note: Help link for Graph 2/3 Variables (ID 744) not added — couldn’t locate corresponding `.vb` file.

help links update

---

instat/dlgModellingTree.Designer.vb
instat/dlgModellingTree.vb
instat/dlgTricotModellingGeneral.Designer.vb
instat/dlgTricotModellingGeneral.vb

Fixed Partly #9601 
Fixed the code to make the graphs show in the output window when a plot type is selected in the Graphics tab in the display options sub-dialog for both modelling dialogs (Trees and General) 
@lilyclements I have made the following observation and I will like your opinion.
So in the modelling (general) dialog, the function that runs when the 'check variety' button is clicked throws an error when you use a different dataset (other than the tricot data). This error occurs in the 'check_variety_data_level' function with the error message;
'Object 'Tricot_Type' not found'. 
This is actually great because the specified dataset does not actually have the 'Tricot_Type' object, but from a UI perspective, is it great?
I think it'll work better the way the …

Fixed Issue with plots not apppearing

---

instat/dlgTricotModelOneVarCov.Designer.vb
instat/dlgTricotModelOneVarCov.vb

Replaces #9602
Fixes #9519
Additions to #9602:
- Bug fixes in VB code from Master amendments
- Added visibility for plots

Linking Display Options Subdialog to the One Covariate Dialog

---

instat/dlgModellingTree.Designer.vb
instat/dlgModellingTree.vb
instat/dlgTricotModelOneVarCov.vb
instat/dlgTricotModellingGeneral.vb

Adding checks for `TRUE/FALSE` sub-dialog bits

Adding functionality to sub-dialog to Tricot Modelling

---

instat/dlgDefineTricotData.Designer.vb
instat/dlgDefineTricotData.vb

Fixes #9569 
@rdstern @lilyclements I have added the checkboxes and configured it as mentioned in the issue. Kindly review the changes.
I also added the count of the selected columns in the multiple receivers

Added the two checkboxes to the tricot define dialog

---

instat/dlgDefineTricotData.Designer.vb

Fixes #9624 
@rdstern @lilyclements  I have made some modifications to the design of the define tricot dialog. Kind review if it's okay now.
Thank you.

Made design changes to the define tricot dialog 

---

instat/dlgDescribeTwoVariable.vb

Fixes #9618 
I have fixed the error produced when the instatExtras::generate_summary_tables() function was added into the 2/3 Variable Summarise dialog.
@rdstern , @lilyclements  this PR is ready for review.

Fixed bug introduced by instaExtras function in the 2/3 Variable Summarise Dialog

---

instat/dlgDefineTricotData.Designer.vb
instat/dlgDefineTricotData.vb

Fixes #9662 
@rdstern Please, I have fixed the issues you highlighted. Kindly check and see if they meet your requirements. Thank you.

Small changes to the tricot define dialog

---

instat/dlgDefineTricotData.Designer.vb
instat/sdgPLModelOptions.Designer.vb

Dialog layouts for Plackett Luce Model Options

---

instat/dlgTraits.vb

Ensuring the data name runs in the Tricot > Describe > Traits dialog

---

instat/static/InstatObject/R/InstallPackages.R

Updating packages for installer

added ncdf4 do install from archive

---

instat/ucrCalculator.Designer.vb
instat/ucrCalculator.resx
instat/ucrCalculator.vb

Fixed #7619 
@lilyclements @rdstern Kindly check if changes meet your requirements. Thank you

Updated the R-help labels for the transform, summary, factor and text/string keyboards.

---

instat/ucrCalculator.vb

Fixes #9675 
@rdstern @lilyclements I have added the parameter specified in the issue and the phi key works now.

Added parameter for the phi option on the integer keyboard

---

instat/clsRecentFiles.vb
instat/frmEditor.vb
instat/frmMain.vb
instat/ucrDataView.vb

Fixes #9651 
I did a couple of test runs and they seem to run fine, the Column factor dialog don't seem to cause the problems found anymore. 
@lilyclements please can you do a stress test and see if everything works fine for you too. 
Thanks

Fixed Regression found in the Column Factor dialogs

---

instat/dlgReorderLevels.vb

solves #9668 
@rdstern Kindly check to confirm
I have corrected the bug in the Reorder Level
@lilyclements

Correct the bug in using the Prepare > Column: Factor > Reorder Level

---

instat/dlgSelect.Designer.vb
instat/dlgSelect.vb
instat/sdgDataOptions.Designer.vb
instat/sdgDataOptions.vb

Fixes #8694 
@rdstern and @lilyclements I have added the column selection preview now and this is ready to review.
Thanks to Lily for the new function `$column_selection_string`
Note you need to update `databook` to run this

Added Column Selection Preview

---

instat/dlgCorrelation.designer.vb
instat/dlgCorrelation.resx
instat/dlgCorrelation.vb

Fixes #4913 
I have added Tooltip for the Kendal, Spearman and Pearson option in the Correlations dialog. 
@berylwaswa, @lilyclements can you review this 
Thanks

Added Tooltips to Kendall, Spearman and Pearson options in the Correlations Dialog

---

instat/ucrCalculator.Designer.vb
instat/ucrCalculator.vb

Fixes #9714
This is the new PR for the rollapply option on the `Transform` keyboard. As discussed, I created this new PR so that we don't have to deal with any potential conflicts.
I request that once this has been merged, the PR #9719 can be closed. Thank you

Added the roll apply option to the transform keyboard

---

instat/App.config
instat/dlgTransformTricotData.Designer.vb
instat/instat.vbproj
instat/packages.config
instat/sdgTransformations.Designer.vb
instat/sdgTransformations.vb

@lilyclements @derekagorhom  @rdstern 
issue #9646 
Added a checkbox on the sub-dialog for the Transform dialog which says "Choose Traits Suffix". Default unchecked. If checked, the "Good Traits Suffix" and "Bad Traits Suffix" labels and inputs come up, and that code runs. 
Moved the "Options" to be above the "Check" on the main dialog 
Set the drop downs to be editable 
I also updated the packeges and still got the same errors

Added a checkbox (unchecked default) and made the dropdown editable

---

instat/dlgPlacketLuceModel.Designer.vb
instat/dlgPlacketLuceModel.vb

Adding `data` argument in "No Covariates" (tricot) dialog 

---

instat/dlgName.vb

Fixes #5019 
@lilyclements @derekagorhom , have a look at it

Fixes a bug when Renaming shape files columns

---

instat/sdgDefineAnnualRainfall.Designer.vb
instat/sdgDefineAnnualRainfall.vb

Update Export to Google Buckets dialog to work with R Code for `Crop`'s tab

---

instat/static/InstatObject/R/install_packages.R

Fixes #9585 
@lilyclements can review this 
Thanks

Added R Packages into R-Instat

---

instat/dlgPlacketLuceModel.vb

Fixes #9755
@rdstern @lilyclements Kindly review the changes to see if everything is fine now. Thanks

Changes to the code for saving coefficients

---

instat/dlgSort.Designer.vb
instat/dlgSort.vb

Adding functionality to sort with missing values accounted for

---

instat/dlgTransformTricotData.vb

As discussed in #9770. This PR adds in additional messages in the Check under the Transform Tricot dialog

Adding and amending error messages for Transform Tricot dialog

---

instat/dlgSplitText.Designer.vb
instat/dlgSplitText.vb

Fixes #3751 
@lilyclements @rdstern @Ag-Derek , this ready for review

  Improving dlgSplit dialog to use multiple variables efficiently

---

instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
instat/frmMain.vb

Fixes #9832 
Please, I have added this functionality.

Added the R-Viewer for the Data Frame Metadata

---

instat/clsGgplotDefaults.vb
instat/sdgPlots.vb

Fixes Partly #9820 
I have fixed the theme_economist bug which was appearing because ggthemes argument was not added initially
@lilyclements can you review this 
Thanks

Fixed error with themes not correctly appearing from the Plot options

---

instat/static/InstatObject/R/install_packages.R

Fixes Partly #9812 
@lilyclements this PR adds the ggthemes package into R-instat
can you review this 
Thanks

Added ggthemes to R packages

---

instat/dlgColumnStructures.vb

Fixes #9855
Fixes issues with the ucrCheck being added as a parameter, when it should not be a parameter

Fixes in Column Structures

---

instat/dlgDescribeTwoVariable.vb

@lilyclements @rdstern @anastasia-mbithe kindly review
Partially solves issue #9863

Fix DataFrame reference bug in "Three Variables" tab when selector changes without reset

---

instat/dlgTransformClimatic.vb

Fixes #9907 
@lilyclements @rdstern @Ag-Derek 
Correctly builds` function_exp` based on the selected operation and threshold values.

Fixes a bug  in Climatic > Prepare > Transform dialog 

---

instat/dlgExportClimaticDefinitions.Designer.vb
instat/dlgExportClimaticDefinitions.vb
instat/sdgDefineAnnualRainfall.Designer.vb
instat/sdgDefineAnnualRainfall.vb

Fixes #9906 
@lilyclements, @rdstern. Kindly review these changes to check if everything works as expected.
Thank you

Added Extremes into the Export to Google Buckets dialog

---

instat/dlgBoxPlot.vb

This PR fixes the issue below
@lilyclements @berylwaswa, while working on fixing the issue with Beryl Repo we found out that the main had a failed check, i hope this fixes it and then beryl make another pull request and it should work for her.
Thanks

Fixed Regression found in  Boxplot

---

instat/dlgBarAndPieChart.vb
instat/dlgBoxPlot.vb
instat/dlgGeneralForGraphics.vb
instat/dlgHistogram.vb
instat/dlgLinePlot.vb
instat/dlgScatterPlot.vb

@berylwaswa @Ag-Derek 
This is in line with the changes made in #9840 
Linking the facet in the main dialog and the subdialog, solves issues the issues we had before with the facets
In this branch, I have linked facets in the Barchart, Scatter plot, Line Plot, General Graphics, and the Histogram (I've restored the older code as well (had made some changes in #9840, that were not complete))

Linking Facets in Graphs

---

instat/dlgExportClimaticDefinitions.Designer.vb
instat/dlgExportClimaticDefinitions.vb
instat/sdgDefineAnnualRainfall.Designer.vb
instat/sdgDefineAnnualRainfall.vb

Fix #9943 
@lilyclements @jkmusyoka , this ready for testing

Improvements to Export Google Buckets dialog

---

instat/dlgImportFromEPicsa.Designer.vb
instat/dlgImportFromEPicsa.resx
instat/dlgImportFromEPicsa.vb
instat/instat.vbproj

Fixes partly #9960 
@lilyclements Please, I've added the dialog to `frmMain`. I'll now populate it with controls and code accordingly

Added the empty Import from E-Picsa dialog to frmMain

---

instat/static/InstatObject/R/install_packages.R

This is a request from @rdstern to add the Quarto R Package into R-instat due to the improvements in the Script Window in regards to the quarto facilities 
@lilyclements , @Vitalis95 we just need to approve and merge this PR 
Thanks

Added Quarto R package in R-Instat
