instat/dlgCalculator.designer.vb, instat/dlgDescriptiveStatistics.Designer.vb, instat/dlgSort.Designer.vb, instat/dlgStartofRains.Designer.vb, instat/rSyntax.vb, rLink.vb
=> Changes to the Sort, Descriptive, Start of Rains, RSyntax

instat/MultilingualResources/instat.fr-FR.xlf, instat/MultilingualResources/instat.sw-KE.xlf, instat/instat.vbproj, instat/ucrSelectorAddRemove.designer.vb, instat/ucrSelectorAddRemove.fr-FR.resx, instat/ucrSelectorAddRemove.resx, instat/ucrSelectorAddRemove.sw-KE.resx, instat/ucrSelectorAddRemove.vb
=> Added control for add or remove

instat/dlgHistogram.fr-FR.resx, instat/dlgHistogram.resx, instat/dlgHistogram.sw-KE.resx, instat/dlgHistogram.vb
Updated the dialog to be working.
=> Added the Histogram dialog

instat/MultilingualResources/instat.fr-FR.xlf, instat/MultilingualResources/instat.sw-KE.xlf, instat/dlgHistogram.designer.vb, instat/dlgHistogram.fr-FR.resx, instat/dlgHistogram.resx, instat/dlgHistogram.sw-KE.resx, instat/dlgHistogram.vb, instat/instat.vbproj
I have added the histogram which is using the RSyntax
=> Addition of the Histogram

instat/frmMain.Designer.vb, instat/frmMain.vb
Added the menu entry for Climate
=> Changes to the Main form

instat/frmMain.Designer.vb
Tagging, checked on click and shortcut keys added to File menu.
=> Added some changes to the menu File

instat/dlgProbabilityPlot.vb
This is the newly redone probability plot
=> redone Probability plot dialog

instat/My Project/Resources.Designer.vb, instat/My Project/Resources.resx, instat/dlgEndRain.designer.vb
End of Rain Dialog, with all parameters.
=> End of Rain Dialog, with all parameters.

instat/dlgOutputforCDT.designer.vb, instat/dlgOutputforCDT.vb
Modifications to Output for CDT with all the parameters.
=> Output for CDT - Climatic Methods Menus.

instat/dlgRainStats.designer.vb, instat/dlgRainStats.vb
Modifications to Rain Statistics with all parameters.
=> Rain Statistics - Climatic Methods Menus.

instat/dlgTimeseriesPlot.designer.vb, instat/dlgTimeseriesPlot.vb
Timeseries dialog with all parameters (: data list).
=> Tiimeseries - Climatic Methods Menus.

instat/dlgCorrelations.designer.vb, instat/dlgCorrelations.fr-FR.resx, instat/dlgCorrelations.resx, instat/dlgCorrelations.sw-KE.resx, instat/dlgCorrelations.vb, instat/dlgRandomSample.designer.vb, instat/dlgRandomSample.fr-FR.resx, instat/dlgRandomSample.resx, instat/dlgRandomSample.sw-KE.resx, instat/dlgRandomSample.vb
=> correlations dialogue

instat/dlgCumulativeExceedance.designer.vb, instat/dlgCumulativeExceedance.vb
Cumulative Exceedence plot with all parameters.
=> Cumulative Exceedence - Climatic Methods Menus.

instat/dlgBoxplotCountVariable.designer.vb, instat/dlgBoxplotCountVariable.vb
Boxplot Count Variable Method with all parameters
=> Boxplot Count Variable Method -Climatic Method Menus

instat/dlgCliPlot.designer.vb, instat/dlgCliPlot.vb
Cliplot dialog with all parameters.
=> Cliplot dialog - Climatic Methods Menus.

instat/rLink.vb
This is the latest edit on Rlink
=> Cleaned up RLink- removed >on strOutput

instat/dlgExtremes.Designer.vb, instat/dlgExtremes.fr-FR.resx, instat/dlgExtremes.resx, instat/dlgExtremes.sw-KE.resx, instat/dlgExtremes.vb
This is a new dialog to be worked on
=> New dlgExtremes

instat/dlgRecode.Designer.vb, instat/dlgRecode.vb
This is the redone recode dialog
=> redone recode dialog

instat/dlgTwoWayAnova.Designer.vb, instat/dlgTwoWayAnova.fr-FR.resx, instat/dlgTwoWayAnova.resx, instat/dlgTwoWayAnova.sw-KE.resx, instat/dlgTwoWayAnova.vb
=> Non-Parametric Two Way ANOVA

instat/dlgOrthogonal.Designer.vb, instat/dlgOrthogonal.fr-FR.resx, instat/dlgOrthogonal.resx, instat/dlgOrthogonal.sw-KE.resx, instat/dlgOrthogonal.vb
=> New dlgorthogonal

instat/dlgGeneral.Designer.vb, instat/dlgGeneral.fr-FR.resx, instat/dlgGeneral.resx, instat/dlgGeneral.sw-KE.resx, instat/dlgGeneral.vb
=> Dlg general

instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
This contains majority dialogs, with some not functional and a few others missing which will be worked on soon.
=> Adding dialogs to main

instat/frmMain.vb, instat/instat.vbproj
This includes vbproj which includes them to master.
=> Adding climatic dialogs to main form

instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb
Removed the user control an disabled ok button so it wont crash
=> Non Crashing calculator

instat/frmMain.vb
This contains additions on opening from library and open dialog. 
It has not achieved much functionality yet but i hope we will have it working soon
=> Mnu filework

instat/dlgBivariateANOVA.Designer.vb, instat/dlgBivariateANOVA.vb
=> Dlg bivariate anova

instat/dlgAlignment.Designer.vb, instat/dlgBoxPlot.designer.vb, instat/dlgBoxPlot.vb, instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb
=> Calculator

instat/dlgBoxPlot.designer.vb, instat/dlgBoxPlot.vb, instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb, instat/dlgChangeType.designer.vb
correction on naming convention on dlgChangeType
=> Dlg change type

instat/dlgDuplicateColumns.Designer.vb, instat/dlgExtremes.Designer.vb, instat/dlgExtremes.vb, instat/dlgFind.Designer.vb, instat/dlgFreqTables.Designer.vb, instat/dlgGammaDistr.designer.vb, instat/dlgGammaDistr.vb, instat/dlgHistogram.designer.vb, instat/dlgHistogram.vb, instat/dlgInteractions.Designer.vb, instat/dlgInteractions.vb
correction on naming convention
=> dlgInteractions

instat/dlgRegularSequence.vb, instat/rSyntax.vb
Added functionality to do assignment through R syntax
=> R syntax assignment

instat/dlgFileNew.Designer.vb, instat/dlgFileNew.fr-FR.resx, instat/dlgFileNew.resx, instat/dlgFileNew.sw-KE.resx, instat/dlgFileNew.vb, instat/frmEditor.vb, instat/frmMain.vb, instat/instat.vbproj
Added functionality to create a blank data frame and save an Instat object as a file (.RDS). Next step to add function to load .RDS file.
=> File new & save

instat/frmEditor.Designer.vb, instat/frmEditor.fr-FR.resx, instat/frmEditor.resx, instat/frmEditor.sw-KE.resx
Same comment as before, added the options the user sees when they right click on selected row, cell or lead Header of the grid
=> Added the cellsContext, rowContext and leadHeaderContext right click Actions.

instat/ucrNewColumnName.vb
ucrNewColumnName.vb was not added to the project.
=> Bug fixed with ucr new column

instat/dlgUnstack.Designer.vb, instat/dlgUnstack.vb
Redone dlgUnstuck with Bethans Guidelines
=> Dlg unstack

instat/frmMain.Designer.vb
Removed ticks on file menu items
=> Removing ticks file menu

instat/frmMain.Designer.vb, instat/frmMain.vb, instat/frmMetaData.designer.vb, instat/frmMetaData.vb
Renamed worksheet metadata to data frame metadata, changed the grid dock to fill, added the right click contexts to make the form interactive. Also I changed the names in the menu entries in the form main.
=> Task 4: Forms e)

instat/frmEditor.vb, instat/frmMain.vb, instat/frmVariables.designer.vb, instat/frmVariables.vb
Renamed worksheet information to variable column metadat, added back the tab control for showing different data frame names, add the right clicks context to make it interactive and made it resizable and child form of the main form
=> Task 4: Forms d)

instat/frmLog.Designer.vb
Prevents the log window having all the text selected when loaded.
=> Task 4: Forms g)

instat/frmMain.Designer.vb, instat/frmMain.vb
Removed import export from file menu and moved code to open from file
=> File menu works 

instat/dlgOptions.Designer.vb, instat/dlgOptions.vb
Addeded language settings into options dialog
=> Dlgoptionswork

instat/dlgBoxPlot.designer.vb, instat/dlgDotPlot.designer.vb, instat/dlgHistogram.designer.vb, instat/dlgProbabilityPlot.designer.vb, instat/dlgScatterPlot.Designer.vb, instat/dlgStemAndLeaf.Designer.vb
Resizing misfigured dialogs on graphics menu
=> Resizing dialogs

instat/dlgOptions.vb
This options dialog works well now
=> Fixing some bug with the options dialog

instat/My Project/Resources.Designer.vb, instat/My Project/Resources.resx, instat/clsRSyntax.vb, instat/dlgRandomSample.vb, instat/ucrDistributions.vb, instat/ucrDistributionsWithParameters.vb
Mean	Mean
Probability	Probability
Added missing parameters on the resource file
=> Random sample work

instat/dlgcolrowname.designer.vb, instat/dlgcolrowname.fr-FR.resx, instat/dlgcolrowname.resx, instat/dlgcolrowname.sw-KE.resx, instat/dlgcolrowname.vb, instat/instat.vbproj
Dialogue for interactively inserting  for example column name
=> added colrowname dialogue

instat/dlgcolrowname.vb, instat/static/InstatObject/R/data_object.R
Edited rename column method in data_object and error checking in dlgolrowname
=> Edited rename column method and dlgcolrowname

instat/dlgStack.Designer.vb, instat/dlgStack.vb, instat/ucrButtons.Designer.vb, instat/ucrReceiver.vb, instat/ucrReceiverSingle.vb, instat/ucrSelectorAddRemove.designer.vb, instat/ucrSelectorByDataFrameAddRemove.Designer.vb
DlgStack with the desirable features
=> More work on dlgStack. 

instat/frmEditor.vb
With these commit the grid and the R end are always in sync when changes are made on the grid.
=>   With these commit the grid and the R end are always in sync when changes are made on the grid.  

instat/dlgStack.Designer.vb, instat/dlgStack.vb
Added deafult settings and reset for dlgstuck
=> dlgStack defaultsettings

instat/dlgUnstack.Designer.vb, instat/dlgUnstack.vb
Added keypress tabs order and parameter parsing code, remaining work is to pass correct parameters
=> dlgUnstackwork

instat/dlgCliBoxplot.designer.vb, instat/dlgCliBoxplot.vb
Cliboxplot with all parameters
=> Cliboxplot - Climatic Methods Menus.

instat/dlgInventoryMethod.designer.vb, instat/dlgInventoryMethod.vb
Inventory Plot with all parameters.
=> Inventory Plot -Climatic Methods Menus

instat/dlgMissingValuesplot.designer.vb, instat/dlgMissingValuesplot.vb
Plot Missing Values Rain dialog with all parameters.
=> Plot Missing Values Rain -Climatic Methods Menus

instat/dlgDisplaySpellLength.designer.vb
Display Spell Length dialog with all parameters.
=> Climatic Menus Methods. 

instat/dlgDisplayDoyofYear.designer.vb, instat/dlgDisplayRainRunningTotal.designer.vb
Display DOY dialogue with parameters.
=> Climatic Methods Menus

instat/dlgSeasonalSummaryRain.designer.vb, instat/dlgSeasonalSummaryRain.vb
Seasonal Summary Rain dialog with all parameters, some not working.
=> Seasonal Summary Rain - Climatic Methods Menus

instat/dlgWindrosePlot.designer.vb
Wind rose Plot dialog. Fixing the designer code
=> Fixing The designer code

instat/dlgSummaryStatistic.Designer.vb, instat/dlgSummaryStatistic.fr-FR.resx, instat/dlgSummaryStatistic.resx, instat/dlgSummaryStatistic.sw-KE.resx, instat/dlgSummaryStatistic.vb
Created Summary Statistics Dialogue with all parameters
=> Summay Statistics -Climatic Methods Menus.

instat/dlgEndofRains.vb, instat/dlgInventoryPlot.vb, instat/dlgStartofRains.vb, instat/frmMain.vb, instat/instat.vbproj, instat/ucrSelector.vb
Removed bugging errors in the project, excluded dlgView which will be redone by john and removed unused variable j in the selector
=> Fixed bugging errors

instat/dlgBoxplotMethod.vb
This makes our pull requests to ZERO!!
=> redone boxplotmethod for climatic menu

instat/dlgStack.vb, instat/dlgUnstack.vb
fixed the onload crashing bug on stack and unstack dialogs
=> Bug fixing

instat/clsDistribution.vb, instat/ucrDistributions.vb, instat/ucrDistributionsWithParameters.vb
Added new Distribution -Von mises
=> Random sample new distribution

instat/My Project/Resources.Designer.vb, instat/My Project/Resources.resx
=> Von mises translations

instat/frmMain.Designer.vb, instat/frmMain.vb
=> File, Manage and Graphics menu: Doing correction on the tags.

instat/dlgOneSample.Designer.vb, instat/dlgOneSample.vb
Did changes on Onesample dialog(this is still not working to perfection )
=> One sample dialog

instat/frmMain.Designer.vb
Added Export entry to the menu, which will be used to save the data in other file formats.
=> Added Export entry to the menu, which will be used to save the data in other file formats.

instat/clsRLink.vb, instat/dlgOptions.Designer.vb, instat/dlgOptions.vb
Modified the appearance of the options for font and color, now it shows a button for preview and changing the formats
=> Modified the appearance of the options for font and color, now it shows a button for preview and changing the formats

instat/dlgDeleteColumn.Designer.vb, instat/dlgDeleteColumn.fr-FR.resx, instat/dlgDeleteColumn.resx, instat/dlgDeleteColumn.sw-KE.resx, instat/dlgDeleteColumn.vb, instat/dlgDeleteSheet.Designer.vb, instat/dlgDeleteSheet.fr-FR.resx, instat/dlgDeleteSheet.resx, instat/dlgDeleteSheet.sw-KE.resx, instat/dlgDeleteSheet.vb, instat/dlgInsertColumn.Designer.vb, instat/dlgInsertColumn.fr-FR.resx, instat/dlgInsertColumn.resx, instat/dlgInsertColumn.sw-KE.resx, instat/dlgInsertColumn.vb, instat/dlgRegularSequence.fr-FR.resx, instat/dlgRegularSequence.sw-KE.resx, instat/dlgRenameSheet.Designer.vb, instat/dlgRenameSheet.fr-FR.resx, instat/dlgRenameSheet.resx, instat/dlgRenameSheet.sw-KE.resx, instat/dlgRenameSheet.vb, instat/instat.vbproj
Added for dialogs for inserting, delete columns and also Rename, delete sheets. These are dialogs that will be accessible from the Manage menu.
=> Added for dialogs for inserting, delete columns and also Rename, delete sheets. These are dialogs that will be accessible from the Manage menu.

instat/dlgAnnualRaintotal.vb, instat/static/ClimateObject/R/BackendComponents/summary_functions.R, instat/static/ClimateObject/R/ClimateMethods/Graphics/plot_annual_rain_total_method.R, instat/static/ClimateObject/R/ClimateMethods/Graphics/plot_yearly_rain_count.R, instat/static/ClimateObject/R/climate_refclass.R, instat/static/InstatObject/R/instat_object.R
Included values over threshold into the list of summary functions
Also included value over threshold as a summary function for  "Number of rain days" in Climate_refclass.R.
Edited plot_annual_rain_total.R and Plot_yearly_rain_count.R
=> Editing climate methods

instat/dlgPrintPreviewOptions.Designer.vb, instat/dlgPrintPreviewOptions.vb
Added the preview and print options for the log and output windows.
=> Added the preview and print options for the log and output windows. 

instat/dlgHistogram.vb
Added density and frequency polygon functions
=> Histogram modifications

instat/dlgPermuteRows.Designer.vb, instat/dlgPermuteRows.vb
=> dlgPermuteRows:

instat/dlgBarAndPieChart.Designer.vb, instat/dlgBarAndPieChart.vb
very, little tidying up needed. Will work on it later on
=> Final Bar and Pie Chart including tabs order

instat/dlgPermuteRows.Designer.vb, instat/dlgPermuteRows.fr-FR.resx, instat/dlgPermuteRows.sw-KE.resx
Hi Danny, The files are now in this request
=> Modifying dlgPermuteRows to include resource files

instat/ucrFactor.vb
Added changes to reflect line 42 where both are set to True.
=> Ucr factors

instat/dlgSummaryBarOrPieChart.Designer.vb, instat/dlgSummaryBarOrPieChart.vb
FInalized SummaryBar or summaryChart. 
little tiding up remaining
=> FInalized SummaryBar or summaryChart.

instat/dlgMissingValuesplot.designer.vb, instat/dlgMissingValuesplot.vb
Redoing the missingValues dialog for the climatic methods
=> Redone dlgMissingValues for the climatic methods

instat/clsInstatOptions.vb, instat/dlgOptions.Designer.vb, instat/dlgOptions.vb, instat/dlgSort.vb, instat/frmMain.vb, instat/instat.vbproj
Proposed changes to include default parameters when global option is changed
=> Defaults on dlgSort

instat/ucrButtons.vb
=> Corrected the key press on the ucr buttons

instat/clsROperator.vb, instat/clsRSyntax.vb, instat/dlgRegressionSimple.Designer.vb, instat/dlgRegressionSimple.resx, instat/dlgRegressionSimple.vb, instat/sdgPlots.vb, instat/ucrReceiver.vb
Fixed dlgRegressionSimple  and implemented Shift + Tab on ucrReceiver
=> Fixing simple regression dialogue and ucrReceiver

instat/clsGridLink.vb, instat/static/InstatObject/R/instat_object.R
Added data_objects_changed field to instat object and set it appropriately in the  metadata and also appropriately called in clsGridLink
=> data_objects_changed

instat/dlgRank.Designer.vb, instat/dlgRank.vb
The resetting of the data selector is now fixed
=> Dlg rank vb

instat/dlgDeleteColumn.Designer.vb, instat/dlgDeleteColumn.vb, instat/static/InstatObject/R/instat_object.R
Almost completing the dialog, with enable/disable okay, ToScript. Help also now points to the right direction. Also reset works
=> Implementation of this week tasks on the dialog

instat/dlgSort.Designer.vb, instat/dlgSort.vb
This is after the discussion we had earlier
=> dlgSort: Changing Event from Leave to SelectionChanged

instat/dlgBarAndPieChart.Designer.vb, instat/dlgBarAndPieChart.vb, instat/dlgBoxPlot.vb, instat/ucrReceiver.vb, instat/ucrReceiverMultiple.vb, instat/ucrReceiverSingle.vb
This includes adding of plot options on barchart dialog, setting datatype for boxplot receivers and creating of IsEmpty to check for empty receivers.
=> Tidying up of bar chart

instat/clsRFunction.vb, instat/dlgRegressionSimple.Designer.vb, instat/dlgRegressionSimple.vb, instat/sdgSimpleRegOptions.Designer.vb, instat/static/InstatObject/R/instat_object.R
Including subdialogue in simple regression and editing instat object and RFunction.
NOTE: The code is not really stable state, I will fix it tomorrow.
=> Including subdialogue in simple regression

instat/dlgUnstack.Designer.vb
The code for this dialog is still not with us.
I will be updating R code as soon as we receive it from Beth.
Thanks
=> dlgUnstack: Updating frontEnd

instat/dlgStack.Designer.vb, instat/dlgStack.vb
I am not sure what to specify on the reopening of the dialog. Can you help please
=> dlgStack: Updating VbCode

instat/static/InstatObject/R/data_object.R, instat/static/InstatObject/R/instat_object.R
Added  convert_column_to_type method in instat and data object
=> Convert columns to type

instat/frmEditor.Designer.vb
Added convert to factor on the right click cells @rdstern
=> Added convert to factor on the right click cells

instat/dlgFromLibrary.Designer.vb, instat/dlgFromLibrary.fr-FR.resx, instat/dlgFromLibrary.resx, instat/dlgFromLibrary.sw-KE.resx, instat/dlgFromLibrary.vb, instat/instat.vbproj
Added the dialog for importing data from the libraries. To add functionality later today.
=> Added the dialog for importing data from the libraries. To add functionality later today.

instat/dlgUnstack.Designer.vb, instat/dlgUnstack.vb
This dialog is working.
But for it to work you have to install R- Version 3.2.3 in your computer since 'tidyr' was built under this version. @stevekogo @dannyparsons @maxwellfundi @deaspo @volloholic @nyagishira @rdstern @bethanclarke@live.co.uk
=> Manage menu

instat/instat.vbproj, instat/ucrInputComboBox.Designer.vb, instat/ucrInputComboBox.vb, instat/ucrInputConfidenceLimit.Designer.vb, instat/ucrInputConfidenceLimit.fr-FR.resx, instat/ucrInputConfidenceLimit.resx, instat/ucrInputConfidenceLimit.sw-KE.resx, instat/ucrInputConfidenceLimit.vb, instat/ucrInputTextBox.Designer.vb, instat/ucrInputTextBox.vb
Confidence Limit control still has a bug when number entered is out of range. Not ready to be used yet.
=> updated Input controls, added ConfidenceLimit control

instat/dlgHideShowColumns.Designer.vb, instat/dlgHideShowColumns.fr-FR.resx, instat/dlgHideShowColumns.resx, instat/dlgHideShowColumns.sw-KE.resx, instat/dlgHideShowColumns.vb, instat/dlgProtect.Designer.vb, instat/dlgProtect.fr-FR.resx, instat/dlgProtect.resx, instat/dlgProtect.sw-KE.resx, instat/dlgProtect.vb, instat/dlgRandomSubset.Designer.vb, instat/dlgRandomSubset.fr-FR.resx, instat/dlgRandomSubset.resx, instat/dlgRandomSubset.sw-KE.resx, instat/dlgRandomSubset.vb, instat/dlgRestrict.Designer.vb, instat/dlgRestrict.fr-FR.resx, instat/dlgRestrict.resx, instat/dlgRestrict.sw-KE.resx, instat/dlgRestrict.vb, instat/dlgUnusedLevels.Designer.vb, instat/dlgUnusedLevels.fr-FR.resx, instat/dlgUnusedLevels.resx, instat/dlgUnusedLevels.sw-KE.resx, instat/dlgUnusedLevels.vb, instat/instat.vbproj
Adding New Dialogs for Manage Menu
=> New dialogs

instat/dlgRegressionSimple.resx, instat/dlgRegressionSimple.vb, instat/sdgSimpleRegOptions.Designer.vb, instat/sdgSimpleRegOptions.vb
@dannyparsons @rdstern I have implemented what was proposed for simple regression dialogue but here are a few concerns.
Should the response variable receiver be restricted to non-factor columns? In case of a factor, it returns an error if you intend to display estimates and ANOVA table.
We are still missing implementation of prediction interval for the fitted model in graphics tab. Can Beth send me the code for this?
Lastly, we can run multiple scripts but for graphics, it cannot diaplay multiple plots. What should we do about this?
=> Implementing changes in regression dialogue and subdialogue

instat/dlgRegularSequence.designer.vb, instat/dlgRegularSequence.vb
=> Dlg regular sequence

instat/dlgBoxPlot.designer.vb, instat/dlgBoxPlot.vb, instat/sdgBoxPlot.Designer.vb, instat/sdgBoxPlot.vb
This is almost complele boxplot though as we discussed with @rdstern , the checkboxes will all go to the boxplotoptions subdialog
=> finalised boxplot

instat/dlgRandomSample.designer.vb, instat/dlgRandomSample.vb, instat/dlgRecode.Designer.vb, instat/dlgRecode.vb
I need further discussion on this
=> Tidying u dialogs

instat/static/InstatObject/R/data_object.R, instat/static/InstatObject/R/instat_object.R
Added copy columns and order data frames methods
=> Copy columns and order data frames methods

instat/dlgPolynomials.vb
=> Editing dlgPolynomials

instat/dlgPlot.designer.vb, instat/dlgPlot.vb, instat/dlgScatterPlot.Designer.vb, instat/dlgScatterPlot.vb
These are the @bethanclarke  recommendations to improve theScatterplot
=> Scatterplot tidying

instat/ucrReorder.Designer.vb, instat/ucrReorder.vb
Added everything we discussed, even highlighting when moving up, down, top and bottom
=> user control Reorder

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
Editing and adding new user control
=> Start of Rain Dialog

instat/frmMain.vb
The RDotNet documentation https://rdotnet.codeplex.com/documentation suggests that this line is included.
=> added REngine line

instat/dlgReferenceLevel.Designer.vb, instat/dlgReferenceLevel.vb
=>  dlgReferenceLevel

instat/dlgSplitText.Designer.vb, instat/dlgSplitText.vb
=> dlgSplitText

instat/clsRLink.vb, instat/frmSetupLoading.Designer.vb, instat/frmSetupLoading.fr-FR.resx, instat/frmSetupLoading.resx, instat/frmSetupLoading.sw-KE.resx, instat/frmSetupLoading.vb, instat/instat.vbproj
First attempt at implementing a loading screen. Currently only used when doing the initial setup since this takes several seconds and errors happen if interrupted. Could easily be implemented to appear each time a command is running.
Still to do: menus and forms should be disabled while loading.
=> very basic implementation of loading screen

instat/dlgReorderLevels.Designer.vb, instat/dlgReorderLevels.vb
i have made the designer and code.the diaog is populating the controls but still ot working coz i have not put the function
=> Dlg reorder levels

instat/static/InstatObject/R/Backend_Components/summary_functions.R
Currently produces a data frame of summary results as output only.
=> Initial implementation of summaries

instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
Classes are now converted to R6, in separate files. These need to be tested and are not currently being used by the software
=> Converting to R6 syntax 

instat/dlgView.Designer.vb, instat/dlgView.vb
@africanmathsinitiative/instat. I have also initiated a check if the numeric up down is empty since the user might delete the default value making it empty. @maxwellfundi  I guess this is the reason why you needed a check for your nud
=> ManageMenuEditing

instat/UcrGeomListWithAes.designer.vb, instat/dlgGeneralForGraphics.Designer.vb, instat/ucrGeom.vb
Adjusting the size of the dlggeneral and adding all geoms
=> More work on geoms work

instat/clsRLink.vb, instat/dlgConvertColumns.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R, instat/ucrFactor.vb, instat/ucrReceiver.vb, instat/ucrReorder.vb, instat/ucrSelector.vb, instat/ucrSelectorByDataFrame.vb
Added functionality to include or exclude a number of data types
=> Enhanced options for column types of receiver

instat/dlgReorderSheet.Designer.vb, instat/dlgReorderSheet.vb
=> Implementing dlgReoderSheets

instat/dlgViewDescriptives.Designer.vb, instat/dlgViewDescriptives.vb
FrontEnd design off ViewObject using dlgViewDescriptives
=> Objects Dialogs

instat/frmEditor.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
=> Updated replace value method in R

instat/dlgRestrict.Designer.vb, instat/dlgRestrict.vb, instat/ucrFactor.vb, instat/ucrFilter.Designer.vb, instat/ucrFilter.vb
Dialog doesn't run or link to R yet
=> updated front end of Filter control and added fitler control to Filter dialog

instat/dlgRecodeFactor.Designer.vb, instat/dlgRecodeFactor.vb
=> initial code for RecodeFactor

instat/dlgRandomSubsets.Designer.vb, instat/dlgRandomSubsets.vb
i am still working on the code. i have not touched some controls  yet
=> dlgRandomSubset code

instat/dlgFreezeColumns.Designer.vb, instat/dlgFreezeColumns.resx, instat/dlgFreezeColumns.vb, instat/instat.vbproj
This removes the earlier error naming the addition of the Rownames dialog which is not originally a part of the Freeze Columns Branch.
=> Resubmit freeze columns

instat/clsGeom.vb, instat/dlgCombineText.vb, instat/dlgImportDataset.vb, instat/dlgSplitText.vb, instat/ucrColors.vb, instat/ucrFilter.vb, instat/ucrGeom.vb, instat/ucrInputComboBox.vb, instat/ucrInputConfidenceLimit.vb, instat/ucrLayerParameters.Designer.vb, instat/ucrLayerParameters.vb, instat/ucrLayerParamsControls.vb
@dannyparsons  this changes the AddItems to SetItems as well work for the array of strings for layer parameters. 
It could be merged too.
=> Changing AddItems to SetItems

instat/clsRLink.vb, instat/dlgHideShowColumns.vb, instat/dlgSplitText.vb, instat/static/InstatObject/R/data_object_R6.R, instat/ucrReceiver.vb, instat/ucrReceiverMultiple.vb, instat/ucrReceiverSingle.vb, instat/ucrSelector.vb
The Hiding and unhiding of columns is done fine but the major problem is that whenever new data is loaded and the dialog is run for the first time it fails to close.
=> Manage menu editing

instat/dlgRownamesOrNumbers.Designer.vb, instat/dlgRownamesOrNumbers.resx, instat/dlgRownamesOrNumbers.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
Danny I would like you to have a look at this for me, I haven't gotten it to work well yet. Use your usual questioning and pointers that should be helpful, thanks.
=> Dialogue for Rownames/Numbers. Not fully functional yet.

instat/UcrGeomListWithAes.designer.vb, instat/UcrGeomListWithAes.vb, instat/clsRFunction.vb, instat/clsROperator.vb, instat/clsRParameter.vb, instat/dlgBoxPlot.designer.vb, instat/dlgBoxPlot.vb, instat/dlgGeneralForGraphics.Designer.vb, instat/dlgGeneralForGraphics.vb, instat/dlgUseGraph.vb, instat/frmMain.Designer.vb, instat/sdgLayerOptions.vb, instat/sdgPlots.vb, instat/ucrDataFrame.vb, instat/ucrGeom.vb, instat/ucrSelectorByDataFrame.vb
@dannyparsons This is still underway. Will let you know when its done. thank s
=> More work on general graphics 

instat/dlgDummyVariables.Designer.vb, instat/dlgDummyVariables.vb
@dannyparsons i had used ucrinput here to write back to dataframe before notising we had to remove it.
I will finish up remaining bit on Monday
=> dlgDummyVariables

instat/clsROperator.vb, instat/dlgThreeVariablesModelling.Designer.vb, instat/dlgThreeVariablesModelling.vb, instat/sdgVariableTransformations.vb
Fixing the link to variable transformation subdialogue
=> Three variable modelling

instat/instat.vbproj
@deaspo This was causing the software to crash due to the Recent_Files directory not existing. Added blank .mru file to ensure directory always exists.
=> added default recent.mru file to ensure directory exists in project

instat/dlgMerge.Designer.vb, instat/dlgMerge.vb, instat/static/InstatObject/R/data_object_R6.R, instat/ucrSelector.vb, instat/ucrSelectorByDataFrame.vb, instat/ucrSelectorByDataFrameAddRemove.vb
Currently only works for one key variable and bug with by parameter sometimes not generated properly.
=> added code and design to merge dialog

instat/dlgColumnStructures.Designer.vb, instat/dlgColumnStructures.fr-FR.resx, instat/dlgColumnStructures.resx, instat/dlgColumnStructures.sw-KE.resx, instat/dlgColumnStructures.vb, instat/instat.vbproj
Implemented vb code
@dannyparsons  i would like you to merge this before i finish up
=> Creating dlgColumnStructure.

instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb
This is design for standard structure
=> Redesigning dlgCalculation

instat/dlgSort.vb, instat/static/InstatObject/R/Rsetup.R, instat/static/InstatObject/R/data_object_R6.R
This now does not preserve row names as described here #1586
=> fixed bugs in sort code and dialog

instat/clsGridLink.vb, instat/clsRLink.vb, instat/dlgCalculator.vb, instat/dlgFromLibrary.vb, instat/dlgRegularSequence.vb, instat/static/InstatObject/R/instat_object_R6.R, instat/ucrFactor.vb
bugs expected as lots of internal code has changed
=> changed how internal R code runs

instat/clsRLink.vb, instat/dlgBarAndPieChart.vb, instat/dlgBoxPlot.vb, instat/dlgCombineforGraphics.vb, instat/dlgCumulativeDistribution.vb, instat/dlgDotPlot.vb, instat/dlgHistogram.vb, instat/dlgPlot.vb, instat/dlgScatterPlot.vb, instat/dlgSummaryBarOrPieChart.vb, instat/sdgCombineGraphOptions.vb, instat/sdgPlots.vb, instat/ucrAdditionalLayers.vb, instat/ucrAxes.vb
Setting default number of rowns and columns for dlgCombineforGraphics
=> Setting default number of columns and rows

instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb
=> calculations dialog

instat/dlgColourbyProperty.Designer.vb, instat/dlgColourbyProperty.vb, instat/frmMain.Designer.vb
Creating color by property dialog
=> Editsonmanage

instat/dlgOpenSST.Designer.vb, instat/dlgOpenSST.fr-FR.resx, instat/dlgOpenSST.resx, instat/dlgOpenSST.sw-KE.resx, instat/dlgOpenSST.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
Created the dialog and made changes in the frmMain
=> Creating dlgOpenSST

instat/dlgFitModel.Designer.vb, instat/dlgFitModel.fr-FR.resx, instat/dlgFitModel.resx, instat/dlgFitModel.sw-KE.resx, instat/dlgFitModel.vb, instat/instat.vbproj
Hi,
You can merge this before we continue adding more controls
=> General dialog for fit model

instat/frmEditor.vb, instat/frmMetaData.vb, instat/frmVariables.vb, instat/ucrFactor.vb
=> fixed bugs with delete key and deleting cells, editing cells in grids

instat/dlgCalculator.vb, instat/dlgRank.vb
TestOKEnabled amended on both
For Calculator:
Try is now disabled
The new column name cannot have spaces in it
=> Rank and Calculator Dialogs Amended

instat/dlgImportFromODK.Designer.vb, instat/dlgImportFromODK.vb, instat/frmMain.Designer.vb, instat/frmMain.vb
Hi @dannyparsons  
I need some help on how to run internal r code to get form names into the combobox since i am not understanding this part
=> Adding code to import from odk dialog

instat/dlgImportFromODK.Designer.vb, instat/dlgImportFromODK.vb
=> Editing dlgImportfromOdk

instat/dlgCopySheet.Designer.vb, instat/dlgCopySheet.vb, instat/dlgDeleteDescriptive.Designer.vb, instat/dlgDeleteSheet.Designer.vb, instat/dlgMerge.vb, instat/dlgRenameDescriptive.Designer.vb, instat/dlgRenameSheet.Designer.vb, instat/dlgRenameSheet.vb, instat/dlgRestrict.Designer.vb, instat/dlgStack.vb, instat/dlgTransposeColumns.Designer.vb, instat/dlgTransposeColumns.vb, instat/dlgViewDescriptives.Designer.vb
Sorted out dialog designs for
Transpose
Rename Data Frame
Copy Data Frame
Delete Data Frame
R Objects - View
R Objects - Rename
R Objects - Delete
OKEnabled on some of these too
=> Dialog Designs

instat/dlgEnter.Designer.vb, instat/dlgEnter.resx, instat/dlgEnter.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
Done with the design of the new dialogue Enter. I have made single keyboard but am yet to add the the four sort methods plus additional back end codes now with the help of John.
=>  New Enter dialogue

instat/dlgOneVarUseModel.Designer.vb, instat/dlgOneVarUseModel.resx, instat/dlgOneVarUseModel.vb, instat/frmEditor.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj, instat/ucrAxes.Designer.vb, instat/ucrAxes.vb
Changed some small things in the main form - added in the next dialog (Use Model) although haven't started this yet. Just wanted to add it in right away to avoid conflicts!
Also, added in the 'comment' for changing values
And for axes, it now has 'interval' as the default
=> Axes options and Form Alterations

instat/dlgTablePlus.Designer.vb, instat/dlgTablePlus.fr-FR.resx, instat/dlgTablePlus.resx, instat/dlgTablePlus.sw-KE.resx, instat/dlgTablePlus.vb, instat/instat.vbproj
@dannyparsons 
You can merge this before i proceed to make more changes
=> Creating dlgTablePlus

instat/dlgTablePlus.Designer.vb, instat/dlgTablePlus.vb, instat/frmMain.Designer.vb, instat/frmMain.vb
@dannyparsons  This is now okay for now
=> Dlg tables plus

instat/dlgOneVariableGraph.vb, instat/sdgOneVarGraph.Designer.vb, instat/sdgOneVarGraph.vb
=> Additions to onevariable

instat/dlgMakeDate.Designer.vb, instat/dlgMakeDate.vb
=> Edits on dialogs

instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb
Need to fix something before it is ready
=> Editing calculator

instat/sdgOneVarFitModDisplay.vb
To fit model - I altered the code slightly for the subdialog. It runs well still, so hopefully is okay!
=> One var comp or use

instat/dlgCanonicalCorrelationAnalysis.Designer.vb, instat/frmMain.Designer.vb, instat/frmMain.vb
=> Decsribe menu

instat/frmMain.Designer.vb, instat/frmMain.vb
=> Menu climatic

instat/dlgOneVariableGraph.vb, instat/sdgOneVarGraph.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
=> Additions on Onevariable

instat/clsRSyntax.vb
Also reordered some subs to make the comments and changed SetFunction as discussed..
=> Explanatory comments in clsRSyntax

instat/dlgOneVariableGraph.vb, instat/sdgOneVarGraph.vb
=> Edits on Onevariable

instat/dlgCountinFactor.vb
=> Adding help id for count in factor

instat/clsRSyntax.vb, instat/dlgColumnStructures.vb, instat/ucrButtons.vb, instat/ucrSelectorByDataFrame.vb
Some minor changes mainly in dlgColumnStructures and ucrSelectorByDataframe, see commits for comments
=> Debug exercise and other commenting

instat/clsRFunction.vb, instat/clsROperator.vb, instat/clsRSyntax.vb, instat/dlgGeneralForGraphics.vb, instat/sdgLayerOptions.vb, instat/ucrAdditionalLayers.vb, instat/ucrGeom.vb
I have inserted a few questions as comments. If you can request changes I will convert these into explanations as soon as I get answers ;) 
+ some other minor changes mainly in SetDefault procedures
=> Some questions and small commits

instat/dlgRugPlot.Designer.vb, instat/dlgRugPlot.resx, instat/dlgRugPlot.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
Created RugPlot dialogue and reorganised mainframe, hopefully as suggested by Roger.
=> Geom rug implementation

instat/dlgContrasts.Designer.vb, instat/dlgContrasts.vb
Initial design for contrast dialog addressing #1838
=> Contrast dialog

instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb, instat/ucrButtons.vb
@dannyparsons  We have discussed with @maxwellfundi  and edited ucrBase control to ensure the help for each group is working fine.
=> Dlg calculator

instat/My Project/Resources.Designer.vb, instat/My Project/Resources.resx, instat/ucrDistributions.vb
=> Distributions

instat/dlgTablePlus.Designer.vb, instat/dlgTablePlus.vb
=> dlgTablePlus

instat/dlgExportToOpenRefine.resx
Hello Danny, had not located the resource file... it was hidden in the untracked files. Kindly merge it too. The latest version bugging.
=> Resource file- Dlg Open Refine

instat/dlgCorrelation.designer.vb, instat/dlgCorrelation.vb, instat/dlgPrincipalComponentAnalysis.Designer.vb, instat/dlgPrincipalComponentAnalysis.vb, instat/sdgCorrPlot.Designer.vb, instat/sdgCorrPlot.vb, instat/sdgPrincipalComponentAnalysis.Designer.vb, instat/sdgPrincipalComponentAnalysis.vb
This can be merged as I am not looking at it again until tomorrow. However, I will be working on it much more tomorrow
=> Correlations and PCA

instat/dlgContrasts.Designer.vb, instat/dlgContrasts.vb
It is now working okay but i have a question on how we can overwrite existing contrast columns using the checkbox ?
=> Dlg contrast

instat/dlgCorrelation.vb, instat/dlgPrincipalComponentAnalysis.vb, instat/sdgCorrPlot.Designer.vb, instat/sdgCorrPlot.vb, instat/sdgPrincipalComponentAnalysis.Designer.vb, instat/sdgPrincipalComponentAnalysis.vb
=> Corr and p

instat/frmMain.Designer.vb, instat/frmMain.vb
Two changes,
Dis-enabling ColumnDate submenus that have not been implemented
Connecting the export and import to openRefine dlgs to the formain as well.
=> FrmMain changes

instat/dlgBoxPlot.vb, instat/ucrSaveGraph.vb
Adding code to enable okay appropriately and reseting the ucrsavegraph
=> Savegraphreset and TestOkEnabled

instat/dlgEnter.Designer.vb, instat/dlgEnter.vb
Dlg Enter (Not Date).
Added a preview pane on the design. Looking how I will implement that if the design is OK.
=> Dlg Enter 

instat/dlgMakeDate.vb
The two commits are similar with a difference in order of code execution. Last one sounds better to me.
=> Make date dlg

instat/clsGridLink.vb, instat/dlgConvertColumns.vb, instat/dlgOneVariableGraph.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R, instat/ucrDataFrame.vb, instat/ucrReceiver.vb, instat/ucrReceiverMultiple.vb
=> initial attempt to include ordered factors, including on one variable graph dialog & method, fixed bug with dialog designers loading

instat/dlgReorderColumns.Designer.vb
Changed layout - added a colon etc,
=> Dlg reorderColumns

instat/dlgDeleteRowsOrColums.Designer.vb, instat/dlgDeleteRowsOrColums.vb
Ready to be merged.
Sorry it's in three commits - I kept getting an error along the lines of UInt32 is too large or small whenever I tried to merge so I restarted VB and sent my changes in regular commits to find the issue. It worked the second time so must've been an issue with VB or something
=> Dlg delete

instat/ucrReceiverSingle.vb, instat/ucrVariablesAsFactor.vb
this fixes the bug which gave an error when variables were in both the multiple receiver and another receiver on the dialog
=> fixed bug in variables as factor control

instat/dlgBoxPlot.vb, instat/sdgLayerOptions.vb
This is a temporary fix to #1874
=> temp disabled options from boxplot when multiple y

instat/dlgRestrict.vb, instat/sdgCreateFilter.Designer.vb
Hid "New Data Frame Name". Made sdg Centre Screen default
=> dlgRestrict, 

instat/clsGridLink.vb, instat/frmEditor.vb
fixes part of #2045 related to freezing
=> temp disabled freezing

instat/dlgMetadata.Designer.vb, instat/dlgMetadata.vb
=> dlgMetadata

instat/ucrVariablesAsFactor.vb
@lilyclements this should fix the issue you saw on graph dialogs. Almost the same solution but done in the user control so it's only added one.
=> vars as factor controls sets current receiver when changing mode

instat/dlgContrasts.Designer.vb, instat/dlgContrasts.vb
I assume someone is working on this at the moment?
The chkbox isn't referred to at all in the dialog so should I disable it for now?
=> Contrasts layout edited

instat/UcrGeomListWithAes.vb
Added a bug tracker in ucrGeomListWithAes in order to solve #2147 later...
=> Ucr geom list with aes

instat/frmMain.Designer.vb
=> Disabled unused dialogs

instat/dlgFourVariableModelling.Designer.vb
=> Dlg four var mod

instat/dlgFromLibrary.Designer.vb
=> dlgFromLibrary

instat/dlgShowModel.Designer.vb, instat/dlgShowModel.vb
Editing the dlgShowModels 
@rdstern  fixed 1, 2 & 3 on #1905
=> Bugs fixing

instat/frmMain.Designer.vb, instat/frmMain.vb
=> Adding features on help menu

instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
@dannyparsons  please have a look at this so that @stevenndungu  can start working on the dialog
=> Adding split_Date Method

instat/clsRCodeStructure.vb, instat/clsRFunction.vb, instat/clsRLink.vb, instat/clsROperator.vb, instat/clsRSyntax.vb, instat/dlgCalculator.vb, instat/dlgEnter.vb, instat/dlgOneVariableGraph.Designer.vb, instat/dlgOneVariableGraph.vb, instat/instat.vbproj, instat/mdlCoreControl.vb, instat/sdgOneVarGraph.Designer.vb, instat/sdgOneVarGraph.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R, instat/ucrCheck.vb, instat/ucrCore.vb, instat/ucrDataFrame.Designer.vb, instat/ucrDataFrame.vb, instat/ucrInput.vb, instat/ucrInputComboBox.vb, instat/ucrNud.Designer.vb, instat/ucrNud.resx, instat/ucrNud.vb, instat/ucrRadio.vb, instat/ucrReceiver.vb, instat/ucrReceiverSingle.vb, instat/ucrSelectorByDataFrame.vb
New class: RCodeStructure which RFunction and ROperator inherit from and shifted some duplicate code into RCodeStructure
Added code to new user controls for nud, checkbox etc.
Started to get new dialog reading implemented on One Variable Graph dialog + sub dialog
=> New implementation of dialog reading/sub dialog linking

instat/clsDistribution.vb, instat/dlgOneVarFitModel.vb, instat/dlgOneVarFitModel2.Designer.vb, instat/dlgRegressionSimple.Designer.vb, instat/dlgRegressionSimple.resx, instat/dlgRegressionSimple.vb, instat/ucrDistributions.vb
This can be reviewed.
There are still many bugs here, however, I have fixed one. We can now do Bernouli, Normal or Poisson tests.
Altered the selector so that the correct data type can be selected.
=> Hyp Tests for Two Variables

instat/dlgInventoryPlot.designer.vb, instat/dlgInventoryPlot.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
@dannyparsons @stevekogo  has been in testing of this and we think its now ready. 
Please have a look.
=> Inventory Plot 

instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R, instat/static/InstatObject/R/stand_alone_functions.R
@africanmathsinitiative/instat  this is ready for review.
=> Split date method

instat/dlgContrasts.Designer.vb, instat/dlgContrasts.vb, instat/ucrInputComboBox.vb
The dialog is completely done. 
I would request @lilyclements  to help in reviewing
=> Implementing contrasts dialog

instat/dlgReplace.Designer.vb
=> dlgReplace

instat/dlgConvertColumns.Designer.vb
Convert Columns - Made small additions
=> Convert cols

instat/ucrSelectorAddRemove.designer.vb
This is the ucrSelectorAddRemove (without the dataframe). I changed the size of the list/etc so that it is consistent with the ucrSelectorByDataFrameAddRemove list part.
=> ucrSelectorAddRemove

instat/dlgDescribeTwoVariable.Designer.vb, instat/sdgDescribeDisplay.Designer.vb
=> Describe two var

instat/dlgPolynomials.Designer.vb, instat/dlgPolynomials.vb
=> Polynomial

instat/dlgFileNew.Designer.vb, instat/dlgFromLibrary.Designer.vb
=> dlgFileNew

instat/dlgAppend.Designer.vb, instat/dlgDeleteDescriptive.Designer.vb, instat/dlgReoderDescriptives.Designer.vb, instat/dlgStack.Designer.vb
Changed titles - capitals, Data Frame with a space, etc
=> A few organise menu titles

instat/dlgDeleteRowsOrColums.Designer.vb, instat/dlgDeleteRowsOrColums.vb
Sorted layout, default options
=> Delete rows or columns

instat/dlgCorrelation.vb, instat/sdgCorrPlot.Designer.vb, instat/sdgCorrPlot.vb
Small additions;
Added to defaults
Changed OK Enabled
Ready for review
=> Dlg correlation

instat/dlgPermuteColumn.Designer.vb, instat/dlgPermuteColumn.vb
This is not giving any output. This was an issue prior to changing NUDs.
Should I add this to the issues page? I'm not sure how we have the output calculated
=> Permute columns

instat/dlgRegularSequence.designer.vb
=> dlgRegularSequence

instat/frmMain.Designer.vb, instat/frmMain.vb
=> Restructuring frmMain

instat/clsRLink.vb, instat/clsRParameter.vb, instat/dlgCalculationsSummary.Designer.vb, instat/dlgCalculationsSummary.vb, instat/sdgCalculationsSummmary.Designer.vb, instat/sdgCalculationsSummmary.vb, instat/static/InstatObject/R/Backend_Components/calculations.R, instat/ucrFilter.vb, instat/ucrInputComboBox.vb
Fixed bugs in:
calculator user control
cloning RParameter
filter control and dialog
=> Working version of general summaries dialog and added sort option to summaries plus bug fixes

instat/dlgInfill.Designer.vb, instat/dlgInfill.resx, instat/dlgInfill.vb, instat/instat.vbproj
=> New dlgInfill

instat/dlgAddComment.vb, instat/dlgAddLink.vb, instat/dlgViewAndRemoveLinks.vb, instat/frmMain.Designer.vb, instat/frmMain.vb
Had a duplicate Help ID on 3 dialogues (a mistake)
=> Editing HelpIDs & Menu Changes (Mainly Climatic)

instat/dlgView.Designer.vb, instat/dlgView.vb
Making OK Enabled and nud to be functional
=> Fixing bugs on view dialog

instat/ucrInput.vb, instat/ucrInputTextBox.vb
@dannyparsons 
Is this fine or should implement it with a function?
=> Multiline textbox method

instat/dlgInventoryPlot.designer.vb, instat/dlgInventoryPlot.vb, instat/ucrNud.vb
@dannyparsons this is a trial for the new linking system. A couple of things we might need to discuss. 
Could you go through this and give some comments?
=> Inventoryplot with new linking system

instat/dlgConvertColumns.Designer.vb, instat/dlgConvertColumns.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
=> Convert factors setting the default digits

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
Redesigning start of rains dialog
@lilyclements  this is now the final design
=> Start of rains 

instat/dlgFreezeColumns.Designer.vb, instat/dlgFreezeColumns.vb, instat/dlgViewAndRemoveKeys.vb
@africanmathsinitiative/instat  this is ready for review
=> DlgFreezecolumns

instat/dlgAppend.vb
Reupdated with fixed code, should be correct now
=> Append dialog

instat/DlgUseDate.Designer.vb, instat/DlgUseDate.vb
@africanmathsinitiative/instat Ready for review
=> Dlg use date

instat/dlgCombine.Designer.vb, instat/dlgCombine.vb
@africanmathsinitiative/instat this is ready for testing/review
=> Combine factors dialog

instat/dlgViewDescriptives.Designer.vb, instat/dlgViewDescriptives.vb
@africanmathsinitiative/instat  this is ready for review.
This is as functional (to my knowledge) as the old-coded version. That is, three radio buttons are disabled as they were before and I am unaware of the function/parameters which are planned to be inputted for the radio buttons.
This works as well as the previous version, however. (Or, it should)
=> Dlg view descriptive

instat/dlgFactorDataFrame.Designer.vb, instat/dlgFactorDataFrame.vb
@africanmathsinitiative/instat  this is ready for review
=> Dlg factor data frame

instat/dlgColumnStructures.Designer.vb, instat/dlgColumnStructures.vb
=> Column structures

instat/dlgName.Designer.vb, instat/dlgName.vb
I ma still figuring out why new_val can not be passed as string
=> Rename column Rewrite

instat/mdlCoreControl.vb, instat/ucrReceiver.vb, instat/ucrReorder.Designer.vb, instat/ucrReorder.vb
@africanmathsinitiative/developers This updates the Reorder control to make it a core control. You may want to see what has been added to the control to enable it to work in our new system, if you are interested in knowing about this.
=> updated reorder control as core control

instat/dlgAddKey.Designer.vb, instat/dlgAddKey.vb
@lilyclements  So how did you resolve the resetting of the ucrinputs in your previous problem you earlier told me. The reset here does work so well for the ucrinput
=> updating dlgAddkey

instat/dlgCumulativeDistribution.Designer.vb, instat/dlgCumulativeDistribution.vb, instat/frmMain.Designer.vb, instat/frmMain.vb
@stevekogo you might want to have a look at this.
=> Adding Cumulative/Exceedance Graphs to SCF

instat/dlgExportToOpenRefine.vb
@dannyparsons This is ready to merge
=> Removing Commented Line

instat/dlgWindrose.Designer.vb, instat/dlgWindrose.vb
@stevekogo  have a look at this, its the edits form our previous discussions. 
Thanks
=> Edits for windrose

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
@dannyparsons This is ready to be merged
=> Start of Rains Dialog - Merge

instat/frmMain.Designer.vb, instat/static/InstatObject/R/data_object_R6.R
These new methods mean the define corruption dialog is broken. I will resolve this soon.
=> Added corruption methods in instat object and added corruption menu items

instat/instat.vbproj, instat/sdgCorruptionCalculatedColumns.Designer.vb, instat/sdgCorruptionCalculatedColumns.resx, instat/sdgCorruptionCalculatedColumns.vb, instat/sdgCorruptionCountryLevelColumns.Designer.vb, instat/sdgCorruptionCountryLevelColumns.resx, instat/sdgCorruptionCountryLevelColumns.vb
@dannyparsons here are two empty sub dialogs for merging. I'll work on them once they're merged
=> DlgDefineCorruption

instat/dlgOneWayFrequencies.resx
this resource file was missed out (in untracked files) @dannyparsons
=> DlgFrequencies

instat/dlgDrySpells.Designer.vb, instat/dlgDrySpells.vb, instat/dlgNewSummaryTables.Designer.vb, instat/dlgNewSummaryTables.resx, instat/dlgNewSummaryTables.vb, instat/dlgRatingScales.Designer.vb, instat/dlgRatingScales.resx, instat/dlgRatingScales.vb, instat/dlgTwoWayFrequencies.Designer.vb, instat/dlgTwoWayFrequencies.resx, instat/dlgTwoWayFrequencies.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
@dannyparsons  this is the New Summary tables dialogue designer and the basic codes,I think it's ready to be merged.
=> New summary tables

instat/frmMain.Designer.vb, instat/frmMain.vb
@dannyparsons I had forgot to add dlgOpenNetCDF to the frmmain but I have done it now,please merge it for @stevekogo needs it.
=> Adding OpenNetCDF to frmMain

instat/frmMain.Designer.vb, instat/frmMain.vb
@dannyparsons This was requested by @rdstern .
Please have it merged.
=> Swapping menu items

instat/dlgDefineCorruptionOutputs.Designer.vb, instat/dlgDefineCorruptionOutputs.vb
This is ready for review @africanmathsinitiative/developers
=> Dlg output corruption

instat/dlgFitCorruptionModel.vb
@africanmathsinitiative/developers  This is ready for review.
=> Dlg fit corruption model

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
=> Start of rains

instat/dlgStartofRains.vb
@dannyparsons Here is another small bug fix that Roger has pointed out this morning. I'm not sure if this will get into the new version. This more prevents an inconvenience from occurring than a crash so isn't as important. Fixes #2813
=> Small Bug Fix

instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
=> fixed bugs with links

instat/dlgStandardiseCountryNames.vb
@dannyparsons  I think this works well.
=> Standardise Country Names

instat/frmMain.Designer.vb, instat/frmMain.vb
@dannyparsons this is ready as well
=> Enabling standardise

instat/dlgRecodeNumericIntoQuantiles.Designer.vb, instat/dlgRecodeNumericIntoQuantiles.resx, instat/dlgRecodeNumericIntoQuantiles.vb, instat/instat.vbproj
=> Recode Numeric into Quantiles

instat/dlgWaterBalance.Designer.vb, instat/dlgWaterBalance.vb
=> Dlg water balance

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
=> Dlg start of rains

instat/dlgSpells.Designer.vb, instat/dlgSpells.vb
@rdstern I have added in column names to this dialog. The following shows the
Year, Default-Name and then some names I added in to get multiple columns on the sheet.
Is this what you had in mind?
Similarly this has been implemented on #2838
=> Dlg spells

instat/frmMain.Designer.vb, instat/frmMain.vb
@africanmathsinitiative/developers This should probably (definitely) be looked at/reviewed before anyone plans to do any work to the frmmain
This is ready for review
Changes include:
- Enabled and linked in dlgRecodeNumericIntoQuantiles
- Changed "mange" to "manage"
- Deleted replicate handles (explained better below)
=> Main Form Changes

instat/dlgRowStats.Designer.vb, instat/dlgRowStats.vb
@africanmathsinitiative/developers This is ready for review. There are very minor changes
- Layout
- Tab Order
- Changed the name to Row Summaries from Row Statistics. The name on the main form is Row Summary and I think this encapsulates it better. Perhaps others will disagree. Let me know.
- Updated SetDefaults() code
=> Dlg row stats

instat/instat.vbproj, instat/sdgOneWayFrequencies.Designer.vb, instat/sdgOneWayFrequencies.vb
@dannyparsons this ready for you
=> Sdg one way freq

instat/dlgLabels.vb, instat/ucrFactor.vb
=> fixed bug in levels labels dialog

instat/dlgColumnStats.Designer.vb, instat/dlgColumnStats.vb
Very minor changes:
* Layout Design
* Tidied the code
=> Dlg column stats

instat/clsGridLink.vb, instat/ucrColumnMetadata.Designer.vb, instat/ucrDataFrameMetadata.Designer.vb, instat/ucrDataFrameMetadata.vb, instat/ucrDataView.Designer.vb, instat/ucrLog.Designer.vb, instat/ucrOutputWindow.Designer.vb, instat/ucrScript.Designer.vb
I changed from the green to the blue that R uses
=> Changed the green to blue

instat/dlgRandomSample.designer.vb, instat/dlgRandomSample.vb
Fixes #2893 
@PatrykNjoroge  This is now okay for your use
=> Fixing Random Samples bug

instat/dlgStringHandling.Designer.vb, instat/dlgStringHandling.resx, instat/dlgStringHandling.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
@dannyparsons .This is ready for you.
=> Dlg string handling

instat/dlgPermuteColumn.vb
I have made changes to this dialogue,I think it's now updated. @africanmathsinitiative/developers Can some one review it.
=> Permute Column New Implementation.

instat/dlgViewAndRemoveKeys.Designer.vb, instat/dlgViewAndRemoveKeys.vb
@dannyparsons This is ready for you to review.
It was reviewed in #2596 a month or so ago, and I've made some final small changes.
=> dlg View and Remove keys

instat/dlgTransposeColumns.Designer.vb, instat/dlgTransposeColumns.vb
Changes:
- Updated the SetDefaults()
- Fixed developer error for a disabled control
- Sorted layout
=> Dlg transpose text

instat/dlgRestrict.Designer.vb, instat/dlgRestrict.vb
In progress
Edit @africanmathsinitiative/developers this is ready for review
=> Filter bug

instat/static/InstatObject/R/instat_object_R6.R
=> prevented renaming an existing data frame

instat/dlgSaveAs.vb
=> add saved rds file to recent files

instat/frmMain.Designer.vb
@dannyparsons .kindly merge this changes on the frmMain
=> Frm main edits

instat/dlgFactorLabels.Designer.vb, instat/dlgFactorLabels.resx, instat/dlgFactorLabels.vb, instat/instat.vbproj
=> View Factor Labels Empty Dialog

instat/dlgStringDistance.Designer.vb, instat/dlgStringDistance.resx, instat/dlgStringDistance.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
@AlexSananka Kindly review this empty dialog.
=> dlgStringDistanceEmptyDialog

instat/dlgDefineCRI.Designer.vb, instat/dlgDefineCRI.vb, instat/dlgDefineRedFlags.Designer.vb, instat/dlgStandardiseCountryNames.Designer.vb, instat/dlgStandardiseCountryNames.vb
These are very _very_ minor changes I made over the weekend. I have only tidied up:
* DefineCRI
* DefineRedFlags
* StandardiseCountryNames
So this should be a very quick review!
=> Tidying up some Corruption Dialogs

instat/dlgConvertColumns.Designer.vb, instat/dlgConvertColumns.vb
Here I 
* Sorted the layout
* Tab order
* Added in a new checkbox "Keep Attributes"
=> dlgConvertColumns - adding checkbox

instat/dlgExportGraphAsImage.Designer.vb, instat/dlgExportGraphAsImage.resx, instat/dlgExportGraphAsImage.vb, instat/instat.vbproj
@maxwellfundi Kindly check at this empty dialog for merging.
=> Dlg export graph as image

instat/dlgViewGraph.Designer.vb, instat/dlgViewGraph.resx, instat/dlgViewGraph.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
@dannyparsons this is ready for you
=> Dlg ViewGraph (Vbproj and FrmMainChanges)

instat/UcrPanel.vb, instat/dlgTwoWayFrequencies.Designer.vb, instat/dlgTwoWayFrequencies.vb, instat/sdgTwoWayFrequencies.vb, instat/ucrCheck.vb, instat/ucrCore.vb, instat/ucrDataFrame.vb, instat/ucrInput.vb, instat/ucrNud.vb, instat/ucrReceiver.vb, instat/ucrReorder.vb, instat/ucrSelectorByDataFrame.vb
In progress- few things to be sorted out.
=> Two Way Frequencies

instat/dlgExportGraphAsImage.Designer.vb, instat/dlgExportGraphAsImage.vb, instat/frmMain.vb
This needs a bit more discussion when @dannyparsons gets here about how we want to save the graphs.
=> dlgExportgraphasimage

instat/dlgViewGraph.Designer.vb, instat/dlgViewGraph.vb
=> DlgView graph

instat/ucrWPFRichTextBox.xaml.vb
@africanmathsinitiative/developers I added a feature on output window to scroll to the end, when content is added. 
Its ready for review as it would be good to have this on todays version
=> Scroll to end feature on Ouputwindow

instat/dlgRegressionSimple.vb
@africanmathsinitiative/developers  this is ready for review. Fixed the bug
=> Two Sample T_Test

instat/dlgImportFromODK.Designer.vb, instat/dlgImportFromODK.vb
After showing this dialog today I noticed a few things to change. Here I have:
* Changed radio buttons to button buttons
* Tidied dialog
* Moved code around a bit
* Potential issue fix? Outlined below
=> dlgImportFromODK - Tidy up

instat/frmMain.Designer.vb, instat/frmMain.vb
=> Frmmain edits

instat/dlgPermuteColumn.Designer.vb, instat/dlgPermuteColumn.vb
@dannyparsons This is ready for you to merge. I made layout/design changes, explained below
=> dlgPermute Design Changes

instat/dlgOneWayFrequencies.vb
@dannyparsons please merge this,it solve the ucrSave issue
=> ucrSave Reset

instat/dlgExportRWorkspace.vb
@dannyparsons I have made the minor edits on this dialog as agreed on #3012
=> Export r workspace

instat/dlgOneWayFrequencies.vb, instat/sdgOneWayFrequencies.Designer.vb, instat/sdgOneWayFrequencies.vb
@dannyparsons  I have made the minor edits here,You can merge this.
=> OneWay bug fix

instat/dlgRegularSequence.vb
@lilyclements  This is ready,you can maybe test it and it can be merged.
=> regular sequence fix

instat/dlgImportDataset.vb
fixes #3058 This was caused by a recently introduced bug in `rio` which I will report.
=> fixed bug in Excel import

instat/dlgBarAndPieChart.vb, instat/dlgBoxPlot.vb, instat/dlgDotPlot.vb, instat/dlgHistogram.vb, instat/dlgLinePlot.vb, instat/dlgRugPlot.vb, instat/dlgScatterPlot.vb, instat/dlgSummaryBarOrPieChart.vb, instat/dlgUseGraph.vb
@africanmathsinitiative/developers its ready for review
This contains changes on prefixes on plots dialogs, no functionality has been added.
=> tidying up graphs prefixes for consistency 

instat/dlgInsertColumn.Designer.vb
@dannyparsons this is ready to merge. I made the incredibly minor edit of fixing the size of this is dialog. It was about double the length.
I wanted to make this now because I know they're working on a script for the dialog so want it to look okay for the video
=> Insert col row

instat/dlgThreeVariablesModelling.vb
@africanmathsinitiative/developers  this is ready for review. Fixes #3088
=> Three Variable modelling Dialogue

instat/dlgDisplayDailyClimaticData.Designer.vb, instat/dlgDisplayDailyClimaticData.resx, instat/dlgDisplayDailyClimaticData.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
@dannyparsons This is ready for you to merge.
=> Display of daily climatic data

instat/dlgDescribeTwoVarGraph.Designer.vb, instat/dlgDescribeTwoVarGraph.vb
@dannyparsons this is ready to be merged
Minor edits:
- moved the label so that it is in a better position for the video
- added colon to the label
- removed the ellipsis from the Options button to be consistent across the software
=> Two var graph

instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
=> added shift day/year R code

instat/frmMain.vb
resolves issue with previous option file causing bug
=> renamed options file

instat/static/ClimateObject/R/BackendComponents/DateManipulationMethods.R, instat/static/InstatObject/R/data_object_R6.R
Here I have changed about six lines in the data_object_R6.R file and also in the DataManipulationsMethods file.
This is to add lubridate:: to fix any bugs of missing this package.
I'm hoping this won't cause any additional conflicts since Danny made similar changes here yesterday and they have been merged.
@dannyparsons this is ready to merge.
=> fixing is.Date lubridate issue

instat/dlgStartofRains.vb
@stevekogo can you confirm if merging this will not cause any conflicts for you? I have been told you're planning to work on this from next week. I wanted to fix these bugs for Friday's version, however.
=> Start of Rains - adding package

instat/dlgPrincipalComponentAnalysis.vb
This dlg is not yet updated. Added the package name.
=> Adding package name for PCA

instat/UcrGeomListWithAes.designer.vb, instat/UcrGeomListWithAes.vb, instat/dlgBarAndPieChart.vb, instat/dlgBoxPlot.vb, instat/dlgDotPlot.vb, instat/dlgGeneralForGraphics.vb, instat/dlgHistogram.vb, instat/dlgLinePlot.vb, instat/dlgMetadata.vb, instat/dlgRugPlot.vb, instat/dlgScatterPlot.vb, instat/dlgSummaryBarOrPieChart.vb, instat/sdgLayerOptions.Designer.vb, instat/sdgLayerOptions.vb, instat/ucrAdditionalLayers.vb, instat/ucrColors.vb, instat/ucrCore.vb, instat/ucrGeom.designer.vb, instat/ucrGeom.vb, instat/ucrInputComboBox.vb, instat/ucrLayerParameters.vb, instat/ucrLayerParamsControls.Designer.vb, instat/ucrLayerParamsControls.vb, instat/ucrReceiver.vb, instat/ucrReceiverMetadataProperty.Designer.vb, instat/ucrReceiverMetadataProperty.vb, instat/ucrReceiverSingle.vb
This is working but needs severe testing. 
Note:
- General dialog is linked the plot options sub dialog but not fully working - this will be resolved when plot options is working correctly
- Design tidying is needed on controls and dialogs, including titles and text for labels
- Need to decide on language we use in R-Instat related to ggplot e.g. layers, geoms, aesthetics
- It is possible to get an error with the general graphics as anything is allowed - we need to at least trap these errors and prevent a major crash
- The definitions of the geoms need testing - are all the aesthetics and layer parameters correct?
=> Updated graphics geom controls to new system and implemented on general graphics dialog

instat/clsRLink.vb
=> Package name added in clsRLink

instat/static/InstatObject/R/data_object_R6.R
Adding "lazyeval::" before interp function
=> Bug fix - adding package

instat/dlgClimdex.Designer.vb, instat/dlgClimdex.vb
Added package names to this dialog and tidied it up a little.
When I looked into the code, however, there are quite a few problems.
Shall I disable OK for this dialog for the release tomorrow since the changes required won't be done in time?
@stevekogo @dannyparsons
=> Climdex - Package name and tidy up

instat/dlgCombineforGraphics.Designer.vb, instat/dlgCombineforGraphics.vb
Adding the package to combine for graphics
General fixes/tidy ups
@dannyparsons this can be merged
=> Package combine

instat/dlgAppend.vb
I believe dplyr is a pre-loaded package, but adding it for consistency and so the user can easily see the package name
=> Adding package for Append

instat/dlgFromLibrary.vb
@dannyparsons this is ready to merge.
Added package `utils`
=> Package from library

instat/dlgExportToCPT.vb, instat/dlgNewMarkovChains.vb
=> Packages: Export to CPT, New markov chains

instat/sdgSummaries.vb
=> fixed bug in summaries sub dialog

instat/dlgNewSummaryTables.vb, instat/ucrCore.vb
=> fixed bugs in summary tables dialog

instat/dlgTransformText.vb
=> fixed bug in transform text dialog

instat/dlgImportDataset.vb
=> Import dataset - bug fix

instat/dlgMakeDate.vb, instat/static/InstatObject/R/data_object_R6.R
We had developer errors since the parameters of the ucrinputs were not set properly after the changes made recently in the ucrCore on setrcode. @africanmathsinitiative/developers this is ready for REVIEW. 
Note: On Reopen  the controls of the respective radio button do not appear until you change the radio button.Can someone help. Line 255 causes it- Not sure how to fix that quickly
=> Dlg MakeDate Bug Fix

instat/dlgOneVariableGraph.vb, instat/sdgOneVarGraph.vb, instat/ucrELementTextControl.Designer.vb, instat/ucrELementTextControl.vb, instat/ucrElementLineControl.Designer.vb, instat/ucrElementLineControl.vb, instat/ucrElementRectControl.Designer.vb, instat/ucrElementRectControl.vb, instat/ucrGridUnit.vb
@africanmathsinitiative/developers   made the ucrinputs non-editable  with minor edits.
=> Dlg one var graph -Minor edits to curb bugs

instat/dlgGeneralForGraphics.vb, instat/sdgLayerOptions.vb, instat/sdgPlots.vb
Fixes #3225 
@dannyparsons  these have now been added in already
=> Gereral Graphics fixes

instat/dlgScatterPlot.Designer.vb, instat/dlgScatterPlot.vb
Fixes #3018 
@dannyparsons  Line of best fit Added. 
@mmumbo Thanks for this, it looks really good.
=> Adding Line of best fit in scatterplot

instat/dlgSplitText.vb, instat/sdgClimdexIndices.vb
@dannyparsons This is ready to go in.
=> Split textand climdex indices

instat/dlgFrequency.Designer.vb, instat/dlgFrequency.vb, instat/dlgNewSummaryTables.Designer.vb, instat/dlgNewSummaryTables.vb, instat/static/InstatObject/R/data_object_R6.R
@africanmathsinitiative/developers this is ready to review. We would like this in 0.3.
Here is a new implemented frequency tables dialog (not yet in form main, so add it in temporarily for the review)
And minor bug fixes to the summary tables dialog
=> Frequencies dialog

instat/dlgImportGriddedData.vb
@dannyparsons  this is a minor fix.This is ready to be merged.
=> developer error fix

instat/static/InstatObject/R/data_object_R6.R, instat/ucrFilter.vb
also made combo box on filter control non editable
=> fixes bug in one variable describe

instat/dlgRegressionSimple.vb
Fixed a bug on Two variable > Fit model (dlgRegressionSimple) where it was not updating properly.
This fixes #3259
=> dlgRegressionSimple

instat/dlgPolynomials.vb
On rdo Centre, the receiver would reset automatically on reopen.
=> Polynomial- Bug Fix

instat/frmMain.Designer.vb
=> frmmain disabled dialogs

instat/frmMain.Designer.vb
=> Adding ellipsis

instat/dlgOneVarCompareModels.vb, instat/dlgThreeVariablesModelling.vb, instat/sdgOneVarCompareModels.vb, instat/sdgSimpleRegOptions.vb
Added package names for sdgSimpleRegOptions
Disabled chkMultiplePlots. Checked with @lilyclements function autoplot does not support glm/lm functions.
Linked three variable modelling dialog with ucrDistributions-was bugging
=> Models Dialogs 

instat/dlgOneWayFrequencies.vb, instat/dlgThreeVariableFrequencies.vb, instat/dlgTwoWayFrequencies.vb
@stevenndungu here I have corrected the setting of R code for the freq dialogs (still not complete solution) but we cannot be setting controls directly in set defaults - that was a temp fix for beta version which is now not acceptable. This must be done through setting the R code.
=> Stevenndungu frequencies dlgs

instat/dlgOneWayFrequencies.vb, instat/dlgThreeVariableFrequencies.vb, instat/dlgTwoWayFrequencies.vb
Addressed issue of resetting of rdo both on reopen; fixes #3267
=> Frequencies Dlgs

instat/sdgOneVarUseModFit.vb
Here I have set the defaults for ucrInputQuantiles.This shouldn't take time to review.
=> Updatingone var use model

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
Bug fixes on the Start of Rains dialog
Here:
- Coping with changing between datasets
- Fixing save column option
=> Start of Rains bug fixes

instat/dlgFromLibrary.Designer.vb, instat/dlgOptions.Designer.vb, instat/dlgOptions.vb
Fixes  #1985 
@dannyparsons  this is already done. 
Includes centering radiobuttons for dlgFromLibrary
=> Adding option to display same dataframe selected in dialog

instat/sdgClimdexIndices.vb, instat/sdgDescribeDisplay.vb, instat/sdgMerge.vb, instat/sdgOneWayFrequencies.vb, instat/sdgThemes.vb, instat/sdgTwoWayFrequencies.vb, instat/ucrELementTextControl.vb, instat/ucrElementLineControl.vb, instat/ucrElementRectControl.vb, instat/ucrGridUnit.vb
Added to all sub-dialogues except those that people are working on currently, of which they should add ultimately before their changes are merged.
Fixes #3473
=> Adding bCloneIfNeeded on sdg and ucrs

instat/static/InstatObject/R/Backend_Components/summary_functions.R, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
=> current filter recognised by summary functions

instat/dlgViewAndRemoveKeys.vb, instat/dlgViewAndRemoveLinks.vb, instat/ucrReceiverSingle.vb
@dannyparsons  this is ready for merging
fixes #2815
=> Link and Keys autofill

instat/frmLog.Designer.vb, instat/frmLog.vb, instat/sdgSimpleRegOptions.Designer.vb, instat/sdgSimpleRegOptions.vb, instat/ucrLog.Designer.vb, instat/ucrLog.resx, instat/ucrLog.vb
Fixes #3460 
@africanmathsinitiative/developers  there is this new nice feature now in R-Instat.  Once you have run things on R-Instat, you can now go to log window, right click and be able to run the same in R-Studio. 
@dannyparsons this is ready for you. 
Thanks.
=> Opening Logs in R-Studio

instat/ucrGeom.vb
=> fixed geom controls syncing issue

instat/dlgStack.Designer.vb, instat/dlgStack.vb
* Tidied up the dialog
* Extended the ucrChk so that all the words in the .Text were in there
* Tab order
* Alignments
=> Stack alterations

instat/dlgSpells.vb, instat/dlgStartofRains.vb
Consistency in dlgSpells headings
Added SOR headings
=> Title headings

instat/dlgStartofRains.vb
@dannyparsons noticed I didn't actually fully implement the str headings. I've corrected it now. this can be merged.
=> SOR Heading fix

instat/dlgTwoVariableFitModel.Designer.vb, instat/sdgSimpleRegOptions.Designer.vb, instat/sdgSimpleRegOptions.vb
@dannyparsons this can be merged. I'm just fixing some layout problems on dlgTwoVarFitModel and a sdg for it
=> TwoVarFit - layout edits

instat/sdgOneVarFitModel.Designer.vb
@dannyparsons this is ready to review
=> Sub tidy up

instat/ucrLog.Designer.vb, instat/ucrLog.vb, instat/ucrScript.Designer.vb, instat/ucrScript.vb
@dannyparsons  this is ready for you. 
Fixes #2900
=> Auto scroll on Windows

instat/dlgSplitText.Designer.vb, instat/dlgSplitText.vb
@africanmathsinitiative/developers this is ready to review. We want this in today's version so this is a high priority.
Added a new radio button at the top to give the option for the `multi.split` function. This is under the radio button "Into Binary Columns"
See #3667 for a further explanation of this
=> Split text

instat/dlgOneVarFitModel.vb, instat/dlgOneVarUseModel.vb, instat/dlgTwoVariableFitModel.vb
Still to do:
* Sort last_likelihood bug
* Checkbox is checked upon reopening
* OK is disabled upon reopening
* Error if I run a factor with the wrong distribution (e.g. Normal)
=> One var fit fixes

instat/dlgThreeVariablesModelling.vb, instat/sdgSimpleRegOptions.vb
@africanmathsinitiative/developers  this ready for review
This fixes all the Bugs mentioned in issue #3697.  We have tested together @AlexSananka   @shadrackkibet and could not replicate any of the bugs. 
Note:
Visreg function has parameter `gg` which converts plots to be of ggplot type but this does not work with  three  and four variables models. Therefore I have set it to plot based on lattice package. Which works fine
=> Model bug fixes

instat/dlgPrincipalComponentAnalysis.Designer.vb, instat/dlgPrincipalComponentAnalysis.vb, instat/sdgPrincipalComponentAnalysis.Designer.vb, instat/sdgPrincipalComponentAnalysis.vb
This is ready to merge @dannyparsons
=> PCA update

instat/clsRLink.vb
=> Changed how backup log runs

instat/dlgDeleteDataFrames.Designer.vb, instat/dlgDeleteDataFrames.vb, instat/dlgStartofRains.vb, instat/frmMain.Designer.vb
Made edits required from #3770 (sorry I forgot to link up the commit to it!)
=> Delete Data Frames layout edits

instat/dlgFromLibrary.Designer.vb, instat/dlgFromLibrary.vb, instat/dlgImportDataset.vb
@africanmathsinitiative/developers this is ready to review. Here:
* Fixed the bug in #3753
* Minor edit to layout for dlgFromLibrary
* Added a ucrSave to dlgFromLibrary
=> Adding NewDataFrame, fixing bug

instat/dlgBoxPlot.vb, instat/ucrSelector.vb
implemented on boxplot dialog. Needs to be implemented on all other specific graphics dialogs.
=> added ggplot operator field to selector to enable clearing parameters on data frame change

instat/dlgOpenNetCDF.Designer.vb, instat/dlgOpenNetCDF.vb, instat/instat.vbproj, instat/sdgOpenNetCDF.Designer.vb, instat/sdgOpenNetCDF.resx, instat/sdgOpenNetCDF.vb
This is ready to merge @dannyparsons
=> Adding sub to NetCDF

instat/frmMain.Designer.vb
@dannyparsons this can be merged
=> Enable net cdf

instat/instat.vbproj, instat/sdgInventoryPlot.Designer.vb, instat/sdgInventoryPlot.resx, instat/sdgInventoryPlot.vb
@dannyparsons this is a new dialog that needs merging
=> sdgInventoryplot

instat/dlgUnstack.Designer.vb, instat/dlgUnstack.vb
@africanmathsinitiative/developers this is ready to review.
fixing #3775 and also sorted updating changes for dlgUnstack
=> Dlg unstack fix

instat/dlgStartofRains.vb
=> SoR - parameter positions

instat/dlgDuplicatesConstructed.vb
@africanmathsinitiative/developers This is a minor edit that fixes a developer error in dlgduplicates.
Someone can have a quick look.
=> Duplicates fix

instat/dlgImportDataset.Designer.vb, instat/dlgImportDataset.vb
This is ready for review @africanmathsinitiative/developers. See #3877 for details
=> Import option

instat/dlgClimaticSummary.vb
@africanmathsinitiative/developers this is ready to review.
Minor fixes:
* iCallType
* Parameter positions
* Naming convention
=> Dlg climatic summary

instat/dlgOpenNetCDF.Designer.vb, instat/dlgOpenNetCDF.vb, instat/sdgOpenNetCDF.Designer.vb, instat/sdgOpenNetCDF.vb
=> Open net cdf

instat/dlgViewAndRemoveLinks.vb
Here the panel wasn't resetting and noticed we didn't have a click reset a sub.
=> View and remove links fix

instat/dlgPlotRegion.Designer.vb, instat/dlgPlotRegion.resx, instat/dlgPlotRegion.vb, instat/frmMain.Designer.vb, instat/frmMain.vb, instat/instat.vbproj
@dannyparsons  this ready for merging.
=> dlgplotRegion

instat/ucrColumnMetadata.Designer.vb, instat/ucrDataFrameMetadata.Designer.vb, instat/ucrDataView.Designer.vb, instat/ucrLog.Designer.vb, instat/ucrOutputWindow.Designer.vb, instat/ucrReceiverSingle.designer.vb, instat/ucrScript.Designer.vb, instat/ucrVariablesAsFactor.Designer.vb
@africanmathsinitiative/developers if I have done this well then you shouldn't see any change (almost). I have changed how controls in the main form are positioned. This links to #3864 where controls do not resize correctly on all screens. I can replicate this on my machine so I have been tested.
So hopefully this shouldn't affect the way controls display on normal screens like yours. If you do get any strange designer changes let me know. A small visible change is that there is now a small margin between controls within the main windows. It's hardly noticeable, I think it looks ok, but if it's preferred the other way without margins I can change that.
=> added table containers to main windows (to have better positioning on screens that zoom) and corrected docking on receiver controls

instat/dlgImportOpenRefine.vb
@dannyparsons this is ready for merging.
=> Import open refine

docs/index.html
Adding other website link @dannyparsons
=> Adding other website download link

instat/frmMain.Designer.vb, instat/frmMain.vb
@dannyparsons here i have enabled Display daily on Climatic>Checkdata.This is ready for merging.
=> Frm Change.

instat/clsRLink.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
@Patowhiz @maxwellfundi these are also useful for the variable sets dialog
=> added methods to use variable sets in dialogs

instat/dlgMakeDate.Designer.vb, instat/dlgMakeDate.resx, instat/dlgMakeDate.vb
=> dlgMakeDate

instat/dlgCumulativeDistribution.vb, instat/dlgDotPlot.vb, instat/dlgHistogram.vb, instat/dlgLinePlot.vb, instat/dlgRugPlot.vb
@africanmathsinitiative/developers  this is ready for review. Open any dataset then go to Describe>Specific and open any dialog and fill up the receivers
Open the options dialog, then layers, click add layers and see if it crashes. 
Fixes #3932
=> Fixing layers Bugs in graphics

instat/dlgBarAndPieChart.vb, instat/dlgSummaryBarOrPieChart.vb
@dannyparsons this is ready for you. 
thanks
=> Layers bug fix for summarybars and barchart

instat/dlgAddKey.vb, instat/static/InstatObject/R/data_object_R6.R
In particular, summaries can now be done by a factor column which contains missing values.
=> Allowed key columns to contain missing values

instat/clsRLink.vb, instat/dlgSummaryBarOrPieChart.Designer.vb
=> selector remains in same place when refreshing

instat/clsInstatOptions.vb, instat/clsInstatOptionsDefaults.vb, instat/dlgOptions.Designer.vb, instat/dlgOptions.vb, instat/frmMain.Designer.vb, instat/frmMain.vb
@dannyparsons  thats now done.  I need to add the same on the view menu now
=> Adding options to show or hide special menus

instat/clsGridLink.vb, instat/dlgHideDataframes.Designer.vb, instat/dlgHideDataframes.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R, instat/ucrDataView.Designer.vb, instat/ucrDataView.vb
=> Implemented hiding data frames

instat/dlgClimaticSummary.Designer.vb, instat/dlgClimaticSummary.resx, instat/dlgClimaticSummary.vb
@africanmathsinitiative/developers This fixes **1** of #4106.
=> Climatic Summary.

instat/dlgCountryColouredMap.Designer.vb, instat/dlgCountryColouredMap.resx, instat/dlgDefineCRI.Designer.vb, instat/dlgDefineCRI.resx, instat/dlgDefineCorruption.Designer.vb, instat/dlgDefineCorruption.resx, instat/dlgDefineCorruptionOutputs.Designer.vb, instat/dlgDefineCorruptionOutputs.resx, instat/dlgDefineRedFlags.Designer.vb, instat/dlgDefineRedFlags.resx, instat/dlgFitCorruptionModel.Designer.vb, instat/dlgFitCorruptionModel.resx, instat/dlgReferenceLevel.Designer.vb, instat/dlgReferenceLevel.resx
@dannyparsons This are dialogs for procurement menu.
=> Localizable procurement Menu.

instat/frmMain.Designer.vb
=> Procurement menu changes

instat/dlgBarAndPieChart.vb, instat/dlgCumulativeDistribution.vb, instat/dlgGeneralForGraphics.vb, instat/dlgHistogram.vb, instat/dlgLinePlot.vb, instat/dlgRugPlot.vb, instat/dlgScatterPlot.vb, instat/static/InstatObject/R/instat_object_R6.R, instat/ucrAdditionalLayers.vb
=> layer order bug fix and general graphics dialog display fixed

instat/Translations.vb, instat/clsRSyntax.vb, instat/dlgContrasts.vb, instat/dlgCopyDataFrame.Designer.vb, instat/dlgCopyDataFrame.resx, instat/dlgDescribeTwoVarGraph.vb, instat/dlgImportFromODK.vb, instat/dlgOpenSST.vb, instat/dlgTransformText.vb, instat/instat.vbproj, instat/sdgDescribeTwoVarGraph.vb, instat/ucrButtons.vb
=> Fixes bugs caused by localisation process + ODK import password fix

instat/dlgDotPlot.vb, instat/dlgLinePlot.vb, instat/dlgOneVarFitModel.vb, instat/dlgRecodeFactor.vb, instat/dlgRugPlot.vb, instat/dlgScatterPlot.vb, instat/dlgViewGraph.vb
=> Various bug fixes

instat/frmMain.Designer.vb, instat/frmMain.resx
@dannyparsons  this is ready to merge. 
It is disabled for now as it doesn't open anything yet.
=> Adding Mosaic to frmMain

instat/dlgClimaticCheckDataRain.Designer.vb, instat/dlgClimaticCheckDataRain.vb
@shadrackkibet I've fixed the filter OR combination issue for the checkboxes. There is still a few things to get sort out on the dialog so please test it further but it is looking good and usable for Roger next week so that's great and we will merge this for today.
=> Shadrackkibet rainfall

instat/dlgClimaticCheckDataRain.Designer.vb, instat/dlgClimaticCheckDataRain.vb
=> Climatic Check Data Rainfall.

instat/ucrGeom.vb
=> Geom density2d

instat/dlgClimaticCheckDataRain.Designer.vb, instat/dlgClimaticCheckDataRain.vb, instat/frmMain.Designer.vb, instat/frmMain.resx, instat/frmMain.vb
@dannyparsons  here i have enabled the Rainfall and temperature dialog in the form main. 
Also sorted out parameter position for function_exp.
=> Frm Main edits.

instat/dlgCalculator.designer.vb, instat/dlgCalculator.vb, instat/ucrCalculator.Designer.vb, instat/ucrCalculator.resx, instat/ucrCalculator.vb
@africanmathsinitiative/developers I have make improvements to the calculator here. This fixes #4125,#4128 and #4126.
This is ready for review and testing.
=> dlgCalculator & ucrCalculator.

instat/ucrScript.Designer.vb, instat/ucrScript.vb
To test it, run the software and send something to script, then from the script window right click > Open Script
Fixes #4115
=> Opening Script from Script Window 

instat/ucrGeom.vb
=> Adding group for geom_line

instat/dlgBoxPlot.vb
=> dlgBoxplot

instat/dlgClimaticCheckDataTemperature.resx, instat/dlgClimaticCheckDataTemperature.vb
@dannyparsons this is ready for merging, i have sorted out the groupby function issue when the station receiver is empty.
I have also made minor  designer fixes though this is not yet perfect.
=> Temperature dialog

instat/ucrCore.vb
@dannyparsons  Please review this code. We edited the ucrCore with @volloholic  and this pull request contains the changes we made to ensure we could do linking with more than one control. 
So we changed the displaycontrol from a single control to a list, tweaked code to match the new changes and work in the same way.
=> ucrCore Changes

instat/ucrELementTextControl.Designer.vb, instat/ucrELementTextControl.vb
=> Adding decimal paces on Theme options

instat/dlgLinePlot.vb
=> Adding group parameter for Lineplot

instat/dlgClimaticCheckDataRain.Designer.vb, instat/dlgClimaticCheckDataRain.resx, instat/dlgClimaticCheckDataRain.vb
@africanmathsinitiative/developers this is ready for review. This fixes some part of  #2392.
=> QC Rainfall

instat/dlgBackupManager.Designer.vb, instat/dlgBackupManager.resx, instat/dlgBackupManager.vb, instat/instat.vbproj
=> Empty dlgBackupManager

instat/dlgColumnStats.vb
@africanmathsinitiative/developers  this is ready for review. Fixes #4302
=> dlgColumnstats

instat/dlgBarAndPieChart.vb, instat/dlgBoxPlot.vb, instat/sdgPlots.Designer.vb, instat/sdgPlots.resx, instat/sdgPlots.vb
@africanmathsinitiative/developers  This is ready for review. 
Fixes #4251 and #4297
=> Adding coordflip to sdgplots

instat/dlgViewLabelsAndLevels.Designer.vb, instat/dlgViewLabelsAndLevels.resx, instat/dlgViewLabelsAndLevels.vb
@africanmathsinitiative/developers this fixes display of output into the browser. Fixes part of #4324
=> View labels And Levels

instat/dlgClimaticCheckDataTemperature.Designer.vb, instat/dlgClimaticCheckDataTemperature.resx, instat/dlgClimaticCheckDataTemperature.vb
=> QC Temperature.

instat/static/InstatObject/R/Backend_Components/summary_functions.R
=> added original_level option to calculate summary method

instat/clsCondition.vb, instat/dlgThreeVariableFrequencies.vb
@africanmathsinitiative/developers this is ready for review.This solves the developer error when you switch between radio buttons on graph frequencies and then reopen the dialog.
=> Three way frequency.

instat/frmMain.Designer.vb, instat/frmMain.resx, instat/frmMain.vb, instat/ucrScript.Designer.vb, instat/ucrScript.vb
@rdstern  @dannyparsons  here is the current menu for the right click on the script window. 
The Save Script to File  saves the script to a text file and the Open Script From File clears the current text on the script window before loading the script window with the contents of the selected, previously saved text file. 
Fixes #4348
=> Saving Script to file

instat/static/InstatObject/R/Backend_Components/calculations.R, instat/static/InstatObject/R/Backend_Components/instat_comment.R, instat/static/InstatObject/R/Backend_Components/link.R, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
@africanmathsinitiative/developers methods for comments are now implemented here so dialogs can be created.
=> added comments to instat object and fixed compatibility issue for old instat objects

instat/dlgMakeDate.vb
=> Make date dialog

instat/ucrCalculator.vb
@africanmathsinitiative/developers this is ready for review. Fixes #4128
=> ucrCalculator

instat/dlgStringDistance.vb
=> Distance Dialog.

instat/instat.vbproj, instat/ucrDateTimePicker.Designer.vb, instat/ucrDateTimePicker.resx, instat/ucrDateTimePicker.vb
needed for #4075 and any dialog where a full date needs to be selected
=> created date picker control

instat/dlgHypothesisTestsCalculator.Designer.vb, instat/dlgHypothesisTestsCalculator.resx, instat/dlgHypothesisTestsCalculator.vb
In progress. Fixes #4385 
**Designer layout:**
=> Hypothesis Calculator.

instat/dlgDisplayDailyData.Designer.vb, instat/dlgDisplayDailyData.resx, instat/dlgDisplayDailyData.vb
=> Display daily climatic data

instat/dlgRegularSequence.vb, instat/frmMain.Designer.vb, instat/frmMain.resx, instat/frmMain.vb
@dannyparsons  i have added regular sequence dialog on  **Prepare>Column:Date >Generate Dates** and **Climatic>Dates>Generate Dates** . However , i am not sure if this is the efficient way to do this.
This is ready for you to review.
=> FrmMain  & Regular sequence

instat/UcrPanel.vb, instat/dlgClimaticSummary.Designer.vb, instat/dlgClimaticSummary.resx, instat/dlgClimaticSummary.vb, instat/instat.vbproj, instat/sdgDoyRange.Designer.vb, instat/sdgDoyRange.resx, instat/sdgDoyRange.vb, instat/static/InstatObject/R/Backend_Components/calculations.R, instat/ucrCheck.vb, instat/ucrCore.vb, instat/ucrDayOfYear.vb, instat/ucrInput.vb, instat/ucrNud.vb, instat/ucrReceiverSingle.vb, instat/ucrReorder.vb
Implemented on climatic summaries dialog
=> Day of year range subdialog

instat/dlgDisplayDailyData.Designer.vb, instat/dlgDisplayDailyData.resx, instat/dlgDisplayDailyData.vb
=> Display Daily  Data

instat/ucrScript.vb
@dannyparsons  Added consistent methods for textboxes
=> Adding cut and copy

instat/dlgClimaticSummary.resx, instat/dlgClimaticSummary.vb, instat/sdgDoyRange.Designer.vb, instat/sdgDoyRange.vb
@dannyparsons  this is ready for you. Roger also suggested  we restrict within-year receiver to only factors.
=> Climatic Summaries

instat/ucrColumnMetadata.Designer.vb, instat/ucrColumnMetadata.vb, instat/ucrDataView.Designer.vb, instat/ucrDataView.vb
@dannyparsons  this is ready for you.
=> Right click

instat/clsRLink.vb
=> more informative error message for being unable to save graphs in temp folder

instat/sdgLayerOptions.vb, instat/ucrGeom.vb
@rdstern finally found the cause of this, couldn't find an issue on it to close
@maxwellfundi @bethanclarke I can explain the cause of this issue if you would like to know
=> fixes bug causing extra boxplot layer added to graphs

instat/dlgColumnStructures.vb
Fixed ucrChkColourColumnsByStructure default state ONLY.
Fixes #4367
I've commented some of the code statements
=> Column Structure

instat/UcrGeomListWithAes.vb
This now correctly sets the data frame for each layer.
=> fixed bug with creating graphs from multiple data frames

instat/frmMain.Designer.vb, instat/frmMain.resx
@maxwellfundi  this is ready for you.
=> Enabling SPI

instat/dlgLinePlot.vb
@mmumbo I have edited this dialog now to produce this kind of graph as you would like 
Fixes  #4556
=> Edits Lineplot

instat/dlgClimaticSummary.vb
@maxwellfundi please have a look at this.
I have removed brackets on the filter to be consistent with other prepare climatic dialogs.
=> Climaticsummary

instat/sdgCreateFilter.Designer.vb, instat/sdgDataOptions.Designer.vb, instat/sdgPlots.Designer.vb
Fixes #4567 Setting for the Filter sub-dialogue .
=> Removed TopMost property

instat/dlgExportGraphAsImage.vb, instat/ucrReceiverSingle.vb
=> Fixing export graph as image bug

instat/clsGridLink.vb
@dannyparsons please review this.
Fixes #4626.
=> Logical columns

instat/clsQualityControl.vb, instat/dlgClimaticCheckDataTemperature.Designer.vb, instat/dlgClimaticCheckDataTemperature.resx, instat/dlgClimaticCheckDataTemperature.vb
@dannyparsons this is ready to merged, I have added a groupbox as requested by @rdstern and also fixed **1** of #4604
=> Qc Tempearture - Calculated columns for both Tmin and Tmax (Same and Jump options)

instat/dlgStartofRains.Designer.vb, instat/dlgStartofRains.vb
@dannyparsons  this is ready for you to review. I have implemented start_doy and start_dates as sub_calcuations and added them as combined calculation. 
@rdstern  here is the latest design of start rains dialog.
=> Adding start_dates as an option - Start of Rains

instat/dlgColumnStats.vb, instat/sdgSummaries.Designer.vb, instat/sdgSummaries.resx, instat/sdgSummaries.vb, instat/static/InstatObject/R/Backend_Components/summary_functions.R
=> Column Summaries

instat/frmMain.Designer.vb, instat/frmMain.resx, instat/frmMain.vb
@dannyparsons this is ready for you.
=> Adding Compare columns to frmmain

instat/dlgUnstack.vb
@dannyparsons please review this.
Fixes #4679.
=> Removing SetAssignTo

instat/dlgCalculateTreatmentDifferences.Designer.vb, instat/dlgCalculateTreatmentDifferences.resx, instat/dlgCalculateTreatmentDifferences.vb, instat/dlgCompareTreatmentLines.Designer.vb, instat/dlgCompareTreatmentLines.resx, instat/dlgCompareTreatmentLines.vb, instat/instat.vbproj
@dannyparsons here are the blank dialogs. Hope it is what you wanted.
=> New treatment dialogs

instat/dlgCorrelation.vb
@dannyparsons this ready for review.
Fixes #4696.
=> Correlations

instat/dlgImportDataset.vb
@dannyparsons this is ready for you.
=> Bug in the current Master

instat/dlgOptionsByContextBoxplot.Designer.vb, instat/dlgOptionsByContextBoxplot.vb
@dannyparsons this is ready to review
=> Minor boxplot edits

instat/clsQualityControl.vb, instat/dlgClimaticCheckDataTemperature.vb
=> Qc Temperature

instat/DlgDefineClimaticData.Designer.vb, instat/DlgDefineClimaticData.resx, instat/DlgDefineClimaticData.vb, instat/static/InstatObject/R/data_object_R6.R
@africanmathsinitiative/developers this is ready for review.  Fixes #4678 ,Fixes #4665, Fixes #4378
=> Adding key and check for Duplicates in define climatic data.

instat/dlgShowNonnumericValues.Designer.vb, instat/dlgShowNonnumericValues.resx, instat/dlgShowNonnumericValues.vb, instat/instat.vbproj
@maxwellfundi  this is ready for you to merge.
=> New Show Non-numeric values dialog.

instat/dlgShowNonnumericValues.Designer.vb, instat/dlgShowNonnumericValues.resx, instat/dlgShowNonnumericValues.vb
@africanmathsinitiative/developers this is ready for review. Fixes #4766
=> Show non numeric columnc

instat/frmMain.Designer.vb, instat/frmMain.resx, instat/frmMain.vb
@maxwellfundi @dannyparsons  please merge this.
=> Adding find non numeric values dialog to the main form

instat/dlgAnonymiseIDColumn.Designer.vb, instat/dlgAnonymiseIDColumn.resx, instat/dlgAnonymiseIDColumn.vb, instat/instat.vbproj
@maxwellfundi please merge this.
=> New anonymise ID column dialog

instat/dlgClimaticLengthOfSeason.Designer.vb, instat/dlgClimaticLengthOfSeason.resx, instat/dlgClimaticLengthOfSeason.vb, instat/instat.vbproj
@maxwellfundi please merge this.
=> New length of season dialog

instat/dlgDisplayDailyData.vb, instat/dlgInventoryPlot.vb, instat/dlgSPI.vb, instat/dlgSpells.vb
@dannyparsons  This are just minor fixes. Please have a look at it.
=> Focus Receiver.

instat/dlgHelpVignettes.Designer.vb, instat/dlgHelpVignettes.resx, instat/dlgHelpVignettes.vb, instat/instat.vbproj
@maxwellfundi please merge this.
=> New help dialog

instat/dlgDuplicates.vb
@africanmathsinitiative/developers please review this.
Fixes #4677.
=> Duplicates

instat/dlgAnonymiseIDColumn.Designer.vb, instat/dlgAnonymiseIDColumn.vb, instat/static/InstatObject/R/stand_alone_functions.R
=> Anonymise ID column dialog

instat/frmMain.Designer.vb, instat/frmMain.resx, instat/frmMain.vb
@dannyparsons @maxwellfundi please merge this.
=> Adding Anonymise id column dialog.

instat/dlgClimaticLengthOfSeason.Designer.vb, instat/dlgClimaticLengthOfSeason.vb
=> Length of the  season dialog

instat/static/InstatObject/R/data_object_R6.R
=> Make date problem with day 60 for Non-leap years.

instat/dlgClimaticMaps.vb, instat/dlgImportShapeFiles.Designer.vb, instat/dlgImportShapeFiles.vb
This is the initial implementation of the dialog. You can now import shape file, convert to data frame and load to R instat. @shadrackkibet and I have managed to do this as shown in the figure below;
@dannyparsons @maxwellfundi @rdstern @volloholic
=>  Importing shape files 

instat/dlgMakeDate.Designer.vb, instat/dlgMakeDate.resx, instat/dlgMakeDate.vb, instat/static/InstatObject/R/data_object_R6.R, instat/static/InstatObject/R/instat_object_R6.R
fixes #4233
- Implemented option (in R code and dialog) to have year, month or day as a fixed value in Year Month Day format, as described in #4233 
- Tidied and simplified dialog code and small bug fixes
Because of the general tidying of the code, please test that the general functionality of the dialog is working as before, as well as the new features.
=> Added fixed value options in Make Date dialog

instat/dlgConvertColumns.Designer.vb, instat/dlgConvertColumns.resx, instat/dlgConvertColumns.vb, instat/static/InstatObject/R/data_object_R6.R, instat/ucrColumnMetadata.Designer.vb, instat/ucrColumnMetadata.resx, instat/ucrColumnMetadata.vb
- Integer to Numeric conversion now forces type to change to numeric (needed when having errors merging by an integer and numeric column)
- Option added to convert dialog to do a "simple" convert to numeric (ignoring any non numeric values) and a convert to factor which ignores existing labels
- Added right click option in Column Metadata window to delete labels
fixes #4709
=> Improvements converting column types

instat/dlgMerge.Designer.vb, instat/dlgMerge.resx, instat/dlgMerge.vb
- added display of merging column on main merge dialog
- prevented running dialog if no merging columns
=> Merge dialog - display merging columns

instat/sdgSummaries.Designer.vb, instat/sdgSummaries.vb
Fixes  #4499 @maxwellfundi this is a minor fix. Please merge this so that @rdstern can test this.
=> Summaries Subdialog

instat/dlgConversions.Designer.vb, instat/dlgConversions.resx, instat/dlgConversions.vb, instat/instat.vbproj
@dannyparsons please merge this.
=> Conversions

instat/dlgEvapotranspiration.Designer.vb, instat/dlgEvapotranspiration.resx, instat/dlgEvapotranspiration.vb
=> Evapotranspiration

instat/frmMain.Designer.vb, instat/frmMain.resx
@maxwellfundi please merge this.
=> Enabling Evapotranspiration dialog on frmmain

instat/dlgMapOption.Designer.vb, instat/dlgMapOption.resx, instat/dlgMapOption.vb, instat/instat.vbproj
@maxwellfundi  Please merge this
=> Map Option subdialog.

instat/dlgMapOption.vb, instat/instat.vbproj, instat/sdgMapOption.Designer.vb, instat/sdgMapOption.resx, instat/sdgMapOption.vb
=> Renaming subdialog

instat/dlgClimaticMaps.Designer.vb, instat/dlgClimaticMaps.vb, instat/dlgImportShapeFiles.vb, instat/sdgMapOption.Designer.vb, instat/sdgMapOption.resx, instat/sdgMapOption.vb
@maxwellfundi The map option  sub-dialog is ready to be merged.
=> Map option

instat/dlgClimaticCheckDataRain.Designer.vb, instat/dlgClimaticCheckDataRain.resx, instat/dlgClimaticCheckDataRain.vb, instat/static/InstatObject/R/Backend_Components/summary_functions.R
@africanmathsinitiative/developers this is ready for review. Fixes #4947
=> Qc Rainfall.

instat/dlgAddKey.vb
Fixes #4976 . @dannyparsons this is a minor edit. Please have a look at it.
=> Add Key dialog

instat/dlgAnonymiseIDColumn.vb, instat/dlgCompareColumns.vb, instat/dlgDuplicates.vb, instat/dlgExportGraphAsImage.vb, instat/dlgExportRObjects.vb, instat/dlgExportRWorkspace.vb, instat/dlgFindNonnumericValues.vb, instat/dlgOpenNetCDF.vb
Fixes #4978 . @dannyparsons please merge this.
=> Adding help IDs

instat/dlgImportShapeFiles.vb
@africanmathsinitiative/developers  This is ready to be tested. Code has been added into shape file dialog to split the geometry to longitude and latitude. This will enable us to use the geom_text.  Use the attached file to test
[Rwandan Shape files.zip](https://github.com/africanmathsinitiative/R-Instat/files/2400172/Rwandan.Shape.files.zip)
=> Splitting the  geometry

instat/dlgMosaicPlot.Designer.vb, instat/dlgMosaicPlot.resx, instat/dlgMosaicPlot.vb, instat/instat.vbproj, instat/static/InstatObject/R/Rsetup.R, instat/ucrReceiver.vb, instat/ucrReceiverMultiple.vb
Part of #4196
Note:
- You need to install `ggmosaic` package first. This will be added to package list in next release
- `Mosaic Plot Options` currently doesn't work as the geom is not yet added to our list of geoms. It will be added as part of #4196.
=> Mosaic plots dialog

instat/clsGgplotDefaults.vb, instat/dlgPICSARainfall.vb, instat/sdgPICSARainfallGraph.Designer.vb, instat/sdgPICSARainfallGraph.resx, instat/sdgPICSARainfallGraph.vb
=> Bug fixes and additional options added to PICSA rainfall graph dialog

instat/dlgPICSARainfall.vb, instat/sdgPICSARainfallGraph.Designer.vb, instat/sdgPICSARainfallGraph.resx, instat/sdgPICSARainfallGraph.vb
values rounded in display of summaries in label
added transparency for labels
fixed developer bug with grid line controls
=> PICSA graphs dialog improvements and bug fixes

instat/dlgPICSARainfall.vb, instat/sdgPICSARainfallGraph.Designer.vb, instat/sdgPICSARainfallGraph.resx, instat/sdgPICSARainfallGraph.vb
- added option to include grid lines and fixed defaults
=> PICSA Rainfall graphs dialog improvements
